apiVersion: config.kuberploy.io/v1alpha1
kind: AppConfig
metadata:
  id: "8903b1d4-4c33-4e6b-971e-dc7344664e94"
  name: "state-normal"
spec:
  projectId: "56c34ed2-bb00-47db-9dee-6b629cb32e83"
  applicationId: "8903b1d4-4c33-4e6b-971e-dc7344664e94"
  environmentId: "6e8a8ef6-23a9-4bf6-8471-07c4fe7335c8"
  delivery:
    mode: image
    release:
      repository: "docker.io/library/nginx"
      digest: "sha256:bd43d3d8fdbbe597c36fea489886796466a9ea5b662e8c50897d53e190c88a3d"
  runtime:
    args:
      - "-g"
      - "daemon off;"
    command:
      - "nginx"
    ports:
      -
        containerPort: 80
        name: "http"
        protocol: "TCP"
        servicePort: 80
    probes:
      readiness:
        failureThreshold: 3
        httpGet:
          path: "/"
          port: "http"
          scheme: "HTTP"
        periodSeconds: 3
        timeoutSeconds: 2
    replicas: 1
    resources:
      limits:
        cpu: "100m"
        memory: "128Mi"
      requests:
        cpu: "10m"
        memory: "32Mi"
    strategy:
      type: "RollingUpdate"
    workloadType: "Deployment"
