apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: kp-h-06dd0c5e8ceb49b7b19923862b296d04
    namespace: argocd
    finalizers:
        - resources-finalizer.argocd.argoproj.io
    labels:
        app.kubernetes.io/component: approved-helm-application
        app.kubernetes.io/managed-by: kuberploy
        kuberploy.io/application-id: 06dd0c5e-8ceb-49b7-b199-23862b296d04
        kuberploy.io/environment-id: 967eb9b3-2e47-46f0-b379-3a668b970539
        kuberploy.io/project-id: c5728a9a-55db-4232-aaf0-a849a1e62e2e
    annotations:
        argocd.argoproj.io/manifest-generate-paths: platform/helm-manifests/environments/967eb9b3-2e47-46f0-b379-3a668b970539/applications/06dd0c5e-8ceb-49b7-b199-23862b296d04/revisions/6bf6ddf7-a498-4871-a8ef-76d4774961a4/release.yaml
        kuberploy.io/helm-payload-digest: sha256:1042ae8d893dfa3cf9f8754477a913bcea597960214b49390896c477e9a39f92
        kuberploy.io/helm-payload-revision: 1b32e1a42e8a95aa9812f968ba8d157b5d46d065
        kuberploy.io/helm-release-revision: 6bf6ddf7-a498-4871-a8ef-76d4774961a4
spec:
    project: kp-rc342-qualification-dev
    source:
        repoURL: https://github.com/kuberploy/kuberploy-gitops-test.git
        targetRevision: 1b32e1a42e8a95aa9812f968ba8d157b5d46d065
        path: platform/helm-manifests/environments/967eb9b3-2e47-46f0-b379-3a668b970539/applications/06dd0c5e-8ceb-49b7-b199-23862b296d04/revisions/6bf6ddf7-a498-4871-a8ef-76d4774961a4
        directory:
            recurse: false
            include: release.yaml
    destination:
        server: https://kubernetes.default.svc
        namespace: kp-rc342-qualification-dev
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
            allowEmpty: false
        syncOptions:
            - CreateNamespace=false
            - ServerSideApply=true
