apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: kp-h-06dd0c5e8ceb49b7b19923862b296d04
    namespace: argocd
    finalizers:
        - resources-finalizer.argocd.argoproj.io
    labels:
        app.kubernetes.io/component: approved-helm-application
        app.kubernetes.io/managed-by: kuberploy
        kuberploy.io/application-id: 06dd0c5e-8ceb-49b7-b199-23862b296d04
        kuberploy.io/environment-id: 967eb9b3-2e47-46f0-b379-3a668b970539
        kuberploy.io/project-id: c5728a9a-55db-4232-aaf0-a849a1e62e2e
    annotations:
        argocd.argoproj.io/manifest-generate-paths: platform/helm-manifests/environments/967eb9b3-2e47-46f0-b379-3a668b970539/applications/06dd0c5e-8ceb-49b7-b199-23862b296d04/revisions/b7215e96-6618-4cd6-82fb-df29567f6fd9/release.yaml
        kuberploy.io/helm-payload-digest: sha256:5aae44fe22bc354d19679c873c55fd990d19bf30a81282254950c2274cb1f141
        kuberploy.io/helm-payload-revision: 38cc7ac2eae4fefa878e549ad2167c094351c279
        kuberploy.io/helm-release-revision: b7215e96-6618-4cd6-82fb-df29567f6fd9
spec:
    project: kp-rc342-qualification-dev
    source:
        repoURL: https://github.com/kuberploy/kuberploy-gitops-test.git
        targetRevision: 38cc7ac2eae4fefa878e549ad2167c094351c279
        path: platform/helm-manifests/environments/967eb9b3-2e47-46f0-b379-3a668b970539/applications/06dd0c5e-8ceb-49b7-b199-23862b296d04/revisions/b7215e96-6618-4cd6-82fb-df29567f6fd9
        directory:
            recurse: false
            include: release.yaml
    destination:
        server: https://kubernetes.default.svc
        namespace: kp-rc342-qualification-dev
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
            allowEmpty: false
        syncOptions:
            - CreateNamespace=false
            - ServerSideApply=true
