{
  "apiVersion": "config.kuberploy.io/v1alpha1",
  "kind": "AppConfig",
  "metadata": {
    "id": "dc2bf2ce-5d55-46a5-8722-42103d714da3",
    "name": "rc156-builder-fixture"
  },
  "spec": {
    "applicationId": "dc2bf2ce-5d55-46a5-8722-42103d714da3",
    "delivery": {
      "mode": "image",
      "registryPull": {
        "profileName": "managed-registry",
        "profileRevision": 1,
        "targetId": "f0b03740-c7a9-4ca0-a852-e807c97d2fc8"
      },
      "release": {
        "digest": "sha256:156078e90839e629392d2b3062c81c90d147a060ca0b8580babbdca35465e2d6",
        "repository": "registry-rc153.adminchatmate.com/kuberploy-qualification/projects/0bc72c28-936f-4925-83f5-05a51d18f4bb/services/dc2bf2ce-5d55-46a5-8722-42103d714da3/image"
      }
    },
    "environmentId": "490637d0-88fa-40f0-8902-208a2f5aa6bd",
    "projectId": "0bc72c28-936f-4925-83f5-05a51d18f4bb",
    "runtime": {
      "ports": [
        {
          "containerPort": 8080,
          "name": "http",
          "protocol": "TCP",
          "servicePort": 80
        }
      ],
      "replicas": 1,
      "resources": {
        "limits": {
          "cpu": "250m",
          "memory": "128Mi"
        },
        "requests": {
          "cpu": "25m",
          "memory": "32Mi"
        }
      },
      "strategy": {
        "type": "RollingUpdate"
      },
      "workloadType": "Deployment"
    }
  }
}
