apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: kp-rc405-qualification-dev
    namespace: argocd
    labels:
        app.kubernetes.io/managed-by: kuberploy
        kuberploy.io/environment-id: 17edcd5e-f159-4236-8e12-70d484d3c961
        kuberploy.io/project-id: 92c030ae-83a7-4308-87cc-0f3742347ce2
    annotations:
        argocd.argoproj.io/sync-options: PruneLast=true
        argocd.argoproj.io/sync-wave: "-10"
        kuberploy.io/git-binding-id: aba67474-620f-4f28-8b54-238fa52f56b3
        kuberploy.io/renderer-image: ghcr.io/kuberploy/kuberploy-worker@sha256:fe467d918748021ef34b06c789855121d6598a7ccf8aeec944c510e910ff4ad9
        kuberploy.io/runtime-chart-digest: sha256:8390ca6c5254d3463fa30d28a32caa4d0ab78d289478d8eecb7fe6d37c967a8f
spec:
    sourceRepos:
        - '*'
    destinations:
        - namespace: kp-rc405-qualification-dev
          server: https://kubernetes.default.svc
    clusterResourceWhitelist: []
    namespaceResourceWhitelist:
        - group: '*'
          kind: '*'
    orphanedResources:
        warn: true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
    name: kp-e-17edcd5ef15942368e1270d484d3c961
    namespace: argocd
    labels:
        app.kubernetes.io/managed-by: kuberploy
        kuberploy.io/environment-id: 17edcd5e-f159-4236-8e12-70d484d3c961
        kuberploy.io/project-id: 92c030ae-83a7-4308-87cc-0f3742347ce2
    annotations:
        argocd.argoproj.io/sync-wave: "0"
        kuberploy.io/git-binding-id: aba67474-620f-4f28-8b54-238fa52f56b3
        kuberploy.io/runtime-chart-digest: sha256:8390ca6c5254d3463fa30d28a32caa4d0ab78d289478d8eecb7fe6d37c967a8f
spec:
    goTemplate: true
    goTemplateOptions:
        - missingkey=error
    generators:
        - list:
            elements:
                - deploymentId: 90fdc9bc-7cec-4be4-96f9-e9c7780b33ce
                  applicationId: 5fdc0ef4-8931-4f4a-8d31-fa006b1c3948
                  applicationName: kp-d-90fdc9bc7cec4be496f9e9c7780b33ce
                  applicationPath: tenants/92c030ae-83a7-4308-87cc-0f3742347ce2/environments/17edcd5e-f159-4236-8e12-70d484d3c961/apps/5fdc0ef4-8931-4f4a-8d31-fa006b1c3948/app.yaml
                  valuesRevision: 6b74cc1ab1ca6855872c657cd51aff8fee3b8afa
    template:
        metadata:
            name: '{{.applicationName}}'
            namespace: argocd
            labels:
                app.kubernetes.io/managed-by: kuberploy
                kuberploy.io/application-id: '{{.applicationId}}'
                kuberploy.io/deployment-id: '{{.deploymentId}}'
                kuberploy.io/environment-id: 17edcd5e-f159-4236-8e12-70d484d3c961
                kuberploy.io/project-id: 92c030ae-83a7-4308-87cc-0f3742347ce2
                kuberploy.io/service: '{{.applicationId}}'
            annotations:
                kuberploy.io/git-binding-id: aba67474-620f-4f28-8b54-238fa52f56b3
                kuberploy.io/renderer-image: ghcr.io/kuberploy/kuberploy-worker@sha256:fe467d918748021ef34b06c789855121d6598a7ccf8aeec944c510e910ff4ad9
                kuberploy.io/runtime-chart-digest: sha256:8390ca6c5254d3463fa30d28a32caa4d0ab78d289478d8eecb7fe6d37c967a8f
                kuberploy.io/runtime-chart-version: 0.1.0-rc.405
        spec:
            project: kp-rc405-qualification-dev
            sources:
                - repoURL: oci://ghcr.io/kuberploy/charts/kuberploy-runtime
                  path: .
                  targetRevision: sha256:8390ca6c5254d3463fa30d28a32caa4d0ab78d289478d8eecb7fe6d37c967a8f
                  helm:
                    valueFiles:
                        - $values/tenants/92c030ae-83a7-4308-87cc-0f3742347ce2/variables.yaml
                        - $values/tenants/92c030ae-83a7-4308-87cc-0f3742347ce2/environments/17edcd5e-f159-4236-8e12-70d484d3c961/variables.yaml
                        - $values/{{.applicationPath}}
                    ignoreMissingValueFiles: true
                    parameters:
                        - name: kuberployExpectedIdentity.projectId
                          value: 92c030ae-83a7-4308-87cc-0f3742347ce2
                          forceString: true
                        - name: kuberployExpectedIdentity.environmentId
                          value: 17edcd5e-f159-4236-8e12-70d484d3c961
                          forceString: true
                        - name: kuberployExpectedIdentity.applicationId
                          value: '{{.applicationId}}'
                          forceString: true
                - repoURL: https://github.com/kuberploy/kuberploy-gitops-test.git
                  targetRevision: '{{.valuesRevision}}'
                  ref: values
            destination:
                namespace: kp-rc405-qualification-dev
                server: https://kubernetes.default.svc
            syncPolicy:
                automated:
                    allowEmpty: false
                    prune: true
                    selfHeal: true
                syncOptions:
                    - CreateNamespace=false
                    - ServerSideApply=true
