apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: kp-rc405-qualification-prod
    namespace: argocd
    labels:
        app.kubernetes.io/managed-by: kuberploy
        kuberploy.io/environment-id: 33b57103-c096-4142-bbb7-fd04172b2245
        kuberploy.io/project-id: 0cb45bb7-0a1c-4415-aea1-35676429cd18
    annotations:
        argocd.argoproj.io/sync-options: PruneLast=true
        argocd.argoproj.io/sync-wave: "-10"
        kuberploy.io/git-binding-id: 3feba0b3-4bff-4206-816c-225416729e1f
        kuberploy.io/renderer-image: ghcr.io/kuberploy/kuberploy-worker@sha256:fe467d918748021ef34b06c789855121d6598a7ccf8aeec944c510e910ff4ad9
        kuberploy.io/runtime-chart-digest: sha256:8390ca6c5254d3463fa30d28a32caa4d0ab78d289478d8eecb7fe6d37c967a8f
spec:
    sourceRepos:
        - '*'
    destinations:
        - namespace: kp-rc405-qualification-prod
          server: https://kubernetes.default.svc
    clusterResourceWhitelist: []
    namespaceResourceWhitelist:
        - group: '*'
          kind: '*'
    orphanedResources:
        warn: true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
    name: kp-e-33b57103c0964142bbb7fd04172b2245
    namespace: argocd
    labels:
        app.kubernetes.io/managed-by: kuberploy
        kuberploy.io/environment-id: 33b57103-c096-4142-bbb7-fd04172b2245
        kuberploy.io/project-id: 0cb45bb7-0a1c-4415-aea1-35676429cd18
    annotations:
        argocd.argoproj.io/sync-wave: "0"
        kuberploy.io/git-binding-id: 3feba0b3-4bff-4206-816c-225416729e1f
        kuberploy.io/runtime-chart-digest: sha256:8390ca6c5254d3463fa30d28a32caa4d0ab78d289478d8eecb7fe6d37c967a8f
spec:
    goTemplate: true
    goTemplateOptions:
        - missingkey=error
    generators:
        - list:
            elements: []
    template:
        metadata:
            name: '{{.applicationName}}'
            namespace: argocd
            labels:
                app.kubernetes.io/managed-by: kuberploy
                kuberploy.io/application-id: '{{.applicationId}}'
                kuberploy.io/deployment-id: '{{.deploymentId}}'
                kuberploy.io/environment-id: 33b57103-c096-4142-bbb7-fd04172b2245
                kuberploy.io/project-id: 0cb45bb7-0a1c-4415-aea1-35676429cd18
                kuberploy.io/service: '{{.applicationId}}'
            annotations:
                kuberploy.io/git-binding-id: 3feba0b3-4bff-4206-816c-225416729e1f
                kuberploy.io/renderer-image: ghcr.io/kuberploy/kuberploy-worker@sha256:fe467d918748021ef34b06c789855121d6598a7ccf8aeec944c510e910ff4ad9
                kuberploy.io/runtime-chart-digest: sha256:8390ca6c5254d3463fa30d28a32caa4d0ab78d289478d8eecb7fe6d37c967a8f
                kuberploy.io/runtime-chart-version: 0.1.0-rc.405
        spec:
            project: kp-rc405-qualification-prod
            sources:
                - repoURL: oci://ghcr.io/kuberploy/charts/kuberploy-runtime
                  path: .
                  targetRevision: sha256:8390ca6c5254d3463fa30d28a32caa4d0ab78d289478d8eecb7fe6d37c967a8f
                  helm:
                    valueFiles:
                        - $values/tenants/0cb45bb7-0a1c-4415-aea1-35676429cd18/variables.yaml
                        - $values/tenants/0cb45bb7-0a1c-4415-aea1-35676429cd18/environments/33b57103-c096-4142-bbb7-fd04172b2245/variables.yaml
                        - $values/{{.applicationPath}}
                    ignoreMissingValueFiles: true
                    parameters:
                        - name: kuberployExpectedIdentity.projectId
                          value: 0cb45bb7-0a1c-4415-aea1-35676429cd18
                          forceString: true
                        - name: kuberployExpectedIdentity.environmentId
                          value: 33b57103-c096-4142-bbb7-fd04172b2245
                          forceString: true
                        - name: kuberployExpectedIdentity.applicationId
                          value: '{{.applicationId}}'
                          forceString: true
                - repoURL: https://github.com/kuberploy/kuberploy-gitops-test.git
                  targetRevision: '{{.valuesRevision}}'
                  ref: values
            destination:
                namespace: kp-rc405-qualification-prod
                server: https://kubernetes.default.svc
            syncPolicy:
                automated:
                    allowEmpty: false
                    prune: true
                    selfHeal: true
                syncOptions:
                    - CreateNamespace=false
                    - ServerSideApply=true
