apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: kp-rc412-qualification-development
    namespace: argocd
    labels:
        app.kubernetes.io/managed-by: kuberploy
        kuberploy.io/environment-id: 3d799c88-0aba-4347-80bf-b4b3ea39a769
        kuberploy.io/project-id: a17354c9-e3d0-4a52-a5e5-edd69d1ccb9e
    annotations:
        argocd.argoproj.io/sync-options: PruneLast=true
        argocd.argoproj.io/sync-wave: "-10"
        kuberploy.io/git-binding-id: fd78a993-472b-4798-a731-ca41638dbe74
        kuberploy.io/renderer-image: ghcr.io/kuberploy/kuberploy-worker@sha256:1199bd7e53f0dcfebfd6afd4593e179dea75073874ad220379a8e651fed760d7
        kuberploy.io/runtime-chart-digest: sha256:b66629ddd11ceacf6218caa2b51cf2632f56adb0e8c326a3dca5c19a67d2522c
spec:
    sourceRepos:
        - '*'
    destinations:
        - namespace: kp-rc412-qualification-development
          server: https://kubernetes.default.svc
    clusterResourceWhitelist: []
    namespaceResourceWhitelist:
        - group: '*'
          kind: '*'
    orphanedResources:
        warn: true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
    name: kp-e-3d799c880aba434780bfb4b3ea39a769
    namespace: argocd
    labels:
        app.kubernetes.io/managed-by: kuberploy
        kuberploy.io/environment-id: 3d799c88-0aba-4347-80bf-b4b3ea39a769
        kuberploy.io/project-id: a17354c9-e3d0-4a52-a5e5-edd69d1ccb9e
    annotations:
        argocd.argoproj.io/sync-wave: "0"
        kuberploy.io/git-binding-id: fd78a993-472b-4798-a731-ca41638dbe74
        kuberploy.io/runtime-chart-digest: sha256:b66629ddd11ceacf6218caa2b51cf2632f56adb0e8c326a3dca5c19a67d2522c
spec:
    goTemplate: true
    goTemplateOptions:
        - missingkey=error
    generators:
        - list:
            elements:
                - deploymentId: 03041a7c-918d-4a67-ab0f-c5d63be92f0b
                  applicationId: 70e71757-7b4b-445a-9b46-2b7ca2e5b24c
                  applicationName: kp-d-03041a7c918d4a67ab0fc5d63be92f0b
                  applicationPath: tenants/a17354c9-e3d0-4a52-a5e5-edd69d1ccb9e/environments/3d799c88-0aba-4347-80bf-b4b3ea39a769/apps/70e71757-7b4b-445a-9b46-2b7ca2e5b24c/app.yaml
                  valuesRevision: 6372db0338508a311470d18670e14374e70fbff6
    template:
        metadata:
            name: '{{.applicationName}}'
            namespace: argocd
            labels:
                app.kubernetes.io/managed-by: kuberploy
                kuberploy.io/application-id: '{{.applicationId}}'
                kuberploy.io/deployment-id: '{{.deploymentId}}'
                kuberploy.io/environment-id: 3d799c88-0aba-4347-80bf-b4b3ea39a769
                kuberploy.io/project-id: a17354c9-e3d0-4a52-a5e5-edd69d1ccb9e
                kuberploy.io/service: '{{.applicationId}}'
            annotations:
                kuberploy.io/git-binding-id: fd78a993-472b-4798-a731-ca41638dbe74
                kuberploy.io/renderer-image: ghcr.io/kuberploy/kuberploy-worker@sha256:1199bd7e53f0dcfebfd6afd4593e179dea75073874ad220379a8e651fed760d7
                kuberploy.io/runtime-chart-digest: sha256:b66629ddd11ceacf6218caa2b51cf2632f56adb0e8c326a3dca5c19a67d2522c
                kuberploy.io/runtime-chart-version: 0.1.0-rc.412
        spec:
            project: kp-rc412-qualification-development
            sources:
                - repoURL: oci://ghcr.io/kuberploy/charts/kuberploy-runtime
                  path: .
                  targetRevision: sha256:b66629ddd11ceacf6218caa2b51cf2632f56adb0e8c326a3dca5c19a67d2522c
                  helm:
                    valueFiles:
                        - $values/tenants/a17354c9-e3d0-4a52-a5e5-edd69d1ccb9e/variables.yaml
                        - $values/tenants/a17354c9-e3d0-4a52-a5e5-edd69d1ccb9e/environments/3d799c88-0aba-4347-80bf-b4b3ea39a769/variables.yaml
                        - $values/{{.applicationPath}}
                    ignoreMissingValueFiles: true
                    parameters:
                        - name: kuberployExpectedIdentity.projectId
                          value: a17354c9-e3d0-4a52-a5e5-edd69d1ccb9e
                          forceString: true
                        - name: kuberployExpectedIdentity.environmentId
                          value: 3d799c88-0aba-4347-80bf-b4b3ea39a769
                          forceString: true
                        - name: kuberployExpectedIdentity.applicationId
                          value: '{{.applicationId}}'
                          forceString: true
                - repoURL: https://github.com/kuberploy/kuberploy-gitops-test.git
                  targetRevision: '{{.valuesRevision}}'
                  ref: values
            destination:
                namespace: kp-rc412-qualification-development
                server: https://kubernetes.default.svc
            syncPolicy:
                automated:
                    allowEmpty: false
                    prune: true
                    selfHeal: true
                syncOptions:
                    - CreateNamespace=false
                    - ServerSideApply=true
