apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: kp-rc403-qualification-dev
    namespace: argocd
    labels:
        app.kubernetes.io/managed-by: kuberploy
        kuberploy.io/environment-id: 451440df-e985-4478-a3fd-18592bcd49b8
        kuberploy.io/project-id: 18290bc7-6ebd-4f92-b306-afe45361532c
    annotations:
        argocd.argoproj.io/sync-options: PruneLast=true
        argocd.argoproj.io/sync-wave: "-10"
        kuberploy.io/git-binding-id: 145026d6-71b0-4de5-a9ba-cd7411367078
        kuberploy.io/renderer-image: ghcr.io/kuberploy/kuberploy-worker@sha256:70ddcedafb56e34163c52dfa3571e77fc2d8d8045d3cc9882621c68534d945b4
        kuberploy.io/runtime-chart-digest: sha256:1ea30b223a5f061329d7b9eb03ea229a0b89167472d3764dca98eb107cea43a1
spec:
    sourceRepos:
        - '*'
    destinations:
        - namespace: kp-rc403-qualification-dev
          server: https://kubernetes.default.svc
    clusterResourceWhitelist: []
    namespaceResourceWhitelist:
        - group: '*'
          kind: '*'
    orphanedResources:
        warn: true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
    name: kp-e-451440dfe9854478a3fd18592bcd49b8
    namespace: argocd
    labels:
        app.kubernetes.io/managed-by: kuberploy
        kuberploy.io/environment-id: 451440df-e985-4478-a3fd-18592bcd49b8
        kuberploy.io/project-id: 18290bc7-6ebd-4f92-b306-afe45361532c
    annotations:
        argocd.argoproj.io/sync-wave: "0"
        kuberploy.io/git-binding-id: 145026d6-71b0-4de5-a9ba-cd7411367078
        kuberploy.io/runtime-chart-digest: sha256:1ea30b223a5f061329d7b9eb03ea229a0b89167472d3764dca98eb107cea43a1
spec:
    goTemplate: true
    goTemplateOptions:
        - missingkey=error
    generators:
        - list:
            elements:
                - deploymentId: c52a1278-3eb6-465b-899a-c731924350f6
                  applicationId: 11135d2e-773b-4c50-beda-235fea4400ac
                  applicationName: kp-d-c52a12783eb6465b899ac731924350f6
                  applicationPath: tenants/18290bc7-6ebd-4f92-b306-afe45361532c/environments/451440df-e985-4478-a3fd-18592bcd49b8/apps/11135d2e-773b-4c50-beda-235fea4400ac/app.yaml
                  valuesRevision: c84f4c34f943a782f2479f531badf7911e7a7d8f
    template:
        metadata:
            name: '{{.applicationName}}'
            namespace: argocd
            labels:
                app.kubernetes.io/managed-by: kuberploy
                kuberploy.io/application-id: '{{.applicationId}}'
                kuberploy.io/deployment-id: '{{.deploymentId}}'
                kuberploy.io/environment-id: 451440df-e985-4478-a3fd-18592bcd49b8
                kuberploy.io/project-id: 18290bc7-6ebd-4f92-b306-afe45361532c
                kuberploy.io/service: '{{.applicationId}}'
            annotations:
                kuberploy.io/git-binding-id: 145026d6-71b0-4de5-a9ba-cd7411367078
                kuberploy.io/renderer-image: ghcr.io/kuberploy/kuberploy-worker@sha256:70ddcedafb56e34163c52dfa3571e77fc2d8d8045d3cc9882621c68534d945b4
                kuberploy.io/runtime-chart-digest: sha256:1ea30b223a5f061329d7b9eb03ea229a0b89167472d3764dca98eb107cea43a1
                kuberploy.io/runtime-chart-version: 0.1.0-rc.404
        spec:
            project: kp-rc403-qualification-dev
            sources:
                - repoURL: oci://ghcr.io/kuberploy/charts/kuberploy-runtime
                  path: .
                  targetRevision: sha256:1ea30b223a5f061329d7b9eb03ea229a0b89167472d3764dca98eb107cea43a1
                  helm:
                    valueFiles:
                        - $values/tenants/18290bc7-6ebd-4f92-b306-afe45361532c/variables.yaml
                        - $values/tenants/18290bc7-6ebd-4f92-b306-afe45361532c/environments/451440df-e985-4478-a3fd-18592bcd49b8/variables.yaml
                        - $values/{{.applicationPath}}
                    ignoreMissingValueFiles: true
                    parameters:
                        - name: kuberployExpectedIdentity.projectId
                          value: 18290bc7-6ebd-4f92-b306-afe45361532c
                          forceString: true
                        - name: kuberployExpectedIdentity.environmentId
                          value: 451440df-e985-4478-a3fd-18592bcd49b8
                          forceString: true
                        - name: kuberployExpectedIdentity.applicationId
                          value: '{{.applicationId}}'
                          forceString: true
                - repoURL: https://github.com/kuberploy/kuberploy-gitops-test.git
                  targetRevision: '{{.valuesRevision}}'
                  ref: values
            destination:
                namespace: kp-rc403-qualification-dev
                server: https://kubernetes.default.svc
            syncPolicy:
                automated:
                    allowEmpty: false
                    prune: true
                    selfHeal: true
                syncOptions:
                    - CreateNamespace=false
                    - ServerSideApply=true
