apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: kp-rc405-qualification-dev
    namespace: argocd
    labels:
        app.kubernetes.io/managed-by: kuberploy
        kuberploy.io/environment-id: 4e4e15b2-719d-4e92-a18f-598f86162373
        kuberploy.io/project-id: b4cb68a3-0ce7-40e4-96a4-61cf471a6989
    annotations:
        argocd.argoproj.io/sync-options: PruneLast=true
        argocd.argoproj.io/sync-wave: "-10"
        kuberploy.io/git-binding-id: e509064b-0b66-4f8b-8e27-5bf83a0f0042
        kuberploy.io/renderer-image: ghcr.io/kuberploy/kuberploy-worker@sha256:fe467d918748021ef34b06c789855121d6598a7ccf8aeec944c510e910ff4ad9
        kuberploy.io/runtime-chart-digest: sha256:8390ca6c5254d3463fa30d28a32caa4d0ab78d289478d8eecb7fe6d37c967a8f
spec:
    sourceRepos:
        - '*'
    destinations:
        - namespace: kp-rc405-qualification-dev
          server: https://kubernetes.default.svc
    clusterResourceWhitelist: []
    namespaceResourceWhitelist:
        - group: '*'
          kind: '*'
    orphanedResources:
        warn: true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
    name: kp-e-4e4e15b2719d4e92a18f598f86162373
    namespace: argocd
    labels:
        app.kubernetes.io/managed-by: kuberploy
        kuberploy.io/environment-id: 4e4e15b2-719d-4e92-a18f-598f86162373
        kuberploy.io/project-id: b4cb68a3-0ce7-40e4-96a4-61cf471a6989
    annotations:
        argocd.argoproj.io/sync-wave: "0"
        kuberploy.io/git-binding-id: e509064b-0b66-4f8b-8e27-5bf83a0f0042
        kuberploy.io/runtime-chart-digest: sha256:8390ca6c5254d3463fa30d28a32caa4d0ab78d289478d8eecb7fe6d37c967a8f
spec:
    goTemplate: true
    goTemplateOptions:
        - missingkey=error
    generators:
        - list:
            elements:
                - deploymentId: d94c0f58-7d55-4709-81ac-ed92e259bd35
                  applicationId: 84bdcc5f-f2ab-40c5-a561-203ec3c4bfed
                  applicationName: kp-d-d94c0f587d55470981aced92e259bd35
                  applicationPath: tenants/b4cb68a3-0ce7-40e4-96a4-61cf471a6989/environments/4e4e15b2-719d-4e92-a18f-598f86162373/apps/84bdcc5f-f2ab-40c5-a561-203ec3c4bfed/app.yaml
                  valuesRevision: 87779bf367c4b79d3559c61a3e82b9be3ded02a1
    template:
        metadata:
            name: '{{.applicationName}}'
            namespace: argocd
            labels:
                app.kubernetes.io/managed-by: kuberploy
                kuberploy.io/application-id: '{{.applicationId}}'
                kuberploy.io/deployment-id: '{{.deploymentId}}'
                kuberploy.io/environment-id: 4e4e15b2-719d-4e92-a18f-598f86162373
                kuberploy.io/project-id: b4cb68a3-0ce7-40e4-96a4-61cf471a6989
                kuberploy.io/service: '{{.applicationId}}'
            annotations:
                kuberploy.io/git-binding-id: e509064b-0b66-4f8b-8e27-5bf83a0f0042
                kuberploy.io/renderer-image: ghcr.io/kuberploy/kuberploy-worker@sha256:fe467d918748021ef34b06c789855121d6598a7ccf8aeec944c510e910ff4ad9
                kuberploy.io/runtime-chart-digest: sha256:8390ca6c5254d3463fa30d28a32caa4d0ab78d289478d8eecb7fe6d37c967a8f
                kuberploy.io/runtime-chart-version: 0.1.0-rc.405
        spec:
            project: kp-rc405-qualification-dev
            sources:
                - repoURL: oci://ghcr.io/kuberploy/charts/kuberploy-runtime
                  path: .
                  targetRevision: sha256:8390ca6c5254d3463fa30d28a32caa4d0ab78d289478d8eecb7fe6d37c967a8f
                  helm:
                    valueFiles:
                        - $values/tenants/b4cb68a3-0ce7-40e4-96a4-61cf471a6989/variables.yaml
                        - $values/tenants/b4cb68a3-0ce7-40e4-96a4-61cf471a6989/environments/4e4e15b2-719d-4e92-a18f-598f86162373/variables.yaml
                        - $values/{{.applicationPath}}
                    ignoreMissingValueFiles: true
                    parameters:
                        - name: kuberployExpectedIdentity.projectId
                          value: b4cb68a3-0ce7-40e4-96a4-61cf471a6989
                          forceString: true
                        - name: kuberployExpectedIdentity.environmentId
                          value: 4e4e15b2-719d-4e92-a18f-598f86162373
                          forceString: true
                        - name: kuberployExpectedIdentity.applicationId
                          value: '{{.applicationId}}'
                          forceString: true
                - repoURL: https://github.com/kuberploy/kuberploy-gitops-test.git
                  targetRevision: '{{.valuesRevision}}'
                  ref: values
            destination:
                namespace: kp-rc405-qualification-dev
                server: https://kubernetes.default.svc
            syncPolicy:
                automated:
                    allowEmpty: false
                    prune: true
                    selfHeal: true
                syncOptions:
                    - CreateNamespace=false
                    - ServerSideApply=true
