apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: kp-rc386-clone-source-65e7fa40-development
    namespace: argocd
    labels:
        app.kubernetes.io/managed-by: kuberploy
        kuberploy.io/environment-id: 51fc57b4-c825-4e7c-9f49-7fef2efc83d0
        kuberploy.io/project-id: 6b1da853-0bf9-436a-b9e7-4744f7a3586e
    annotations:
        argocd.argoproj.io/sync-options: PruneLast=true
        argocd.argoproj.io/sync-wave: "-10"
        kuberploy.io/git-binding-id: cc5c8228-b6fd-4e31-b641-6dd06876d382
        kuberploy.io/renderer-image: ghcr.io/kuberploy/kuberploy-worker@sha256:e03811d40ddb4c9d8bdbc4c9a7707263a13669f50b0afcb025b2310c94bc3339
        kuberploy.io/runtime-chart-digest: sha256:78228c10ba28fbaaea5aaeacfd4aca4e3e6b584129e165c87252c6a90cecacaf
spec:
    sourceRepos:
        - '*'
    destinations:
        - namespace: kp-rc386-clone-source-65e7fa40-development
          server: https://kubernetes.default.svc
    clusterResourceWhitelist: []
    namespaceResourceWhitelist:
        - group: '*'
          kind: '*'
    orphanedResources:
        warn: true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
    name: kp-e-51fc57b4c8254e7c9f497fef2efc83d0
    namespace: argocd
    labels:
        app.kubernetes.io/managed-by: kuberploy
        kuberploy.io/environment-id: 51fc57b4-c825-4e7c-9f49-7fef2efc83d0
        kuberploy.io/project-id: 6b1da853-0bf9-436a-b9e7-4744f7a3586e
    annotations:
        argocd.argoproj.io/sync-wave: "0"
        kuberploy.io/git-binding-id: cc5c8228-b6fd-4e31-b641-6dd06876d382
        kuberploy.io/runtime-chart-digest: sha256:78228c10ba28fbaaea5aaeacfd4aca4e3e6b584129e165c87252c6a90cecacaf
spec:
    goTemplate: true
    goTemplateOptions:
        - missingkey=error
    generators:
        - list:
            elements:
                - deploymentId: 2f3a9584-884a-4799-879a-1f710b5297b5
                  applicationId: 6da05d06-69ed-48cc-8e58-15a1cd2e2c01
                  applicationName: kp-d-2f3a9584884a4799879a1f710b5297b5
                  applicationPath: tenants/6b1da853-0bf9-436a-b9e7-4744f7a3586e/environments/51fc57b4-c825-4e7c-9f49-7fef2efc83d0/apps/6da05d06-69ed-48cc-8e58-15a1cd2e2c01/app.yaml
                  valuesRevision: 712635a1d52e9c97fcdb1f633df8b18b0196f7fa
    template:
        metadata:
            name: '{{.applicationName}}'
            namespace: argocd
            labels:
                app.kubernetes.io/managed-by: kuberploy
                kuberploy.io/application-id: '{{.applicationId}}'
                kuberploy.io/deployment-id: '{{.deploymentId}}'
                kuberploy.io/environment-id: 51fc57b4-c825-4e7c-9f49-7fef2efc83d0
                kuberploy.io/project-id: 6b1da853-0bf9-436a-b9e7-4744f7a3586e
                kuberploy.io/service: '{{.applicationId}}'
            annotations:
                kuberploy.io/git-binding-id: cc5c8228-b6fd-4e31-b641-6dd06876d382
                kuberploy.io/renderer-image: ghcr.io/kuberploy/kuberploy-worker@sha256:e03811d40ddb4c9d8bdbc4c9a7707263a13669f50b0afcb025b2310c94bc3339
                kuberploy.io/runtime-chart-digest: sha256:78228c10ba28fbaaea5aaeacfd4aca4e3e6b584129e165c87252c6a90cecacaf
                kuberploy.io/runtime-chart-version: 0.1.0-rc.386
        spec:
            project: kp-rc386-clone-source-65e7fa40-development
            sources:
                - repoURL: oci://ghcr.io/kuberploy/charts/kuberploy-runtime
                  path: .
                  targetRevision: sha256:78228c10ba28fbaaea5aaeacfd4aca4e3e6b584129e165c87252c6a90cecacaf
                  helm:
                    valueFiles:
                        - $values/tenants/6b1da853-0bf9-436a-b9e7-4744f7a3586e/variables.yaml
                        - $values/tenants/6b1da853-0bf9-436a-b9e7-4744f7a3586e/environments/51fc57b4-c825-4e7c-9f49-7fef2efc83d0/variables.yaml
                        - $values/{{.applicationPath}}
                    ignoreMissingValueFiles: true
                    parameters:
                        - name: kuberployExpectedIdentity.projectId
                          value: 6b1da853-0bf9-436a-b9e7-4744f7a3586e
                          forceString: true
                        - name: kuberployExpectedIdentity.environmentId
                          value: 51fc57b4-c825-4e7c-9f49-7fef2efc83d0
                          forceString: true
                        - name: kuberployExpectedIdentity.applicationId
                          value: '{{.applicationId}}'
                          forceString: true
                - repoURL: https://github.com/kuberploy/kuberploy-gitops-test.git
                  targetRevision: '{{.valuesRevision}}'
                  ref: values
            destination:
                namespace: kp-rc386-clone-source-65e7fa40-development
                server: https://kubernetes.default.svc
            syncPolicy:
                automated:
                    allowEmpty: false
                    prune: true
                    selfHeal: true
                syncOptions:
                    - CreateNamespace=false
                    - ServerSideApply=true
