apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: kp-rc405-qualification-prod
    namespace: argocd
    labels:
        app.kubernetes.io/managed-by: kuberploy
        kuberploy.io/environment-id: 6c9bf378-ccf1-4def-b04f-661530fe093a
        kuberploy.io/project-id: b4cb68a3-0ce7-40e4-96a4-61cf471a6989
    annotations:
        argocd.argoproj.io/sync-options: PruneLast=true
        argocd.argoproj.io/sync-wave: "-10"
        kuberploy.io/git-binding-id: 2bd499d7-0626-4824-8553-60f487fedbb1
        kuberploy.io/renderer-image: ghcr.io/kuberploy/kuberploy-worker@sha256:70ddcedafb56e34163c52dfa3571e77fc2d8d8045d3cc9882621c68534d945b4
        kuberploy.io/runtime-chart-digest: sha256:1ea30b223a5f061329d7b9eb03ea229a0b89167472d3764dca98eb107cea43a1
spec:
    sourceRepos:
        - '*'
    destinations:
        - namespace: kp-rc405-qualification-prod
          server: https://kubernetes.default.svc
    clusterResourceWhitelist: []
    namespaceResourceWhitelist:
        - group: '*'
          kind: '*'
    orphanedResources:
        warn: true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
    name: kp-e-6c9bf378ccf14defb04f661530fe093a
    namespace: argocd
    labels:
        app.kubernetes.io/managed-by: kuberploy
        kuberploy.io/environment-id: 6c9bf378-ccf1-4def-b04f-661530fe093a
        kuberploy.io/project-id: b4cb68a3-0ce7-40e4-96a4-61cf471a6989
    annotations:
        argocd.argoproj.io/sync-wave: "0"
        kuberploy.io/git-binding-id: 2bd499d7-0626-4824-8553-60f487fedbb1
        kuberploy.io/runtime-chart-digest: sha256:1ea30b223a5f061329d7b9eb03ea229a0b89167472d3764dca98eb107cea43a1
spec:
    goTemplate: true
    goTemplateOptions:
        - missingkey=error
    generators:
        - list:
            elements: []
    template:
        metadata:
            name: '{{.applicationName}}'
            namespace: argocd
            labels:
                app.kubernetes.io/managed-by: kuberploy
                kuberploy.io/application-id: '{{.applicationId}}'
                kuberploy.io/deployment-id: '{{.deploymentId}}'
                kuberploy.io/environment-id: 6c9bf378-ccf1-4def-b04f-661530fe093a
                kuberploy.io/project-id: b4cb68a3-0ce7-40e4-96a4-61cf471a6989
                kuberploy.io/service: '{{.applicationId}}'
            annotations:
                kuberploy.io/git-binding-id: 2bd499d7-0626-4824-8553-60f487fedbb1
                kuberploy.io/renderer-image: ghcr.io/kuberploy/kuberploy-worker@sha256:70ddcedafb56e34163c52dfa3571e77fc2d8d8045d3cc9882621c68534d945b4
                kuberploy.io/runtime-chart-digest: sha256:1ea30b223a5f061329d7b9eb03ea229a0b89167472d3764dca98eb107cea43a1
                kuberploy.io/runtime-chart-version: 0.1.0-rc.404
        spec:
            project: kp-rc405-qualification-prod
            sources:
                - repoURL: oci://ghcr.io/kuberploy/charts/kuberploy-runtime
                  path: .
                  targetRevision: sha256:1ea30b223a5f061329d7b9eb03ea229a0b89167472d3764dca98eb107cea43a1
                  helm:
                    valueFiles:
                        - $values/tenants/b4cb68a3-0ce7-40e4-96a4-61cf471a6989/variables.yaml
                        - $values/tenants/b4cb68a3-0ce7-40e4-96a4-61cf471a6989/environments/6c9bf378-ccf1-4def-b04f-661530fe093a/variables.yaml
                        - $values/{{.applicationPath}}
                    ignoreMissingValueFiles: true
                    parameters:
                        - name: kuberployExpectedIdentity.projectId
                          value: b4cb68a3-0ce7-40e4-96a4-61cf471a6989
                          forceString: true
                        - name: kuberployExpectedIdentity.environmentId
                          value: 6c9bf378-ccf1-4def-b04f-661530fe093a
                          forceString: true
                        - name: kuberployExpectedIdentity.applicationId
                          value: '{{.applicationId}}'
                          forceString: true
                - repoURL: https://github.com/kuberploy/kuberploy-gitops-test.git
                  targetRevision: '{{.valuesRevision}}'
                  ref: values
            destination:
                namespace: kp-rc405-qualification-prod
                server: https://kubernetes.default.svc
            syncPolicy:
                automated:
                    allowEmpty: false
                    prune: true
                    selfHeal: true
                syncOptions:
                    - CreateNamespace=false
                    - ServerSideApply=true
