apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: kp-rc376-platform-development
    namespace: argocd
    labels:
        app.kubernetes.io/managed-by: kuberploy
        kuberploy.io/environment-id: d2ce9611-44b3-41ff-a729-21d8df849084
        kuberploy.io/project-id: f2674f0a-afbc-40b4-9286-874de90efdd9
    annotations:
        argocd.argoproj.io/sync-options: PruneLast=true
        argocd.argoproj.io/sync-wave: "-10"
        kuberploy.io/git-binding-id: 52b2ab96-9e55-4a09-8448-a6210cc00095
        kuberploy.io/renderer-image: ghcr.io/kuberploy/kuberploy-worker@sha256:9cf8f4a470ce931a076cf3639bfa110265bc7304bba7816df25739444023e8a7
        kuberploy.io/runtime-chart-digest: sha256:fa0e871dc865015c0d2a58839582aa8dccc279720d2ffc97466e27febe2136d4
spec:
    sourceRepos:
        - '*'
    destinations:
        - namespace: kp-rc376-platform-development
          server: https://kubernetes.default.svc
    clusterResourceWhitelist: []
    namespaceResourceWhitelist:
        - group: '*'
          kind: '*'
    orphanedResources:
        warn: true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
    name: kp-e-d2ce961144b341ffa72921d8df849084
    namespace: argocd
    labels:
        app.kubernetes.io/managed-by: kuberploy
        kuberploy.io/environment-id: d2ce9611-44b3-41ff-a729-21d8df849084
        kuberploy.io/project-id: f2674f0a-afbc-40b4-9286-874de90efdd9
    annotations:
        argocd.argoproj.io/sync-wave: "0"
        kuberploy.io/git-binding-id: 52b2ab96-9e55-4a09-8448-a6210cc00095
        kuberploy.io/runtime-chart-digest: sha256:fa0e871dc865015c0d2a58839582aa8dccc279720d2ffc97466e27febe2136d4
spec:
    goTemplate: true
    goTemplateOptions:
        - missingkey=error
    generators:
        - list:
            elements:
                - deploymentId: 1604e4d4-ee09-46cb-b8dd-5e7453b274f8
                  applicationId: f38a5d7d-4673-4e72-9199-2d62813179c9
                  applicationName: kp-d-1604e4d4ee0946cbb8dd5e7453b274f8
                  applicationPath: tenants/f2674f0a-afbc-40b4-9286-874de90efdd9/environments/d2ce9611-44b3-41ff-a729-21d8df849084/apps/f38a5d7d-4673-4e72-9199-2d62813179c9/app.yaml
                  valuesRevision: 953c98f9f830b7d397c60ba9d1d68a70c39eaf32
    template:
        metadata:
            name: '{{.applicationName}}'
            namespace: argocd
            labels:
                app.kubernetes.io/managed-by: kuberploy
                kuberploy.io/application-id: '{{.applicationId}}'
                kuberploy.io/deployment-id: '{{.deploymentId}}'
                kuberploy.io/environment-id: d2ce9611-44b3-41ff-a729-21d8df849084
                kuberploy.io/project-id: f2674f0a-afbc-40b4-9286-874de90efdd9
                kuberploy.io/service: '{{.applicationId}}'
            annotations:
                kuberploy.io/git-binding-id: 52b2ab96-9e55-4a09-8448-a6210cc00095
                kuberploy.io/renderer-image: ghcr.io/kuberploy/kuberploy-worker@sha256:9cf8f4a470ce931a076cf3639bfa110265bc7304bba7816df25739444023e8a7
                kuberploy.io/runtime-chart-digest: sha256:fa0e871dc865015c0d2a58839582aa8dccc279720d2ffc97466e27febe2136d4
                kuberploy.io/runtime-chart-version: 0.1.0-rc.384
        spec:
            project: kp-rc376-platform-development
            sources:
                - repoURL: oci://ghcr.io/kuberploy/charts/kuberploy-runtime
                  path: .
                  targetRevision: sha256:fa0e871dc865015c0d2a58839582aa8dccc279720d2ffc97466e27febe2136d4
                  helm:
                    valueFiles:
                        - $values/tenants/f2674f0a-afbc-40b4-9286-874de90efdd9/variables.yaml
                        - $values/tenants/f2674f0a-afbc-40b4-9286-874de90efdd9/environments/d2ce9611-44b3-41ff-a729-21d8df849084/variables.yaml
                        - $values/{{.applicationPath}}
                    ignoreMissingValueFiles: true
                    parameters:
                        - name: kuberployExpectedIdentity.projectId
                          value: f2674f0a-afbc-40b4-9286-874de90efdd9
                          forceString: true
                        - name: kuberployExpectedIdentity.environmentId
                          value: d2ce9611-44b3-41ff-a729-21d8df849084
                          forceString: true
                        - name: kuberployExpectedIdentity.applicationId
                          value: '{{.applicationId}}'
                          forceString: true
                - repoURL: https://github.com/kuberploy/kuberploy-gitops-test.git
                  targetRevision: '{{.valuesRevision}}'
                  ref: values
            destination:
                namespace: kp-rc376-platform-development
                server: https://kubernetes.default.svc
            syncPolicy:
                automated:
                    allowEmpty: false
                    prune: true
                    selfHeal: true
                syncOptions:
                    - CreateNamespace=false
                    - ServerSideApply=true
