apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: kp-rc376-platform-development
    namespace: argocd
    labels:
        app.kubernetes.io/managed-by: kuberploy
        kuberploy.io/environment-id: d2ce9611-44b3-41ff-a729-21d8df849084
        kuberploy.io/project-id: f2674f0a-afbc-40b4-9286-874de90efdd9
    annotations:
        argocd.argoproj.io/sync-options: PruneLast=true
        argocd.argoproj.io/sync-wave: "-10"
        kuberploy.io/git-binding-id: 52b2ab96-9e55-4a09-8448-a6210cc00095
        kuberploy.io/renderer-image: ghcr.io/kuberploy/kuberploy-worker@sha256:8dd1441052612914056a28924550c1d1c67341714334ca384c02ac62e4988da5
        kuberploy.io/runtime-chart-digest: sha256:55758c39a82920855b152d9e173af54219a0d37565c28fe9d2c2885e3cff79d7
spec:
    sourceRepos:
        - '*'
    destinations:
        - namespace: kp-rc376-platform-development
          server: https://kubernetes.default.svc
    clusterResourceWhitelist: []
    namespaceResourceWhitelist:
        - group: '*'
          kind: '*'
    orphanedResources:
        warn: true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
    name: kp-e-d2ce961144b341ffa72921d8df849084
    namespace: argocd
    labels:
        app.kubernetes.io/managed-by: kuberploy
        kuberploy.io/environment-id: d2ce9611-44b3-41ff-a729-21d8df849084
        kuberploy.io/project-id: f2674f0a-afbc-40b4-9286-874de90efdd9
    annotations:
        argocd.argoproj.io/sync-wave: "0"
        kuberploy.io/git-binding-id: 52b2ab96-9e55-4a09-8448-a6210cc00095
        kuberploy.io/runtime-chart-digest: sha256:55758c39a82920855b152d9e173af54219a0d37565c28fe9d2c2885e3cff79d7
spec:
    goTemplate: true
    goTemplateOptions:
        - missingkey=error
    generators:
        - list:
            elements: []
    template:
        metadata:
            name: '{{.applicationName}}'
            namespace: argocd
            labels:
                app.kubernetes.io/managed-by: kuberploy
                kuberploy.io/application-id: '{{.applicationId}}'
                kuberploy.io/deployment-id: '{{.deploymentId}}'
                kuberploy.io/environment-id: d2ce9611-44b3-41ff-a729-21d8df849084
                kuberploy.io/project-id: f2674f0a-afbc-40b4-9286-874de90efdd9
                kuberploy.io/service: '{{.applicationId}}'
            annotations:
                kuberploy.io/git-binding-id: 52b2ab96-9e55-4a09-8448-a6210cc00095
                kuberploy.io/renderer-image: ghcr.io/kuberploy/kuberploy-worker@sha256:8dd1441052612914056a28924550c1d1c67341714334ca384c02ac62e4988da5
                kuberploy.io/runtime-chart-digest: sha256:55758c39a82920855b152d9e173af54219a0d37565c28fe9d2c2885e3cff79d7
                kuberploy.io/runtime-chart-version: 0.1.0-rc.376
        spec:
            project: kp-rc376-platform-development
            sources:
                - repoURL: oci://ghcr.io/kuberploy/charts/kuberploy-runtime
                  path: .
                  targetRevision: sha256:55758c39a82920855b152d9e173af54219a0d37565c28fe9d2c2885e3cff79d7
                  helm:
                    valueFiles:
                        - $values/tenants/f2674f0a-afbc-40b4-9286-874de90efdd9/variables.yaml
                        - $values/tenants/f2674f0a-afbc-40b4-9286-874de90efdd9/environments/d2ce9611-44b3-41ff-a729-21d8df849084/variables.yaml
                        - $values/{{.applicationPath}}
                    ignoreMissingValueFiles: true
                    parameters:
                        - name: kuberployExpectedIdentity.projectId
                          value: f2674f0a-afbc-40b4-9286-874de90efdd9
                          forceString: true
                        - name: kuberployExpectedIdentity.environmentId
                          value: d2ce9611-44b3-41ff-a729-21d8df849084
                          forceString: true
                        - name: kuberployExpectedIdentity.applicationId
                          value: '{{.applicationId}}'
                          forceString: true
                - repoURL: https://github.com/kuberploy/kuberploy-gitops-test.git
                  targetRevision: '{{.valuesRevision}}'
                  ref: values
            destination:
                namespace: kp-rc376-platform-development
                server: https://kubernetes.default.svc
            syncPolicy:
                automated:
                    allowEmpty: false
                    prune: true
                    selfHeal: true
                syncOptions:
                    - CreateNamespace=false
                    - ServerSideApply=true
