apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: kp-rc366-qualification-development
    namespace: argocd
    labels:
        app.kubernetes.io/managed-by: kuberploy
        kuberploy.io/environment-id: d7ba656e-bad2-4f16-8251-b729dee55894
        kuberploy.io/project-id: b87693b1-4925-4049-9814-cf768bac0dd3
    annotations:
        argocd.argoproj.io/sync-options: PruneLast=true
        argocd.argoproj.io/sync-wave: "-10"
        kuberploy.io/git-binding-id: 79a4f2fd-8745-4bec-9666-02bf179f5ca5
        kuberploy.io/renderer-image: ghcr.io/kuberploy/kuberploy-worker@sha256:2540550354958654b44ef37fcae95b76b021ebbf145cba89f17a0a49a917f20c
        kuberploy.io/runtime-chart-digest: sha256:e458486391d54f6f59a7443c541d4f2c5b1ad5f37422f293f97f4aac78624fd2
spec:
    sourceRepos:
        - '*'
    destinations:
        - namespace: kp-rc366-qualification-development
          server: https://kubernetes.default.svc
    clusterResourceWhitelist: []
    namespaceResourceWhitelist:
        - group: '*'
          kind: '*'
    orphanedResources:
        warn: true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
    name: kp-e-d7ba656ebad24f168251b729dee55894
    namespace: argocd
    labels:
        app.kubernetes.io/managed-by: kuberploy
        kuberploy.io/environment-id: d7ba656e-bad2-4f16-8251-b729dee55894
        kuberploy.io/project-id: b87693b1-4925-4049-9814-cf768bac0dd3
    annotations:
        argocd.argoproj.io/sync-wave: "0"
        kuberploy.io/git-binding-id: 79a4f2fd-8745-4bec-9666-02bf179f5ca5
        kuberploy.io/runtime-chart-digest: sha256:e458486391d54f6f59a7443c541d4f2c5b1ad5f37422f293f97f4aac78624fd2
spec:
    goTemplate: true
    goTemplateOptions:
        - missingkey=error
    generators:
        - list:
            elements:
                - deploymentId: 9a4cb81d-1d71-4631-b200-a1db38f036ee
                  applicationId: c9f4bad1-4d6c-4ee0-9660-823edce70b39
                  applicationName: kp-d-9a4cb81d1d714631b200a1db38f036ee
                  applicationPath: tenants/b87693b1-4925-4049-9814-cf768bac0dd3/environments/d7ba656e-bad2-4f16-8251-b729dee55894/apps/c9f4bad1-4d6c-4ee0-9660-823edce70b39/app.yaml
                  valuesRevision: 34e6fd7233622d36a8e8e44f2c4b5b0ab8f2672c
                - deploymentId: af79c813-6555-4c5d-a7d7-435e5ab96506
                  applicationId: 3ad5b221-9a88-4ce2-8d84-f78359d6fc71
                  applicationName: kp-d-af79c81365554c5da7d7435e5ab96506
                  applicationPath: tenants/b87693b1-4925-4049-9814-cf768bac0dd3/environments/d7ba656e-bad2-4f16-8251-b729dee55894/apps/3ad5b221-9a88-4ce2-8d84-f78359d6fc71/app.yaml
                  valuesRevision: 0b4d6d6fc73451809d7ba718f6233b307e46abde
    template:
        metadata:
            name: '{{.applicationName}}'
            namespace: argocd
            labels:
                app.kubernetes.io/managed-by: kuberploy
                kuberploy.io/application-id: '{{.applicationId}}'
                kuberploy.io/deployment-id: '{{.deploymentId}}'
                kuberploy.io/environment-id: d7ba656e-bad2-4f16-8251-b729dee55894
                kuberploy.io/project-id: b87693b1-4925-4049-9814-cf768bac0dd3
                kuberploy.io/service: '{{.applicationId}}'
            annotations:
                kuberploy.io/git-binding-id: 79a4f2fd-8745-4bec-9666-02bf179f5ca5
                kuberploy.io/renderer-image: ghcr.io/kuberploy/kuberploy-worker@sha256:2540550354958654b44ef37fcae95b76b021ebbf145cba89f17a0a49a917f20c
                kuberploy.io/runtime-chart-digest: sha256:e458486391d54f6f59a7443c541d4f2c5b1ad5f37422f293f97f4aac78624fd2
                kuberploy.io/runtime-chart-version: 0.1.0-rc.372
        spec:
            project: kp-rc366-qualification-development
            sources:
                - repoURL: oci://ghcr.io/kuberploy/charts/kuberploy-runtime
                  path: .
                  targetRevision: sha256:e458486391d54f6f59a7443c541d4f2c5b1ad5f37422f293f97f4aac78624fd2
                  helm:
                    valueFiles:
                        - $values/tenants/b87693b1-4925-4049-9814-cf768bac0dd3/variables.yaml
                        - $values/tenants/b87693b1-4925-4049-9814-cf768bac0dd3/environments/d7ba656e-bad2-4f16-8251-b729dee55894/variables.yaml
                        - $values/{{.applicationPath}}
                    ignoreMissingValueFiles: true
                    parameters:
                        - name: kuberployExpectedIdentity.projectId
                          value: b87693b1-4925-4049-9814-cf768bac0dd3
                          forceString: true
                        - name: kuberployExpectedIdentity.environmentId
                          value: d7ba656e-bad2-4f16-8251-b729dee55894
                          forceString: true
                        - name: kuberployExpectedIdentity.applicationId
                          value: '{{.applicationId}}'
                          forceString: true
                - repoURL: https://github.com/kuberploy/kuberploy-gitops-test.git
                  targetRevision: '{{.valuesRevision}}'
                  ref: values
            destination:
                namespace: kp-rc366-qualification-development
                server: https://kubernetes.default.svc
            syncPolicy:
                automated:
                    allowEmpty: false
                    prune: true
                    selfHeal: true
                syncOptions:
                    - CreateNamespace=false
                    - ServerSideApply=true
