apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: kp-rc386-clone-source-65e7fa40-rc386-clone-c9fed66a
    namespace: argocd
    labels:
        app.kubernetes.io/managed-by: kuberploy
        kuberploy.io/environment-id: edd3487b-8262-41ec-b267-314f579f375d
        kuberploy.io/project-id: 6b1da853-0bf9-436a-b9e7-4744f7a3586e
    annotations:
        argocd.argoproj.io/sync-options: PruneLast=true
        argocd.argoproj.io/sync-wave: "-10"
        kuberploy.io/git-binding-id: 1f83856e-7f9b-4626-a206-759703328d95
        kuberploy.io/renderer-image: ghcr.io/kuberploy/kuberploy-worker@sha256:e03811d40ddb4c9d8bdbc4c9a7707263a13669f50b0afcb025b2310c94bc3339
        kuberploy.io/runtime-chart-digest: sha256:78228c10ba28fbaaea5aaeacfd4aca4e3e6b584129e165c87252c6a90cecacaf
spec:
    sourceRepos:
        - '*'
    destinations:
        - namespace: kp-rc386-clone-source-65e7fa40-rc386-clone-c9fed66a
          server: https://kubernetes.default.svc
    clusterResourceWhitelist: []
    namespaceResourceWhitelist:
        - group: '*'
          kind: '*'
    orphanedResources:
        warn: true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
    name: kp-e-edd3487b826241ecb267314f579f375d
    namespace: argocd
    labels:
        app.kubernetes.io/managed-by: kuberploy
        kuberploy.io/environment-id: edd3487b-8262-41ec-b267-314f579f375d
        kuberploy.io/project-id: 6b1da853-0bf9-436a-b9e7-4744f7a3586e
    annotations:
        argocd.argoproj.io/sync-wave: "0"
        kuberploy.io/git-binding-id: 1f83856e-7f9b-4626-a206-759703328d95
        kuberploy.io/runtime-chart-digest: sha256:78228c10ba28fbaaea5aaeacfd4aca4e3e6b584129e165c87252c6a90cecacaf
spec:
    goTemplate: true
    goTemplateOptions:
        - missingkey=error
    generators:
        - list:
            elements:
                - deploymentId: 40bbc6bc-7609-4028-929d-5d58c4b7e1f8
                  applicationId: 6da05d06-69ed-48cc-8e58-15a1cd2e2c01
                  applicationName: kp-d-40bbc6bc76094028929d5d58c4b7e1f8
                  applicationPath: tenants/6b1da853-0bf9-436a-b9e7-4744f7a3586e/environments/edd3487b-8262-41ec-b267-314f579f375d/apps/6da05d06-69ed-48cc-8e58-15a1cd2e2c01/app.yaml
                  valuesRevision: 9e0e4a06fb995dfe34c0b7c70c99e1c0c2aeb077
    template:
        metadata:
            name: '{{.applicationName}}'
            namespace: argocd
            labels:
                app.kubernetes.io/managed-by: kuberploy
                kuberploy.io/application-id: '{{.applicationId}}'
                kuberploy.io/deployment-id: '{{.deploymentId}}'
                kuberploy.io/environment-id: edd3487b-8262-41ec-b267-314f579f375d
                kuberploy.io/project-id: 6b1da853-0bf9-436a-b9e7-4744f7a3586e
                kuberploy.io/service: '{{.applicationId}}'
            annotations:
                kuberploy.io/git-binding-id: 1f83856e-7f9b-4626-a206-759703328d95
                kuberploy.io/renderer-image: ghcr.io/kuberploy/kuberploy-worker@sha256:e03811d40ddb4c9d8bdbc4c9a7707263a13669f50b0afcb025b2310c94bc3339
                kuberploy.io/runtime-chart-digest: sha256:78228c10ba28fbaaea5aaeacfd4aca4e3e6b584129e165c87252c6a90cecacaf
                kuberploy.io/runtime-chart-version: 0.1.0-rc.386
        spec:
            project: kp-rc386-clone-source-65e7fa40-rc386-clone-c9fed66a
            sources:
                - repoURL: oci://ghcr.io/kuberploy/charts/kuberploy-runtime
                  path: .
                  targetRevision: sha256:78228c10ba28fbaaea5aaeacfd4aca4e3e6b584129e165c87252c6a90cecacaf
                  helm:
                    valueFiles:
                        - $values/tenants/6b1da853-0bf9-436a-b9e7-4744f7a3586e/variables.yaml
                        - $values/tenants/6b1da853-0bf9-436a-b9e7-4744f7a3586e/environments/edd3487b-8262-41ec-b267-314f579f375d/variables.yaml
                        - $values/{{.applicationPath}}
                    ignoreMissingValueFiles: true
                    parameters:
                        - name: kuberployExpectedIdentity.projectId
                          value: 6b1da853-0bf9-436a-b9e7-4744f7a3586e
                          forceString: true
                        - name: kuberployExpectedIdentity.environmentId
                          value: edd3487b-8262-41ec-b267-314f579f375d
                          forceString: true
                        - name: kuberployExpectedIdentity.applicationId
                          value: '{{.applicationId}}'
                          forceString: true
                - repoURL: https://github.com/kuberploy/kuberploy-gitops-test.git
                  targetRevision: '{{.valuesRevision}}'
                  ref: values
            destination:
                namespace: kp-rc386-clone-source-65e7fa40-rc386-clone-c9fed66a
                server: https://kubernetes.default.svc
            syncPolicy:
                automated:
                    allowEmpty: false
                    prune: true
                    selfHeal: true
                syncOptions:
                    - CreateNamespace=false
                    - ServerSideApply=true
