apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: kp-rc361-deletion-qualification-rc361-control
    namespace: argocd
    labels:
        app.kubernetes.io/managed-by: kuberploy
        kuberploy.io/environment-id: f19416a5-0760-4062-be0b-ece5af9f51c7
        kuberploy.io/project-id: 70d3f00a-4d77-4745-b974-0b5cff1a3e33
    annotations:
        argocd.argoproj.io/sync-options: PruneLast=true
        argocd.argoproj.io/sync-wave: "-10"
        kuberploy.io/git-binding-id: 5c22dd45-2853-43a9-89de-752788a1559a
        kuberploy.io/renderer-image: ghcr.io/kuberploy/kuberploy-worker@sha256:f564f3fe8697b3d6bb15e29e9807b1577e7dfaa972f2a9f92335618f91b48784
        kuberploy.io/runtime-chart-digest: sha256:5c0f148afc76d40471976b4e8d7f1370ef744c937bcf8437d51d7c7a67b5c4bd
spec:
    sourceRepos:
        - '*'
    destinations:
        - namespace: kp-rc361-deletion-qualification-rc361-control
          server: https://kubernetes.default.svc
    clusterResourceWhitelist: []
    namespaceResourceWhitelist:
        - group: '*'
          kind: '*'
    orphanedResources:
        warn: true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
    name: kp-e-f19416a507604062be0bece5af9f51c7
    namespace: argocd
    labels:
        app.kubernetes.io/managed-by: kuberploy
        kuberploy.io/environment-id: f19416a5-0760-4062-be0b-ece5af9f51c7
        kuberploy.io/project-id: 70d3f00a-4d77-4745-b974-0b5cff1a3e33
    annotations:
        argocd.argoproj.io/sync-wave: "0"
        kuberploy.io/git-binding-id: 5c22dd45-2853-43a9-89de-752788a1559a
        kuberploy.io/runtime-chart-digest: sha256:5c0f148afc76d40471976b4e8d7f1370ef744c937bcf8437d51d7c7a67b5c4bd
spec:
    goTemplate: true
    goTemplateOptions:
        - missingkey=error
    generators:
        - list:
            elements:
                - deploymentId: 4f0917c4-7e2c-4c72-b25e-35f3abf9fee6
                  applicationId: 585fdf32-d15e-466a-9a6c-20befe82afbd
                  applicationName: kp-d-4f0917c47e2c4c72b25e35f3abf9fee6
                  applicationPath: tenants/70d3f00a-4d77-4745-b974-0b5cff1a3e33/environments/f19416a5-0760-4062-be0b-ece5af9f51c7/apps/585fdf32-d15e-466a-9a6c-20befe82afbd/app.yaml
                  valuesRevision: 8b9e9c01208b69352105909a9c2cfdaf10f4c96a
    template:
        metadata:
            name: '{{.applicationName}}'
            namespace: argocd
            labels:
                app.kubernetes.io/managed-by: kuberploy
                kuberploy.io/application-id: '{{.applicationId}}'
                kuberploy.io/deployment-id: '{{.deploymentId}}'
                kuberploy.io/environment-id: f19416a5-0760-4062-be0b-ece5af9f51c7
                kuberploy.io/project-id: 70d3f00a-4d77-4745-b974-0b5cff1a3e33
                kuberploy.io/service: '{{.applicationId}}'
            annotations:
                kuberploy.io/git-binding-id: 5c22dd45-2853-43a9-89de-752788a1559a
                kuberploy.io/renderer-image: ghcr.io/kuberploy/kuberploy-worker@sha256:f564f3fe8697b3d6bb15e29e9807b1577e7dfaa972f2a9f92335618f91b48784
                kuberploy.io/runtime-chart-digest: sha256:5c0f148afc76d40471976b4e8d7f1370ef744c937bcf8437d51d7c7a67b5c4bd
                kuberploy.io/runtime-chart-version: 0.1.0-rc.364
        spec:
            project: kp-rc361-deletion-qualification-rc361-control
            sources:
                - repoURL: oci://ghcr.io/kuberploy/charts/kuberploy-runtime
                  path: .
                  targetRevision: sha256:5c0f148afc76d40471976b4e8d7f1370ef744c937bcf8437d51d7c7a67b5c4bd
                  helm:
                    valueFiles:
                        - $values/tenants/70d3f00a-4d77-4745-b974-0b5cff1a3e33/variables.yaml
                        - $values/tenants/70d3f00a-4d77-4745-b974-0b5cff1a3e33/environments/f19416a5-0760-4062-be0b-ece5af9f51c7/variables.yaml
                        - $values/{{.applicationPath}}
                    ignoreMissingValueFiles: true
                    parameters:
                        - name: kuberployExpectedIdentity.projectId
                          value: 70d3f00a-4d77-4745-b974-0b5cff1a3e33
                          forceString: true
                        - name: kuberployExpectedIdentity.environmentId
                          value: f19416a5-0760-4062-be0b-ece5af9f51c7
                          forceString: true
                        - name: kuberployExpectedIdentity.applicationId
                          value: '{{.applicationId}}'
                          forceString: true
                - repoURL: https://github.com/kuberploy/kuberploy-gitops-test.git
                  targetRevision: '{{.valuesRevision}}'
                  ref: values
            destination:
                namespace: kp-rc361-deletion-qualification-rc361-control
                server: https://kubernetes.default.svc
            syncPolicy:
                automated:
                    allowEmpty: false
                    prune: true
                    selfHeal: true
                syncOptions:
                    - CreateNamespace=false
                    - ServerSideApply=true
