apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: kp-rc399-qualification-rc402-clone-89b70119
    namespace: argocd
    labels:
        app.kubernetes.io/managed-by: kuberploy
        kuberploy.io/environment-id: f33017cb-c055-4384-addd-8c585a193b36
        kuberploy.io/project-id: 76b7df36-5540-4728-90e4-3332c9cd6b18
    annotations:
        argocd.argoproj.io/sync-options: PruneLast=true
        argocd.argoproj.io/sync-wave: "-10"
        kuberploy.io/git-binding-id: 94de47ae-13ed-40bd-8f84-648a00cb9443
        kuberploy.io/renderer-image: ghcr.io/kuberploy/kuberploy-worker@sha256:0e17aff293f541424a79f8e2b27533f832f2fc2d64586af12d1672527750da42
        kuberploy.io/runtime-chart-digest: sha256:d081c5009be028f35bc781e03db0506272c8418f5fb1169d7e17ac2a10815f06
spec:
    sourceRepos:
        - '*'
    destinations:
        - namespace: kp-rc399-qualification-rc402-clone-89b70119
          server: https://kubernetes.default.svc
    clusterResourceWhitelist: []
    namespaceResourceWhitelist:
        - group: '*'
          kind: '*'
    orphanedResources:
        warn: true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
    name: kp-e-f33017cbc0554384addd8c585a193b36
    namespace: argocd
    labels:
        app.kubernetes.io/managed-by: kuberploy
        kuberploy.io/environment-id: f33017cb-c055-4384-addd-8c585a193b36
        kuberploy.io/project-id: 76b7df36-5540-4728-90e4-3332c9cd6b18
    annotations:
        argocd.argoproj.io/sync-wave: "0"
        kuberploy.io/git-binding-id: 94de47ae-13ed-40bd-8f84-648a00cb9443
        kuberploy.io/runtime-chart-digest: sha256:d081c5009be028f35bc781e03db0506272c8418f5fb1169d7e17ac2a10815f06
spec:
    goTemplate: true
    goTemplateOptions:
        - missingkey=error
    generators:
        - list:
            elements:
                - deploymentId: 130ca31c-e46a-4b85-98e4-30e8199ed40a
                  applicationId: a3012d3f-08e6-4c69-b9b3-187251cb83bb
                  applicationName: kp-d-130ca31ce46a4b8598e430e8199ed40a
                  applicationPath: tenants/76b7df36-5540-4728-90e4-3332c9cd6b18/environments/f33017cb-c055-4384-addd-8c585a193b36/apps/a3012d3f-08e6-4c69-b9b3-187251cb83bb/app.yaml
                  valuesRevision: 43952397cf3c5750aa74a6516745de9fcd013c90
    template:
        metadata:
            name: '{{.applicationName}}'
            namespace: argocd
            labels:
                app.kubernetes.io/managed-by: kuberploy
                kuberploy.io/application-id: '{{.applicationId}}'
                kuberploy.io/deployment-id: '{{.deploymentId}}'
                kuberploy.io/environment-id: f33017cb-c055-4384-addd-8c585a193b36
                kuberploy.io/project-id: 76b7df36-5540-4728-90e4-3332c9cd6b18
                kuberploy.io/service: '{{.applicationId}}'
            annotations:
                kuberploy.io/git-binding-id: 94de47ae-13ed-40bd-8f84-648a00cb9443
                kuberploy.io/renderer-image: ghcr.io/kuberploy/kuberploy-worker@sha256:0e17aff293f541424a79f8e2b27533f832f2fc2d64586af12d1672527750da42
                kuberploy.io/runtime-chart-digest: sha256:d081c5009be028f35bc781e03db0506272c8418f5fb1169d7e17ac2a10815f06
                kuberploy.io/runtime-chart-version: 0.1.0-rc.402
        spec:
            project: kp-rc399-qualification-rc402-clone-89b70119
            sources:
                - repoURL: oci://ghcr.io/kuberploy/charts/kuberploy-runtime
                  path: .
                  targetRevision: sha256:d081c5009be028f35bc781e03db0506272c8418f5fb1169d7e17ac2a10815f06
                  helm:
                    valueFiles:
                        - $values/tenants/76b7df36-5540-4728-90e4-3332c9cd6b18/variables.yaml
                        - $values/tenants/76b7df36-5540-4728-90e4-3332c9cd6b18/environments/f33017cb-c055-4384-addd-8c585a193b36/variables.yaml
                        - $values/{{.applicationPath}}
                    ignoreMissingValueFiles: true
                    parameters:
                        - name: kuberployExpectedIdentity.projectId
                          value: 76b7df36-5540-4728-90e4-3332c9cd6b18
                          forceString: true
                        - name: kuberployExpectedIdentity.environmentId
                          value: f33017cb-c055-4384-addd-8c585a193b36
                          forceString: true
                        - name: kuberployExpectedIdentity.applicationId
                          value: '{{.applicationId}}'
                          forceString: true
                - repoURL: https://github.com/kuberploy/kuberploy-gitops-test.git
                  targetRevision: '{{.valuesRevision}}'
                  ref: values
            destination:
                namespace: kp-rc399-qualification-rc402-clone-89b70119
                server: https://kubernetes.default.svc
            syncPolicy:
                automated:
                    allowEmpty: false
                    prune: true
                    selfHeal: true
                syncOptions:
                    - CreateNamespace=false
                    - ServerSideApply=true
