{
  "apiVersion": "config.kuberploy.io/v1alpha1",
  "kind": "AppConfig",
  "metadata": {
    "id": "4cb99293-877e-431f-bcf9-0a44c508bf48",
    "name": "web"
  },
  "spec": {
    "applicationId": "4cb99293-877e-431f-bcf9-0a44c508bf48",
    "delivery": {
      "mode": "image",
      "registryPull": {
        "profileName": "managed-main",
        "profileRevision": 1,
        "targetId": "f0b03740-c7a9-4ca0-a852-e807c97d2fc8"
      },
      "release": {
        "digest": "sha256:1c2b85a91d4488b34e482e902008bec7f4afc55c10142ce8adbaf39ee76156d1",
        "repository": "registry.adminchatmate.com/kuberploy-qualification/projects/3da1a56f-b0fd-4b0f-b046-e710e3536fc0/services/4cb99293-877e-431f-bcf9-0a44c508bf48/image"
      }
    },
    "environmentId": "dd864b39-cf0d-422f-8900-60b73ce07e79",
    "projectId": "3da1a56f-b0fd-4b0f-b046-e710e3536fc0",
    "routes": [
      {
        "dns": {
          "mode": "manual"
        },
        "host": "rc415-clone-dd864b39.adminchatmate.com",
        "id": "dns01",
        "ingressClassName": "traefik",
        "middlewareRefs": [],
        "path": "/",
        "port": "http",
        "tls": {
          "mode": "httpOnly"
        }
      }
    ],
    "runtime": {
      "ports": [
        {
          "containerPort": 8080,
          "name": "http",
          "protocol": "TCP",
          "servicePort": 80
        }
      ],
      "probes": {
        "liveness": {
          "failureThreshold": 3,
          "httpGet": {
            "path": "/",
            "port": "http",
            "scheme": "HTTP"
          },
          "periodSeconds": 10,
          "timeoutSeconds": 2
        },
        "readiness": {
          "failureThreshold": 3,
          "httpGet": {
            "path": "/",
            "port": "http",
            "scheme": "HTTP"
          },
          "periodSeconds": 3,
          "timeoutSeconds": 2
        },
        "startup": {
          "failureThreshold": 30,
          "periodSeconds": 2,
          "tcpSocket": {
            "port": "http"
          },
          "timeoutSeconds": 1
        }
      },
      "replicas": 2,
      "resources": {
        "limits": {
          "cpu": "100m",
          "memory": "64Mi"
        },
        "requests": {
          "cpu": "10m",
          "memory": "16Mi"
        }
      },
      "strategy": {
        "type": "RollingUpdate"
      },
      "workloadType": "Deployment"
    }
  }
}
