apiVersion: config.kuberploy.io/v1alpha1
kind: AppConfig
metadata:
  id: "c9eb1c93-ef0b-4d2f-b632-60e16659da25"
  name: "rc414-gitssh-project-28b72542"
spec:
  projectId: "bbdc9ba9-af3f-45c1-af6b-c04650eada8c"
  applicationId: "c9eb1c93-ef0b-4d2f-b632-60e16659da25"
  environmentId: "a7fdeec1-3c68-40cf-a4da-ce956a678208"
  delivery:
    mode: image
    registryPull:
      targetId: "f0b03740-c7a9-4ca0-a852-e807c97d2fc8"
      profileName: "managed-main"
      profileRevision: 1
    release:
      repository: "registry.adminchatmate.com/kuberploy-qualification/projects/bbdc9ba9-af3f-45c1-af6b-c04650eada8c/services/c9eb1c93-ef0b-4d2f-b632-60e16659da25/image"
      digest: "sha256:a18dcb7e531348acfa07388bcf1d676f772bb00f0d9027661d11e371c9a3d0d8"
  runtime:
    ports:
      -
        containerPort: 8080
        name: "http"
        protocol: "TCP"
        servicePort: 80
    probes:
      liveness:
        failureThreshold: 3
        httpGet:
          path: "/"
          port: "http"
          scheme: "HTTP"
        periodSeconds: 10
        timeoutSeconds: 2
      readiness:
        failureThreshold: 3
        httpGet:
          path: "/"
          port: "http"
          scheme: "HTTP"
        periodSeconds: 3
        timeoutSeconds: 2
    replicas: 1
    resources:
      limits:
        cpu: "250m"
        memory: "128Mi"
      requests:
        cpu: "10m"
        memory: "16Mi"
    strategy:
      type: "RollingUpdate"
    workloadType: "Deployment"
