---
# Source: kuberploy-helm-fixture/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: rc339-helm-app-config
  namespace: kp-rc338-qualification-production
  labels:
    app.kubernetes.io/instance: rc339-helm-app
    app.kubernetes.io/name: rc339-helm-app
    kuberploy.io/application: "a938b0df-1d46-4e65-8741-cf0bb56bb548"
    kuberploy.io/environment: "bb54463d-ff08-449a-84df-0827e49da938"
    kuberploy.io/project: "47f48012-64a6-433a-9502-27c0db1c61fe"
  annotations:
    qualification.kuberploy.io/sensitive-token: "rc331-git-sensitive"
data:
  MESSAGE: "rc331-git-message"

---
# Source: kuberploy-helm-fixture/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rc339-helm-app
  namespace: kp-rc338-qualification-production
  labels:
    app.kubernetes.io/instance: rc339-helm-app
    app.kubernetes.io/name: rc339-helm-app
    kuberploy.io/application: "a938b0df-1d46-4e65-8741-cf0bb56bb548"
    kuberploy.io/environment: "bb54463d-ff08-449a-84df-0827e49da938"
    kuberploy.io/project: "47f48012-64a6-433a-9502-27c0db1c61fe"
spec:
  replicas: 1
  selector:
    matchLabels:
      kuberploy.io/application: "a938b0df-1d46-4e65-8741-cf0bb56bb548"
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: rc339-helm-app
        app.kubernetes.io/name: rc339-helm-app
        kuberploy.io/application: "a938b0df-1d46-4e65-8741-cf0bb56bb548"
        kuberploy.io/environment: "bb54463d-ff08-449a-84df-0827e49da938"
        kuberploy.io/project: "47f48012-64a6-433a-9502-27c0db1c61fe"
    spec:
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: fixture
          image: registry.k8s.io/e2e-test-images/agnhost@sha256:99c6b4bb4a1e1df3f0b3752168c89358794d02258ebebc26bf21c29399011a85
          imagePullPolicy: IfNotPresent
          command: ["/agnhost"]
          args: ["netexec", "--http-port=8080", "--udp-port=-1", "--http-override=/echo?msg=rc331-git"]
          env:
            - name: QUALIFICATION_VALUE
              value: "rc331-git-environment"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65532
            runAsGroup: 65532
