apiVersion: config.kuberploy.io/v1alpha1
kind: AppConfig
metadata:
  id: "5954982d-322d-4687-9d43-bb11c6f697a9"
  name: "rc402-private-oci-2a4c94f3"
spec:
  projectId: "76b7df36-5540-4728-90e4-3332c9cd6b18"
  applicationId: "5954982d-322d-4687-9d43-bb11c6f697a9"
  environmentId: "138ece86-c752-4d68-86cb-d95a7d109f56"
  delivery:
    mode: image
    registryPull:
      targetId: "f0b03740-c7a9-4ca0-a852-e807c97d2fc8"
      profileName: "managed-main"
      profileRevision: 1
    release:
      repository: "registry.adminchatmate.com/kuberploy-qualification/projects/76b7df36-5540-4728-90e4-3332c9cd6b18/services/5954982d-322d-4687-9d43-bb11c6f697a9/image"
      digest: "sha256:5f1956a16918827fda956c1db094cb74354d85e78287b6b38269205e4f73c7ba"
  runtime:
    ports:
      -
        containerPort: 8080
        name: "http"
        protocol: "TCP"
    replicas: 1
    resources:
      limits:
        cpu: "250m"
        memory: "128Mi"
      requests:
        cpu: "25m"
        memory: "32Mi"
    strategy:
      type: "RollingUpdate"
    workloadType: "Deployment"
