apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: kp-h-41ca73c6937c4bebab17b4ef1d08780e
    namespace: argocd
    finalizers:
        - resources-finalizer.argocd.argoproj.io
    labels:
        app.kubernetes.io/component: approved-helm-application
        app.kubernetes.io/managed-by: kuberploy
        kuberploy.io/application-id: 41ca73c6-937c-4beb-ab17-b4ef1d08780e
        kuberploy.io/environment-id: 5cd7abf6-ae6e-4f82-bc73-6508f5311b89
        kuberploy.io/project-id: 0928a543-f9f0-475e-92b0-7ae522682a7e
    annotations:
        argocd.argoproj.io/manifest-generate-paths: platform/helm-manifests/environments/5cd7abf6-ae6e-4f82-bc73-6508f5311b89/applications/41ca73c6-937c-4beb-ab17-b4ef1d08780e/revisions/39bdd22a-710b-487c-b25d-e314a9266bc2/release.yaml
        kuberploy.io/helm-payload-digest: sha256:0d3225b1bb868f01460fec97cd4dc28c36a66dad33654bf72ce58c113b78d09f
        kuberploy.io/helm-payload-revision: c420008882c311ce7e2c2ed085acc05300db540d
        kuberploy.io/helm-release-revision: 39bdd22a-710b-487c-b25d-e314a9266bc2
spec:
    project: kp-rc331-qualification-dev
    source:
        repoURL: https://github.com/kuberploy/kuberploy-gitops-test.git
        targetRevision: c420008882c311ce7e2c2ed085acc05300db540d
        path: platform/helm-manifests/environments/5cd7abf6-ae6e-4f82-bc73-6508f5311b89/applications/41ca73c6-937c-4beb-ab17-b4ef1d08780e/revisions/39bdd22a-710b-487c-b25d-e314a9266bc2
        directory:
            recurse: false
            include: release.yaml
    destination:
        server: https://kubernetes.default.svc
        namespace: kp-rc331-qualification-dev
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
            allowEmpty: false
        syncOptions:
            - CreateNamespace=false
            - ServerSideApply=true
