apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: kp-h-41ca73c6937c4bebab17b4ef1d08780e
    namespace: argocd
    finalizers:
        - resources-finalizer.argocd.argoproj.io
    labels:
        app.kubernetes.io/component: approved-helm-application
        app.kubernetes.io/managed-by: kuberploy
        kuberploy.io/application-id: 41ca73c6-937c-4beb-ab17-b4ef1d08780e
        kuberploy.io/environment-id: 5cd7abf6-ae6e-4f82-bc73-6508f5311b89
        kuberploy.io/project-id: 0928a543-f9f0-475e-92b0-7ae522682a7e
    annotations:
        argocd.argoproj.io/manifest-generate-paths: platform/helm-manifests/environments/5cd7abf6-ae6e-4f82-bc73-6508f5311b89/applications/41ca73c6-937c-4beb-ab17-b4ef1d08780e/revisions/2523dad9-67e3-4952-908c-1c010c06d053/release.yaml
        kuberploy.io/helm-payload-digest: sha256:efb0777a59d6734bfbce43a29e032b489ade56c08c4fbd97503ac894133015c8
        kuberploy.io/helm-payload-revision: fdf894c7a9cc24b4aa6b236c3b029085cc53a70d
        kuberploy.io/helm-release-revision: 2523dad9-67e3-4952-908c-1c010c06d053
spec:
    project: kp-rc331-qualification-dev
    source:
        repoURL: https://github.com/kuberploy/kuberploy-gitops-test.git
        targetRevision: fdf894c7a9cc24b4aa6b236c3b029085cc53a70d
        path: platform/helm-manifests/environments/5cd7abf6-ae6e-4f82-bc73-6508f5311b89/applications/41ca73c6-937c-4beb-ab17-b4ef1d08780e/revisions/2523dad9-67e3-4952-908c-1c010c06d053
        directory:
            recurse: false
            include: release.yaml
    destination:
        server: https://kubernetes.default.svc
        namespace: kp-rc331-qualification-dev
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
            allowEmpty: false
        syncOptions:
            - CreateNamespace=false
            - ServerSideApply=true
