{
  "apiVersion": "config.kuberploy.io/v1alpha1",
  "kind": "AppConfig",
  "metadata": {
    "id": "a3012d3f-08e6-4c69-b9b3-187251cb83bb",
    "name": "github"
  },
  "spec": {
    "applicationId": "a3012d3f-08e6-4c69-b9b3-187251cb83bb",
    "delivery": {
      "mode": "image",
      "registryPull": {
        "profileName": "managed-main",
        "profileRevision": 1,
        "targetId": "f0b03740-c7a9-4ca0-a852-e807c97d2fc8"
      },
      "release": {
        "digest": "sha256:930cb8eab8fd47c04889dea29ad22a8a544c386d749928f718c2c7c5ca7964df",
        "repository": "registry.adminchatmate.com/kuberploy-qualification/projects/76b7df36-5540-4728-90e4-3332c9cd6b18/services/a3012d3f-08e6-4c69-b9b3-187251cb83bb/image"
      }
    },
    "environmentId": "138ece86-c752-4d68-86cb-d95a7d109f56",
    "projectId": "76b7df36-5540-4728-90e4-3332c9cd6b18",
    "runtime": {
      "ports": [
        {
          "containerPort": 8080,
          "name": "http",
          "protocol": "TCP",
          "servicePort": 80
        }
      ],
      "probes": {
        "liveness": {
          "failureThreshold": 3,
          "httpGet": {
            "path": "/",
            "port": "http",
            "scheme": "HTTP"
          },
          "periodSeconds": 10,
          "timeoutSeconds": 2
        },
        "readiness": {
          "failureThreshold": 3,
          "httpGet": {
            "path": "/",
            "port": "http",
            "scheme": "HTTP"
          },
          "periodSeconds": 3,
          "timeoutSeconds": 2
        }
      },
      "replicas": 1,
      "resources": {
        "limits": {
          "cpu": "100m",
          "memory": "64Mi"
        },
        "requests": {
          "cpu": "10m",
          "memory": "16Mi"
        }
      },
      "strategy": {
        "type": "RollingUpdate"
      },
      "workloadType": "Deployment"
    }
  }
}
