---
# Source: qualification/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: rc133-helm-qualification-qualification
  namespace: kp-rc89-qualification-development
  labels:
    app.kubernetes.io/instance: rc133-helm-qualification
    app.kubernetes.io/name: rc133-helm-qualification
    kuberploy.io/application: 936fbadb-97e8-4989-96a5-c5d34db0356d
    kuberploy.io/environment: 9ca3deb4-7de4-4404-ace6-0fd99ce95759
    kuberploy.io/project: 3821bcf5-83a9-4a72-9d10-9ee9ee6a4b73
data:
  message: "private-oci-qualified"

---
# Source: qualification/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rc133-helm-qualification-qualification
  namespace: kp-rc89-qualification-development
  labels:
    app.kubernetes.io/instance: rc133-helm-qualification
    app.kubernetes.io/name: rc133-helm-qualification
    kuberploy.io/application: 936fbadb-97e8-4989-96a5-c5d34db0356d
    kuberploy.io/environment: 9ca3deb4-7de4-4404-ace6-0fd99ce95759
    kuberploy.io/project: 3821bcf5-83a9-4a72-9d10-9ee9ee6a4b73
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rc133-helm-qualification
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: rc133-helm-qualification
        app.kubernetes.io/name: rc133-helm-qualification
        kuberploy.io/application: 936fbadb-97e8-4989-96a5-c5d34db0356d
        kuberploy.io/environment: 9ca3deb4-7de4-4404-ace6-0fd99ce95759
        kuberploy.io/project: 3821bcf5-83a9-4a72-9d10-9ee9ee6a4b73
    spec:
      automountServiceAccountToken: false
      containers:
        - name: agnhost
          image: registry.k8s.io/e2e-test-images/agnhost@sha256:99c6b4bb4a1e1df3f0b3752168c89358794d02258ebebc26bf21c29399011a85
          args: ["pause"]
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
