apiVersion: config.kuberploy.io/v1alpha1
kind: AppConfig
metadata:
  id: "16ce5f65-b44a-4e5e-be85-9d0e2b648276"
  name: "rc414-private-oci-9d13de6a"
spec:
  projectId: "21a12574-8177-418f-b54e-4b1adc4cc301"
  applicationId: "16ce5f65-b44a-4e5e-be85-9d0e2b648276"
  environmentId: "c06912f0-5612-4593-b697-0a1cb12beab2"
  delivery:
    mode: image
    registryPull:
      targetId: "f0b03740-c7a9-4ca0-a852-e807c97d2fc8"
      profileName: "managed-main"
      profileRevision: 1
    release:
      repository: "registry.adminchatmate.com/kuberploy-qualification/projects/21a12574-8177-418f-b54e-4b1adc4cc301/services/16ce5f65-b44a-4e5e-be85-9d0e2b648276/image"
      digest: "sha256:5f1956a16918827fda956c1db094cb74354d85e78287b6b38269205e4f73c7ba"
  runtime:
    ports:
      -
        containerPort: 8080
        name: "http"
        protocol: "TCP"
    replicas: 1
    resources:
      limits:
        cpu: "250m"
        memory: "128Mi"
      requests:
        cpu: "25m"
        memory: "32Mi"
    strategy:
      type: "RollingUpdate"
    workloadType: "Deployment"
