apiVersion: config.kuberploy.io/v1alpha1
kind: AppConfig
metadata:
  id: "f1f5f9b0-6a86-4031-b9b6-2d9eeea718bd"
  name: "rc402-oci-a4185560"
spec:
  projectId: "76b7df36-5540-4728-90e4-3332c9cd6b18"
  applicationId: "f1f5f9b0-6a86-4031-b9b6-2d9eeea718bd"
  environmentId: "138ece86-c752-4d68-86cb-d95a7d109f56"
  delivery:
    mode: image
    release:
      repository: "registry.k8s.io/e2e-test-images/agnhost"
      digest: "sha256:99c6b4bb4a1e1df3f0b3752168c89358794d02258ebebc26bf21c29399011a85"
  runtime:
    args:
      - "netexec"
      - "--http-port=8080"
      - "--udp-port=-1"
      - "--http-override=/echo?msg=development"
    command:
      - "/agnhost"
    env:
      -
        name: "RC402_ENVIRONMENT"
        value: "development"
    ports:
      -
        containerPort: 8080
        name: "http"
        protocol: "TCP"
        servicePort: 80
    probes:
      liveness:
        failureThreshold: 3
        httpGet:
          path: "/echo?msg=live"
          port: "http"
          scheme: "HTTP"
        periodSeconds: 10
        timeoutSeconds: 2
      readiness:
        failureThreshold: 3
        httpGet:
          path: "/echo?msg=ready"
          port: "http"
          scheme: "HTTP"
        periodSeconds: 3
        timeoutSeconds: 2
      startup:
        failureThreshold: 30
        periodSeconds: 2
        tcpSocket:
          port: "http"
        timeoutSeconds: 1
    replicas: 1
    resources:
      limits:
        cpu: "100m"
        memory: "64Mi"
      requests:
        cpu: "10m"
        memory: "16Mi"
    strategy:
      type: "RollingUpdate"
    terminationGracePeriodSeconds: 20
    workingDirectory: "/"
    workloadType: "Deployment"
