{
  "apiVersion": "config.kuberploy.io/v1alpha1",
  "kind": "AppConfig",
  "metadata": {
    "id": "3ad5b221-9a88-4ce2-8d84-f78359d6fc71",
    "name": "github"
  },
  "spec": {
    "applicationId": "3ad5b221-9a88-4ce2-8d84-f78359d6fc71",
    "delivery": {
      "mode": "image",
      "registryPull": {
        "profileName": "managed-main",
        "profileRevision": 1,
        "targetId": "f0b03740-c7a9-4ca0-a852-e807c97d2fc8"
      },
      "release": {
        "digest": "sha256:8779774e91c4dbc85f0912adacc7c57f6767e58a994e7ab20b28250c56259b3e",
        "repository": "registry.adminchatmate.com/kuberploy-qualification/projects/b87693b1-4925-4049-9814-cf768bac0dd3/services/3ad5b221-9a88-4ce2-8d84-f78359d6fc71/image"
      }
    },
    "environmentId": "d7ba656e-bad2-4f16-8251-b729dee55894",
    "projectId": "b87693b1-4925-4049-9814-cf768bac0dd3",
    "runtime": {
      "ports": [
        {
          "containerPort": 8080,
          "name": "http",
          "protocol": "TCP"
        }
      ],
      "replicas": 1,
      "resources": {
        "requests": {
          "cpu": "50m",
          "memory": "100Mi"
        }
      },
      "strategy": {
        "type": "RollingUpdate"
      },
      "workloadType": "Deployment"
    }
  }
}
