apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: kp-rc156-qualification-rc244-external-dns
    namespace: argocd
    labels:
        app.kubernetes.io/managed-by: kuberploy
        kuberploy.io/environment-id: 14cc8e8c-5dcc-45c4-beea-54a543bd2f47
        kuberploy.io/project-id: 0bc72c28-936f-4925-83f5-05a51d18f4bb
    annotations:
        argocd.argoproj.io/sync-options: PruneLast=true
        argocd.argoproj.io/sync-wave: "-10"
        kuberploy.io/git-binding-id: 8a532e86-9573-461f-a4b6-adb91465f737
        kuberploy.io/renderer-image: ghcr.io/kuberploy/kuberploy-worker@sha256:916bfffbedd656b469c70ffdfa49fe5917aad23470cbdc32c7c77aef454c17cf
        kuberploy.io/runtime-chart-digest: sha256:af46b18a30119fef406ebae48989838202bd98522fc3c98e8951f65014bded09
spec:
    sourceRepos:
        - https://github.com/kuberploy/kuberploy-gitops-test.git
        - oci://ghcr.io/kuberploy/charts/kuberploy-runtime
    destinations:
        - namespace: kp-rc156-qualification-rc244-external-dns
          server: https://kubernetes.default.svc
    clusterResourceWhitelist: []
    namespaceResourceWhitelist:
        - group: ""
          kind: ConfigMap
        - group: ""
          kind: PersistentVolumeClaim
        - group: ""
          kind: Service
        - group: ""
          kind: ServiceAccount
        - group: apps
          kind: Deployment
        - group: apps
          kind: StatefulSet
        - group: autoscaling
          kind: HorizontalPodAutoscaler
        - group: batch
          kind: CronJob
        - group: batch
          kind: Job
        - group: networking.k8s.io
          kind: Ingress
        - group: networking.k8s.io
          kind: NetworkPolicy
        - group: policy
          kind: PodDisruptionBudget
        - group: traefik.io
          kind: Middleware
    orphanedResources:
        warn: true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
    name: kp-e-14cc8e8c5dcc45c4beea54a543bd2f47
    namespace: argocd
    labels:
        app.kubernetes.io/managed-by: kuberploy
        kuberploy.io/environment-id: 14cc8e8c-5dcc-45c4-beea-54a543bd2f47
        kuberploy.io/project-id: 0bc72c28-936f-4925-83f5-05a51d18f4bb
    annotations:
        argocd.argoproj.io/sync-wave: "0"
        kuberploy.io/git-binding-id: 8a532e86-9573-461f-a4b6-adb91465f737
        kuberploy.io/runtime-chart-digest: sha256:af46b18a30119fef406ebae48989838202bd98522fc3c98e8951f65014bded09
spec:
    goTemplate: true
    goTemplateOptions:
        - missingkey=error
    generators:
        - list:
            elements:
                - deploymentId: 868a9ea4-3248-4296-a5f0-ae3933166b82
                  applicationId: 29c89b56-56a6-4354-97d6-662e9adf0f44
                  applicationName: kp-d-868a9ea432484296a5f0ae3933166b82
                  applicationPath: tenants/0bc72c28-936f-4925-83f5-05a51d18f4bb/environments/14cc8e8c-5dcc-45c4-beea-54a543bd2f47/apps/29c89b56-56a6-4354-97d6-662e9adf0f44/app.yaml
                  valuesRevision: bbae3aa0e2f9e23df6677b5f0334144d04115f6b
    template:
        metadata:
            name: '{{.applicationName}}'
            namespace: argocd
            labels:
                app.kubernetes.io/managed-by: kuberploy
                kuberploy.io/application-id: '{{.applicationId}}'
                kuberploy.io/deployment-id: '{{.deploymentId}}'
                kuberploy.io/environment-id: 14cc8e8c-5dcc-45c4-beea-54a543bd2f47
                kuberploy.io/project-id: 0bc72c28-936f-4925-83f5-05a51d18f4bb
                kuberploy.io/service: '{{.applicationId}}'
            annotations:
                kuberploy.io/git-binding-id: 8a532e86-9573-461f-a4b6-adb91465f737
                kuberploy.io/renderer-image: ghcr.io/kuberploy/kuberploy-worker@sha256:916bfffbedd656b469c70ffdfa49fe5917aad23470cbdc32c7c77aef454c17cf
                kuberploy.io/runtime-chart-digest: sha256:af46b18a30119fef406ebae48989838202bd98522fc3c98e8951f65014bded09
                kuberploy.io/runtime-chart-version: 0.1.0-rc.245
        spec:
            project: kp-rc156-qualification-rc244-external-dns
            sources:
                - repoURL: oci://ghcr.io/kuberploy/charts/kuberploy-runtime
                  path: .
                  targetRevision: sha256:af46b18a30119fef406ebae48989838202bd98522fc3c98e8951f65014bded09
                  helm:
                    valueFiles:
                        - $values/tenants/0bc72c28-936f-4925-83f5-05a51d18f4bb/variables.yaml
                        - $values/tenants/0bc72c28-936f-4925-83f5-05a51d18f4bb/environments/14cc8e8c-5dcc-45c4-beea-54a543bd2f47/variables.yaml
                        - $values/{{.applicationPath}}
                    ignoreMissingValueFiles: true
                    parameters:
                        - name: kuberployExpectedIdentity.projectId
                          value: 0bc72c28-936f-4925-83f5-05a51d18f4bb
                          forceString: true
                        - name: kuberployExpectedIdentity.environmentId
                          value: 14cc8e8c-5dcc-45c4-beea-54a543bd2f47
                          forceString: true
                        - name: kuberployExpectedIdentity.applicationId
                          value: '{{.applicationId}}'
                          forceString: true
                - repoURL: https://github.com/kuberploy/kuberploy-gitops-test.git
                  targetRevision: '{{.valuesRevision}}'
                  ref: values
            destination:
                namespace: kp-rc156-qualification-rc244-external-dns
                server: https://kubernetes.default.svc
            syncPolicy:
                automated:
                    allowEmpty: false
                    prune: true
                    selfHeal: true
                syncOptions:
                    - CreateNamespace=false
                    - ServerSideApply=true
