apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: kp-p-c06eb0f93ac344d4b50e68fe0d993064
    namespace: argocd
    labels:
        app.kubernetes.io/managed-by: kuberploy
        kuberploy.io/environment-id: c7f3a333-91a3-44c7-b298-bde1cce72a2e
        kuberploy.io/project-id: c06eb0f9-3ac3-44d4-b50e-68fe0d993064
    annotations:
        argocd.argoproj.io/sync-wave: "-10"
        kuberploy.io/git-binding-id: a6b4d9b0-b442-443c-8ff5-10fde53c5944
        kuberploy.io/renderer-image: ghcr.io/kuberploy/kuberploy-worker@sha256:db134af1fede92368c2a6309dc20213c0f1292f6c24be5e58960edf333b324c1
        kuberploy.io/runtime-chart-digest: sha256:9a0a17f9053c4c769bbb9efd0946a167d77a982e22cdb77fe385ee3709dfc3a5
spec:
    sourceRepos:
        - https://github.com/kuberploy/kuberploy-gitops-test.git
        - oci://ghcr.io/kuberploy/charts/kuberploy-runtime
    destinations:
        - namespace: kp-kuberploy-qualification-development
          server: https://kubernetes.default.svc
    clusterResourceWhitelist: []
    namespaceResourceWhitelist:
        - group: ""
          kind: ConfigMap
        - group: ""
          kind: Service
        - group: ""
          kind: ServiceAccount
        - group: apps
          kind: Deployment
        - group: autoscaling
          kind: HorizontalPodAutoscaler
        - group: networking.k8s.io
          kind: Ingress
        - group: networking.k8s.io
          kind: NetworkPolicy
        - group: policy
          kind: PodDisruptionBudget
        - group: traefik.io
          kind: Middleware
        - group: cert-manager.io
          kind: Certificate
    orphanedResources:
        warn: true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
    name: kp-e-c7f3a33391a344c7b298bde1cce72a2e
    namespace: argocd
    labels:
        app.kubernetes.io/managed-by: kuberploy
        kuberploy.io/environment-id: c7f3a333-91a3-44c7-b298-bde1cce72a2e
        kuberploy.io/project-id: c06eb0f9-3ac3-44d4-b50e-68fe0d993064
    annotations:
        argocd.argoproj.io/sync-wave: "0"
        kuberploy.io/git-binding-id: a6b4d9b0-b442-443c-8ff5-10fde53c5944
        kuberploy.io/runtime-chart-digest: sha256:9a0a17f9053c4c769bbb9efd0946a167d77a982e22cdb77fe385ee3709dfc3a5
spec:
    goTemplate: true
    goTemplateOptions:
        - missingkey=error
    generators:
        - list:
            elements:
                - deploymentId: 7af2a181-f301-4ed8-be9b-f6434fe67164
                  applicationId: 3a1e8696-9300-42c6-92ce-acabae29f50f
                  applicationName: kp-d-7af2a181f3014ed8be9bf6434fe67164
                  applicationPath: tenants/c06eb0f9-3ac3-44d4-b50e-68fe0d993064/environments/c7f3a333-91a3-44c7-b298-bde1cce72a2e/apps/3a1e8696-9300-42c6-92ce-acabae29f50f/app.yaml
                  valuesRevision: b231688ce985265cb5bb3d3885e9e719fbfa86ba
    template:
        metadata:
            name: '{{.applicationName}}'
            namespace: argocd
            labels:
                app.kubernetes.io/managed-by: kuberploy
                kuberploy.io/application-id: '{{.applicationId}}'
                kuberploy.io/deployment-id: '{{.deploymentId}}'
                kuberploy.io/environment-id: c7f3a333-91a3-44c7-b298-bde1cce72a2e
                kuberploy.io/project-id: c06eb0f9-3ac3-44d4-b50e-68fe0d993064
                kuberploy.io/service: '{{.applicationId}}'
            annotations:
                kuberploy.io/git-binding-id: a6b4d9b0-b442-443c-8ff5-10fde53c5944
                kuberploy.io/renderer-image: ghcr.io/kuberploy/kuberploy-worker@sha256:db134af1fede92368c2a6309dc20213c0f1292f6c24be5e58960edf333b324c1
                kuberploy.io/runtime-chart-digest: sha256:9a0a17f9053c4c769bbb9efd0946a167d77a982e22cdb77fe385ee3709dfc3a5
                kuberploy.io/runtime-chart-version: 0.1.0-rc.67
        spec:
            project: kp-p-c06eb0f93ac344d4b50e68fe0d993064
            sources:
                - repoURL: oci://ghcr.io/kuberploy/charts/kuberploy-runtime
                  path: .
                  targetRevision: sha256:9a0a17f9053c4c769bbb9efd0946a167d77a982e22cdb77fe385ee3709dfc3a5
                  helm:
                    valueFiles:
                        - $values/tenants/c06eb0f9-3ac3-44d4-b50e-68fe0d993064/variables.yaml
                        - $values/tenants/c06eb0f9-3ac3-44d4-b50e-68fe0d993064/environments/c7f3a333-91a3-44c7-b298-bde1cce72a2e/variables.yaml
                        - $values/{{.applicationPath}}
                    ignoreMissingValueFiles: true
                    parameters:
                        - name: kuberployExpectedIdentity.projectId
                          value: c06eb0f9-3ac3-44d4-b50e-68fe0d993064
                          forceString: true
                        - name: kuberployExpectedIdentity.environmentId
                          value: c7f3a333-91a3-44c7-b298-bde1cce72a2e
                          forceString: true
                        - name: kuberployExpectedIdentity.applicationId
                          value: '{{.applicationId}}'
                          forceString: true
                - repoURL: https://github.com/kuberploy/kuberploy-gitops-test.git
                  targetRevision: '{{.valuesRevision}}'
                  ref: values
            destination:
                namespace: kp-kuberploy-qualification-development
                server: https://kubernetes.default.svc
            syncPolicy:
                automated:
                    allowEmpty: false
                    prune: true
                    selfHeal: true
                syncOptions:
                    - CreateNamespace=false
                    - ServerSideApply=true
