{
  "apiVersion": "config.kuberploy.io/v1alpha1",
  "kind": "AppConfig",
  "metadata": {
    "id": "94fb81be-efc7-40fd-8656-a2c5918672c1",
    "name": "web"
  },
  "spec": {
    "applicationId": "94fb81be-efc7-40fd-8656-a2c5918672c1",
    "delivery": {
      "mode": "image",
      "registryPull": {
        "profileName": "managed-main",
        "profileRevision": 1,
        "targetId": "f0b03740-c7a9-4ca0-a852-e807c97d2fc8"
      },
      "release": {
        "digest": "sha256:b90d3db866d0cabb9dcfd7ad47f28ec81d5c85dc68a925669b4e24f677c2f330",
        "repository": "registry.adminchatmate.com/kuberploy-qualification/projects/a2f5afcc-239b-47e6-8cbd-d0de07670fbe/services/94fb81be-efc7-40fd-8656-a2c5918672c1/image"
      }
    },
    "environmentId": "1d1cff85-636d-43cf-a6cf-289b0f430080",
    "projectId": "a2f5afcc-239b-47e6-8cbd-d0de07670fbe",
    "runtime": {
      "ports": [
        {
          "containerPort": 8080,
          "name": "http",
          "protocol": "TCP",
          "servicePort": 80
        }
      ],
      "probes": {
        "liveness": {
          "failureThreshold": 3,
          "httpGet": {
            "path": "/",
            "port": "http",
            "scheme": "HTTP"
          },
          "periodSeconds": 10,
          "timeoutSeconds": 2
        },
        "readiness": {
          "failureThreshold": 3,
          "httpGet": {
            "path": "/",
            "port": "http",
            "scheme": "HTTP"
          },
          "periodSeconds": 3,
          "timeoutSeconds": 2
        }
      },
      "replicas": 1,
      "resources": {
        "limits": {
          "cpu": "250m",
          "memory": "128Mi"
        },
        "requests": {
          "cpu": "10m",
          "memory": "16Mi"
        }
      },
      "strategy": {
        "type": "RollingUpdate"
      },
      "workloadType": "Deployment"
    }
  }
}
