apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: kp-h-a938b0df1d464e658741cf0bb56bb548
    namespace: argocd
    finalizers:
        - resources-finalizer.argocd.argoproj.io
    labels:
        app.kubernetes.io/component: approved-helm-application
        app.kubernetes.io/managed-by: kuberploy
        kuberploy.io/application-id: a938b0df-1d46-4e65-8741-cf0bb56bb548
        kuberploy.io/environment-id: bb54463d-ff08-449a-84df-0827e49da938
        kuberploy.io/project-id: 47f48012-64a6-433a-9502-27c0db1c61fe
    annotations:
        argocd.argoproj.io/manifest-generate-paths: platform/helm-manifests/environments/bb54463d-ff08-449a-84df-0827e49da938/applications/a938b0df-1d46-4e65-8741-cf0bb56bb548/revisions/95604626-0adb-48ce-bbad-1fc1826b0fbc/release.yaml
        kuberploy.io/helm-payload-digest: sha256:81a807848227abfdbaa6fd5a5d86eaf2c819c44779ebd0c901526481f25b6259
        kuberploy.io/helm-payload-revision: 29b4e6ecb9a780cad2d5ecd55d367f6638cdc205
        kuberploy.io/helm-release-revision: 95604626-0adb-48ce-bbad-1fc1826b0fbc
spec:
    project: kp-rc338-qualification-production
    source:
        repoURL: https://github.com/kuberploy/kuberploy-gitops-test.git
        targetRevision: 29b4e6ecb9a780cad2d5ecd55d367f6638cdc205
        path: platform/helm-manifests/environments/bb54463d-ff08-449a-84df-0827e49da938/applications/a938b0df-1d46-4e65-8741-cf0bb56bb548/revisions/95604626-0adb-48ce-bbad-1fc1826b0fbc
        directory:
            recurse: false
            include: release.yaml
    destination:
        server: https://kubernetes.default.svc
        namespace: kp-rc338-qualification-production
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
            allowEmpty: false
        syncOptions:
            - CreateNamespace=false
            - ServerSideApply=true
