apiVersion: config.kuberploy.io/v1alpha1
kind: AppConfig
metadata:
  id: "1161e875-5a6f-4610-a0a4-080c05974e2a"
  name: "github"
spec:
  projectId: "92c030ae-83a7-4308-87cc-0f3742347ce2"
  applicationId: "1161e875-5a6f-4610-a0a4-080c05974e2a"
  environmentId: "17edcd5e-f159-4236-8e12-70d484d3c961"
  delivery:
    mode: image
    registryPull:
      targetId: "f0b03740-c7a9-4ca0-a852-e807c97d2fc8"
      profileName: "managed-main"
      profileRevision: 1
    release:
      repository: "registry.adminchatmate.com/kuberploy-qualification/projects/92c030ae-83a7-4308-87cc-0f3742347ce2/services/1161e875-5a6f-4610-a0a4-080c05974e2a/image"
      digest: "sha256:021cce6bad360ebb3a48d04d5e36e511f7d370cbe145db74004aacbe75830541"
  runtime:
    ports:
      -
        containerPort: 8080
        name: "http"
        protocol: "TCP"
        servicePort: 80
    probes:
      liveness:
        failureThreshold: 3
        httpGet:
          path: "/"
          port: "http"
          scheme: "HTTP"
        periodSeconds: 10
        timeoutSeconds: 2
      readiness:
        failureThreshold: 3
        httpGet:
          path: "/"
          port: "http"
          scheme: "HTTP"
        periodSeconds: 3
        timeoutSeconds: 2
    replicas: 1
    resources:
      limits:
        cpu: "250m"
        memory: "128Mi"
      requests:
        cpu: "10m"
        memory: "16Mi"
    strategy:
      type: "RollingUpdate"
    workloadType: "Deployment"
