apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: kp-h-936fbadb97e8498996a5c5d34db0356d
    namespace: argocd
    labels:
        app.kubernetes.io/component: approved-helm-application
        app.kubernetes.io/managed-by: kuberploy
        kuberploy.io/application-id: 936fbadb-97e8-4989-96a5-c5d34db0356d
        kuberploy.io/environment-id: 9ca3deb4-7de4-4404-ace6-0fd99ce95759
        kuberploy.io/project-id: 3821bcf5-83a9-4a72-9d10-9ee9ee6a4b73
    annotations:
        argocd.argoproj.io/manifest-generate-paths: clusters/22222222-2222-4222-8222-222222222222/helm-manifests/environments/9ca3deb4-7de4-4404-ace6-0fd99ce95759/applications/936fbadb-97e8-4989-96a5-c5d34db0356d/revisions/e50e8160-4f06-419d-82a1-0cea97225b11/release.yaml
        kuberploy.io/helm-payload-digest: sha256:97b98561689e769ff9dd249407ad70590eccaf688da7ce53f2924ede4c51c7e4
        kuberploy.io/helm-payload-revision: e2c1638a0b66b78c7f77827514b1fdad23a9f68b
        kuberploy.io/helm-release-revision: e50e8160-4f06-419d-82a1-0cea97225b11
spec:
    project: kp-rc89-qualification-development
    source:
        repoURL: https://github.com/kuberploy/kuberploy-gitops-test.git
        targetRevision: e2c1638a0b66b78c7f77827514b1fdad23a9f68b
        path: clusters/22222222-2222-4222-8222-222222222222/helm-manifests/environments/9ca3deb4-7de4-4404-ace6-0fd99ce95759/applications/936fbadb-97e8-4989-96a5-c5d34db0356d/revisions/e50e8160-4f06-419d-82a1-0cea97225b11
        directory:
            recurse: false
            include: release.yaml
    destination:
        server: https://kubernetes.default.svc
        namespace: kp-rc89-qualification-development
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
            allowEmpty: false
        syncOptions:
            - CreateNamespace=false
            - ServerSideApply=true
