apiVersion: config.kuberploy.io/v1alpha1
kind: AppConfig
metadata:
  id: "a45f19a8-d332-4a4d-bdea-55cfabaa5c98"
  name: "web-fixture"
spec:
  projectId: "0bc72c28-936f-4925-83f5-05a51d18f4bb"
  applicationId: "a45f19a8-d332-4a4d-bdea-55cfabaa5c98"
  environmentId: "55aadf18-50ec-433d-8f61-932b83025aee"
  delivery:
    mode: image
    release:
      repository: "registry.k8s.io/e2e-test-images/agnhost"
      digest: "sha256:99c6b4bb4a1e1df3f0b3752168c89358794d02258ebebc26bf21c29399011a85"
  runtime:
    args:
      - "netexec"
      - "--http-port=8080"
      - "--udp-port=-1"
    command:
      - "/agnhost"
    env:
      -
        name: "ENV_ONLY"
        value: "rc157-parent-change"
      -
        name: "RELEASE_LANE"
        value: "environment"
      -
        name: "SHARED_REGION"
        value: "ap-southeast-1"
    ports:
      -
        containerPort: 8080
        name: "http"
        protocol: "TCP"
        servicePort: 80
    replicas: 2
    resources:
      limits:
        cpu: "250m"
        memory: "128Mi"
      requests:
        cpu: "25m"
        memory: "32Mi"
    strategy:
      type: "RollingUpdate"
    workingDirectory: "/"
    workloadType: "Deployment"
