apiVersion: config.kuberploy.io/v1alpha1
kind: AppConfig
metadata:
  id: "19c56fa1-ee98-4c4a-a8da-6a74c559a5c7"
  name: "qa-feature-app"
spec:
  projectId: "bb2ac9ec-545f-46ec-9372-0774fc770769"
  applicationId: "19c56fa1-ee98-4c4a-a8da-6a74c559a5c7"
  environmentId: "f435d127-3032-4f07-bf82-cb0400a1cfb8"
  delivery:
    mode: image
    release:
      repository: "ghcr.io/kuberploy/kuberploy-web"
      digest: "sha256:1f3feab3583b2a22902c574ddc2300cf51be154bd82845008b8ca51cf4bb7bd5"
  runtime:
    ports:
      -
        containerPort: 3000
        name: "http"
        protocol: "TCP"
    replicas: 1
    resources:
      requests:
        cpu: "50m"
        memory: "100Mi"
    strategy:
      type: "RollingUpdate"
    workloadType: "Deployment"
