apiVersion: config.kuberploy.io/v1alpha1
kind: AppConfig
metadata:
  id: "05fc1109-f21e-4da8-80fd-82b89d31a115"
  name: "rc414-gitssh-app-6bd21aa4"
spec:
  projectId: "df2f110c-550b-4045-8d07-4aab08fcce0f"
  applicationId: "05fc1109-f21e-4da8-80fd-82b89d31a115"
  environmentId: "e7c5d040-de96-4949-8d00-f1bd30d9db6b"
  delivery:
    mode: image
    registryPull:
      targetId: "f0b03740-c7a9-4ca0-a852-e807c97d2fc8"
      profileName: "managed-main"
      profileRevision: 1
    release:
      repository: "registry.adminchatmate.com/kuberploy-qualification/projects/df2f110c-550b-4045-8d07-4aab08fcce0f/services/05fc1109-f21e-4da8-80fd-82b89d31a115/image"
      digest: "sha256:d5c03add9fe40fe287b8fce4d8be9182daae3dc3ef9e3e5611ea275c8f6fdfc3"
  runtime:
    ports:
      -
        containerPort: 8080
        name: "http"
        protocol: "TCP"
        servicePort: 80
    probes:
      liveness:
        failureThreshold: 3
        httpGet:
          path: "/"
          port: "http"
          scheme: "HTTP"
        periodSeconds: 10
        timeoutSeconds: 2
      readiness:
        failureThreshold: 3
        httpGet:
          path: "/"
          port: "http"
          scheme: "HTTP"
        periodSeconds: 3
        timeoutSeconds: 2
    replicas: 1
    resources:
      limits:
        cpu: "250m"
        memory: "128Mi"
      requests:
        cpu: "10m"
        memory: "16Mi"
    strategy:
      type: "RollingUpdate"
    workloadType: "Deployment"
