---
# Source: kuberploy-helm-fixture/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-config
  namespace: kp-rc345-qualification-dev
  labels:
    app.kubernetes.io/instance: helm
    app.kubernetes.io/name: helm
    kuberploy.io/application: "012dc522-6c4f-4150-8574-4d24d81fa074"
    kuberploy.io/environment: "00f171dd-1bf2-4dba-b173-9304ba56f3b3"
    kuberploy.io/project: "d329f441-87c5-4a54-a00a-be01316f64af"
  annotations:
    qualification.kuberploy.io/sensitive-token: "rc355g-oci-a-sensitive"
data:
  MESSAGE: "rc355g-oci-a-message"

---
# Source: kuberploy-helm-fixture/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm
  namespace: kp-rc345-qualification-dev
  labels:
    app.kubernetes.io/instance: helm
    app.kubernetes.io/name: helm
    kuberploy.io/application: "012dc522-6c4f-4150-8574-4d24d81fa074"
    kuberploy.io/environment: "00f171dd-1bf2-4dba-b173-9304ba56f3b3"
    kuberploy.io/project: "d329f441-87c5-4a54-a00a-be01316f64af"
spec:
  replicas: 1
  selector:
    matchLabels:
      kuberploy.io/application: "012dc522-6c4f-4150-8574-4d24d81fa074"
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: helm
        app.kubernetes.io/name: helm
        kuberploy.io/application: "012dc522-6c4f-4150-8574-4d24d81fa074"
        kuberploy.io/environment: "00f171dd-1bf2-4dba-b173-9304ba56f3b3"
        kuberploy.io/project: "d329f441-87c5-4a54-a00a-be01316f64af"
    spec:
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: fixture
          image: registry.k8s.io/e2e-test-images/agnhost@sha256:99c6b4bb4a1e1df3f0b3752168c89358794d02258ebebc26bf21c29399011a85
          imagePullPolicy: IfNotPresent
          command: ["/agnhost"]
          args: ["netexec", "--http-port=8080", "--udp-port=-1", "--http-override=/echo?msg=rc355g-oci-a"]
          env:
            - name: QUALIFICATION_VALUE
              value: "rc355g-oci-a-environment"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65532
            runAsGroup: 65532
