apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: kp-h-1fd19adab35540f28eaf983ee5e0c3fe
    namespace: argocd
    finalizers:
        - resources-finalizer.argocd.argoproj.io
    labels:
        app.kubernetes.io/component: approved-helm-application
        app.kubernetes.io/managed-by: kuberploy
        kuberploy.io/application-id: 1fd19ada-b355-40f2-8eaf-983ee5e0c3fe
        kuberploy.io/environment-id: a25667e7-49b6-463f-aa1e-073aa721d3dc
        kuberploy.io/project-id: 0cad340e-9ca7-41a4-915a-803bcb312434
    annotations:
        argocd.argoproj.io/manifest-generate-paths: platform/helm-manifests/environments/a25667e7-49b6-463f-aa1e-073aa721d3dc/applications/1fd19ada-b355-40f2-8eaf-983ee5e0c3fe/revisions/7b239155-ae34-45fe-89c5-dee7097a1789/release.yaml
        kuberploy.io/helm-payload-digest: sha256:8ddc61dd8953375d0f492bfb6f38733f48fe755afe3b0931873800f05890c7c9
        kuberploy.io/helm-payload-revision: ecdf15e5762e4185234ccab4e30ed28731c02c33
        kuberploy.io/helm-release-revision: 7b239155-ae34-45fe-89c5-dee7097a1789
spec:
    project: kp-rc326-qualification-dev
    source:
        repoURL: https://github.com/kuberploy/kuberploy-gitops-test.git
        targetRevision: ecdf15e5762e4185234ccab4e30ed28731c02c33
        path: platform/helm-manifests/environments/a25667e7-49b6-463f-aa1e-073aa721d3dc/applications/1fd19ada-b355-40f2-8eaf-983ee5e0c3fe/revisions/7b239155-ae34-45fe-89c5-dee7097a1789
        directory:
            recurse: false
            include: release.yaml
    destination:
        server: https://kubernetes.default.svc
        namespace: kp-rc326-qualification-dev
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
            allowEmpty: false
        syncOptions:
            - CreateNamespace=false
            - ServerSideApply=true
