apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: kp-h-1fd19adab35540f28eaf983ee5e0c3fe
    namespace: argocd
    finalizers:
        - resources-finalizer.argocd.argoproj.io
    labels:
        app.kubernetes.io/component: approved-helm-application
        app.kubernetes.io/managed-by: kuberploy
        kuberploy.io/application-id: 1fd19ada-b355-40f2-8eaf-983ee5e0c3fe
        kuberploy.io/environment-id: a25667e7-49b6-463f-aa1e-073aa721d3dc
        kuberploy.io/project-id: 0cad340e-9ca7-41a4-915a-803bcb312434
    annotations:
        argocd.argoproj.io/manifest-generate-paths: platform/helm-manifests/environments/a25667e7-49b6-463f-aa1e-073aa721d3dc/applications/1fd19ada-b355-40f2-8eaf-983ee5e0c3fe/revisions/eb083e67-c2f2-440b-886f-9e528da88b89/release.yaml
        kuberploy.io/helm-payload-digest: sha256:2ac6a21606b55990861eb1b426c429544ffebb34d1d8dfb8deb667a12c307cd4
        kuberploy.io/helm-payload-revision: dca051e70d45e12c93ed029de14832162cc360ec
        kuberploy.io/helm-release-revision: eb083e67-c2f2-440b-886f-9e528da88b89
spec:
    project: kp-rc326-qualification-dev
    source:
        repoURL: https://github.com/kuberploy/kuberploy-gitops-test.git
        targetRevision: dca051e70d45e12c93ed029de14832162cc360ec
        path: platform/helm-manifests/environments/a25667e7-49b6-463f-aa1e-073aa721d3dc/applications/1fd19ada-b355-40f2-8eaf-983ee5e0c3fe/revisions/eb083e67-c2f2-440b-886f-9e528da88b89
        directory:
            recurse: false
            include: release.yaml
    destination:
        server: https://kubernetes.default.svc
        namespace: kp-rc326-qualification-dev
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
            allowEmpty: false
        syncOptions:
            - CreateNamespace=false
            - ServerSideApply=true
