apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: kp-h-3b7df5bebdf14b6e86d5adcfe87c3a2d
    namespace: argocd
    finalizers:
        - resources-finalizer.argocd.argoproj.io
    labels:
        app.kubernetes.io/component: approved-helm-application
        app.kubernetes.io/managed-by: kuberploy
        kuberploy.io/application-id: 3b7df5be-bdf1-4b6e-86d5-adcfe87c3a2d
        kuberploy.io/environment-id: aa67ff10-d73f-423c-8e6d-71eda2e1af69
        kuberploy.io/project-id: 42f87499-2630-4641-af0b-95ca21125d45
    annotations:
        argocd.argoproj.io/manifest-generate-paths: platform/helm-manifests/environments/aa67ff10-d73f-423c-8e6d-71eda2e1af69/applications/3b7df5be-bdf1-4b6e-86d5-adcfe87c3a2d/revisions/e0400bdd-6534-4026-a80f-a935444eba29/release.yaml
        kuberploy.io/helm-payload-digest: sha256:308c4cc5d28e7b9c37401f363a99fb46fee3a218d1dd527d01cf81278650c357
        kuberploy.io/helm-payload-revision: fd144faa667a0115186216cd847419e6012a9a48
        kuberploy.io/helm-release-revision: e0400bdd-6534-4026-a80f-a935444eba29
spec:
    project: kp-rc329-qualification-dev
    source:
        repoURL: https://github.com/kuberploy/kuberploy-gitops-test.git
        targetRevision: fd144faa667a0115186216cd847419e6012a9a48
        path: platform/helm-manifests/environments/aa67ff10-d73f-423c-8e6d-71eda2e1af69/applications/3b7df5be-bdf1-4b6e-86d5-adcfe87c3a2d/revisions/e0400bdd-6534-4026-a80f-a935444eba29
        directory:
            recurse: false
            include: release.yaml
    destination:
        server: https://kubernetes.default.svc
        namespace: kp-rc329-qualification-dev
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
            allowEmpty: false
        syncOptions:
            - CreateNamespace=false
            - ServerSideApply=true
