{
  "apiVersion": "config.kuberploy.io/v1alpha1",
  "kind": "AppConfig",
  "metadata": {
    "id": "f38a5d7d-4673-4e72-9199-2d62813179c9",
    "name": "rc382-builder-1787840071"
  },
  "spec": {
    "applicationId": "f38a5d7d-4673-4e72-9199-2d62813179c9",
    "delivery": {
      "mode": "image",
      "registryPull": {
        "profileName": "managed-main",
        "profileRevision": 1,
        "targetId": "f0b03740-c7a9-4ca0-a852-e807c97d2fc8"
      },
      "release": {
        "digest": "sha256:108426d41ce181b31f79f9e49b6bd1379278f3b30fd41fdb81ef7a6646528ce9",
        "repository": "registry.adminchatmate.com/kuberploy-qualification/projects/f2674f0a-afbc-40b4-9286-874de90efdd9/services/f38a5d7d-4673-4e72-9199-2d62813179c9/image"
      }
    },
    "environmentId": "d2ce9611-44b3-41ff-a729-21d8df849084",
    "projectId": "f2674f0a-afbc-40b4-9286-874de90efdd9",
    "runtime": {
      "ports": [
        {
          "containerPort": 8080,
          "name": "http",
          "protocol": "TCP"
        }
      ],
      "replicas": 1,
      "resources": {
        "requests": {
          "cpu": "50m",
          "memory": "100Mi"
        }
      },
      "strategy": {
        "type": "RollingUpdate"
      },
      "workloadType": "Deployment"
    }
  }
}
