apiVersion: config.kuberploy.io/v1alpha1
kind: AppConfig
metadata:
  id: "ab1ba4fe-2949-4030-8eef-7a1759562f59"
  name: "oci"
spec:
  projectId: "9ed18608-909c-4577-9d67-0e890db8e079"
  applicationId: "ab1ba4fe-2949-4030-8eef-7a1759562f59"
  environmentId: "afc476f7-9098-49ae-97c7-dec39714ebec"
  delivery:
    mode: image
    release:
      repository: "docker.io/library/nginx"
      digest: "sha256:5616878291a2eed594aee8db4dade5878cf7edcb475e59193904b198d9b830de"
  runtime:
    ports:
      -
        containerPort: 80
        name: "http"
        protocol: "TCP"
        servicePort: 80
    replicas: 1
    resources:
      limits:
        cpu: "250m"
        memory: "128Mi"
      requests:
        cpu: "25m"
        memory: "32Mi"
    strategy:
      type: "RollingUpdate"
    workloadType: "Deployment"
  routes:
    - id: route-7dd95c811e
      host: "app-staging.adminchatmate.com"
      path: "/"
      ingressClassName: "traefik"
      port: "http"
      tls:
        mode: httpOnly
