apiVersion: config.kuberploy.io/v1alpha1
kind: AppConfig
metadata:
  id: "456bb933-cf4f-40ad-807c-615bf6ffb70a"
  name: "private-oci"
spec:
  projectId: "0d60a002-4fe1-4a15-9a7a-4ffc08cdb17a"
  applicationId: "456bb933-cf4f-40ad-807c-615bf6ffb70a"
  environmentId: "cdb01c3c-6925-4da8-8c7d-9942431a428e"
  delivery:
    mode: image
    release:
      repository: "registry.k8s.io/e2e-test-images/agnhost"
      digest: "sha256:1c5d47ecd9c4fca235ec0eeb9af0c39d8dd981ae703805a1f23676a9bf47c3bb"
  runtime:
    args:
      - "netexec"
      - "--http-port=8080"
    command:
      - "/agnhost"
    ports:
      -
        containerPort: 8080
        name: "http"
        protocol: "TCP"
        servicePort: 80
    probes:
      readiness:
        httpGet:
          path: "/hostname"
          port: "http"
        periodSeconds: 3
    replicas: 1
    resources:
      limits:
        cpu: "100m"
        memory: "128Mi"
      requests:
        cpu: "10m"
        memory: "32Mi"
    strategy:
      type: "RollingUpdate"
    workloadType: "Deployment"
