{
  "apiVersion": "config.kuberploy.io/v1alpha1",
  "kind": "AppConfig",
  "metadata": {
    "id": "4d77abd0-fdd6-4798-8433-021a691197ee",
    "name": "web"
  },
  "spec": {
    "applicationId": "4d77abd0-fdd6-4798-8433-021a691197ee",
    "delivery": {
      "mode": "image",
      "registryPull": {
        "profileName": "managed-main",
        "profileRevision": 1,
        "targetId": "f0b03740-c7a9-4ca0-a852-e807c97d2fc8"
      },
      "release": {
        "digest": "sha256:e3e6fcfac7be43e47941edf1bf52504cb65979965f45fff9d8b8d42792acddfa",
        "repository": "registry.adminchatmate.com/kuberploy-qualification/projects/ea186ebb-acbf-49b4-b8b5-54a02c5080a6/services/4d77abd0-fdd6-4798-8433-021a691197ee/image"
      }
    },
    "environmentId": "5d7af687-f604-4bd2-a39f-420a9dbb5622",
    "projectId": "ea186ebb-acbf-49b4-b8b5-54a02c5080a6",
    "runtime": {
      "ports": [
        {
          "containerPort": 8080,
          "name": "http",
          "protocol": "TCP",
          "servicePort": 80
        }
      ],
      "probes": {
        "liveness": {
          "failureThreshold": 3,
          "httpGet": {
            "path": "/",
            "port": "http",
            "scheme": "HTTP"
          },
          "periodSeconds": 10,
          "timeoutSeconds": 2
        },
        "readiness": {
          "failureThreshold": 3,
          "httpGet": {
            "path": "/",
            "port": "http",
            "scheme": "HTTP"
          },
          "periodSeconds": 3,
          "timeoutSeconds": 2
        },
        "startup": {
          "failureThreshold": 30,
          "periodSeconds": 2,
          "tcpSocket": {
            "port": "http"
          },
          "timeoutSeconds": 1
        }
      },
      "replicas": 1,
      "resources": {
        "limits": {
          "cpu": "100m",
          "memory": "64Mi"
        },
        "requests": {
          "cpu": "10m",
          "memory": "16Mi"
        }
      },
      "strategy": {
        "type": "RollingUpdate"
      },
      "workloadType": "Deployment"
    }
  }
}
