apiVersion: config.kuberploy.io/v1alpha1
kind: AppConfig
metadata:
  id: "712cc88c-09c8-4196-bfa5-431a0af5b6a4"
  name: "rc414-public-oci-20260904051054"
spec:
  projectId: "a2f5afcc-239b-47e6-8cbd-d0de07670fbe"
  applicationId: "712cc88c-09c8-4196-bfa5-431a0af5b6a4"
  environmentId: "1d1cff85-636d-43cf-a6cf-289b0f430080"
  delivery:
    mode: image
    release:
      repository: "registry.k8s.io/e2e-test-images/agnhost"
      digest: "sha256:99c6b4bb4a1e1df3f0b3752168c89358794d02258ebebc26bf21c29399011a85"
  runtime:
    args:
      - "netexec"
      - "--http-port=8080"
      - "--udp-port=-1"
    command:
      - "/agnhost"
    env:
      -
        name: "RC414_RUNTIME"
        value: "changed"
    ports:
      -
        containerPort: 8080
        name: "http"
        protocol: "TCP"
        servicePort: 80
    probes:
      liveness:
        failureThreshold: 3
        httpGet:
          path: "/echo?msg=live"
          port: "http"
          scheme: "HTTP"
        periodSeconds: 10
        timeoutSeconds: 2
      readiness:
        failureThreshold: 3
        httpGet:
          path: "/echo?msg=ready"
          port: "http"
          scheme: "HTTP"
        periodSeconds: 3
        timeoutSeconds: 2
      startup:
        failureThreshold: 30
        periodSeconds: 2
        tcpSocket:
          port: "http"
        timeoutSeconds: 1
    replicas: 2
    resources:
      limits:
        cpu: "100m"
        memory: "64Mi"
      requests:
        cpu: "10m"
        memory: "16Mi"
    strategy:
      type: "RollingUpdate"
    terminationGracePeriodSeconds: 20
    workingDirectory: "/"
    workloadType: "Deployment"
