{
  "apiVersion": "config.kuberploy.io/v1alpha1",
  "kind": "AppConfig",
  "metadata": {
    "id": "84bdcc5f-f2ab-40c5-a561-203ec3c4bfed",
    "name": "github"
  },
  "spec": {
    "applicationId": "84bdcc5f-f2ab-40c5-a561-203ec3c4bfed",
    "delivery": {
      "mode": "image",
      "registryPull": {
        "profileName": "managed-main",
        "profileRevision": 1,
        "targetId": "f0b03740-c7a9-4ca0-a852-e807c97d2fc8"
      },
      "release": {
        "digest": "sha256:959b2ae20fb4aa3cb02035ab08b509f0c7a25521be953b1f05070dbd70c29714",
        "repository": "registry.adminchatmate.com/kuberploy-qualification/projects/b4cb68a3-0ce7-40e4-96a4-61cf471a6989/services/84bdcc5f-f2ab-40c5-a561-203ec3c4bfed/image"
      }
    },
    "environmentId": "4e4e15b2-719d-4e92-a18f-598f86162373",
    "projectId": "b4cb68a3-0ce7-40e4-96a4-61cf471a6989",
    "runtime": {
      "ports": [
        {
          "containerPort": 8080,
          "name": "http",
          "protocol": "TCP",
          "servicePort": 80
        }
      ],
      "probes": {
        "liveness": {
          "failureThreshold": 3,
          "httpGet": {
            "path": "/",
            "port": "http",
            "scheme": "HTTP"
          },
          "periodSeconds": 10,
          "timeoutSeconds": 2
        },
        "readiness": {
          "failureThreshold": 3,
          "httpGet": {
            "path": "/",
            "port": "http",
            "scheme": "HTTP"
          },
          "periodSeconds": 3,
          "timeoutSeconds": 2
        }
      },
      "replicas": 1,
      "resources": {
        "limits": {
          "cpu": "250m",
          "memory": "128Mi"
        },
        "requests": {
          "cpu": "10m",
          "memory": "16Mi"
        }
      },
      "strategy": {
        "type": "RollingUpdate"
      },
      "workloadType": "Deployment"
    }
  }
}
