apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: kp-h-012dc5226c4f415085744d24d81fa074
    namespace: argocd
    finalizers:
        - resources-finalizer.argocd.argoproj.io
    labels:
        app.kubernetes.io/component: approved-helm-application
        app.kubernetes.io/managed-by: kuberploy
        kuberploy.io/application-id: 012dc522-6c4f-4150-8574-4d24d81fa074
        kuberploy.io/environment-id: 00f171dd-1bf2-4dba-b173-9304ba56f3b3
        kuberploy.io/project-id: d329f441-87c5-4a54-a00a-be01316f64af
    annotations:
        argocd.argoproj.io/manifest-generate-paths: platform/helm-manifests/environments/00f171dd-1bf2-4dba-b173-9304ba56f3b3/applications/012dc522-6c4f-4150-8574-4d24d81fa074/revisions/f5eb8ab9-abc5-4ae5-9e5e-5a20f1fcf00c/release.yaml
        kuberploy.io/helm-payload-digest: sha256:b47bcd1b6ab3de48c2cd71c7537b1af47b740b5d37e9297401c7ef36c7aedcfc
        kuberploy.io/helm-payload-revision: f3d9e33b4305953eb60b3c15cca289eb5a3de361
        kuberploy.io/helm-release-revision: f5eb8ab9-abc5-4ae5-9e5e-5a20f1fcf00c
spec:
    project: kp-rc345-qualification-dev
    source:
        repoURL: https://github.com/kuberploy/kuberploy-gitops-test.git
        targetRevision: f3d9e33b4305953eb60b3c15cca289eb5a3de361
        path: platform/helm-manifests/environments/00f171dd-1bf2-4dba-b173-9304ba56f3b3/applications/012dc522-6c4f-4150-8574-4d24d81fa074/revisions/f5eb8ab9-abc5-4ae5-9e5e-5a20f1fcf00c
        directory:
            recurse: false
            include: release.yaml
    destination:
        server: https://kubernetes.default.svc
        namespace: kp-rc345-qualification-dev
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
            allowEmpty: false
        syncOptions:
            - CreateNamespace=false
            - ServerSideApply=true
