apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: kp-h-012dc5226c4f415085744d24d81fa074
    namespace: argocd
    finalizers:
        - resources-finalizer.argocd.argoproj.io
    labels:
        app.kubernetes.io/component: approved-helm-application
        app.kubernetes.io/managed-by: kuberploy
        kuberploy.io/application-id: 012dc522-6c4f-4150-8574-4d24d81fa074
        kuberploy.io/environment-id: 00f171dd-1bf2-4dba-b173-9304ba56f3b3
        kuberploy.io/project-id: d329f441-87c5-4a54-a00a-be01316f64af
    annotations:
        argocd.argoproj.io/manifest-generate-paths: platform/helm-manifests/environments/00f171dd-1bf2-4dba-b173-9304ba56f3b3/applications/012dc522-6c4f-4150-8574-4d24d81fa074/revisions/5b3f3f37-a0a7-4b49-9f1f-19cea852abe9/release.yaml
        kuberploy.io/helm-payload-digest: sha256:7e90b2fa22fca050ae89f77d5d5a7849fb2d1df4666da0f03036e4c6d4797f58
        kuberploy.io/helm-payload-revision: a668b3b40bccf8acbaf86d41f47c5e5a86f629b1
        kuberploy.io/helm-release-revision: 5b3f3f37-a0a7-4b49-9f1f-19cea852abe9
spec:
    project: kp-rc345-qualification-dev
    source:
        repoURL: https://github.com/kuberploy/kuberploy-gitops-test.git
        targetRevision: a668b3b40bccf8acbaf86d41f47c5e5a86f629b1
        path: platform/helm-manifests/environments/00f171dd-1bf2-4dba-b173-9304ba56f3b3/applications/012dc522-6c4f-4150-8574-4d24d81fa074/revisions/5b3f3f37-a0a7-4b49-9f1f-19cea852abe9
        directory:
            recurse: false
            include: release.yaml
    destination:
        server: https://kubernetes.default.svc
        namespace: kp-rc345-qualification-dev
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
            allowEmpty: false
        syncOptions:
            - CreateNamespace=false
            - ServerSideApply=true
