apiVersion: config.kuberploy.io/v1alpha1
kind: AppConfig
metadata:
  id: "f6b25925-da05-431c-b2d9-3f3de8cbccae"
  name: "web"
spec:
  projectId: "4f12a4da-f574-40d3-ad03-4eb4c9fe3ce6"
  applicationId: "f6b25925-da05-431c-b2d9-3f3de8cbccae"
  environmentId: "42baeafd-888c-4db3-b9c3-b7e2f9311ffe"
  delivery:
    mode: image
    registryPull:
      targetId: "f0b03740-c7a9-4ca0-a852-e807c97d2fc8"
      profileName: "managed-main"
      profileRevision: 1
    release:
      repository: "registry.adminchatmate.com/kuberploy-qualification/projects/4f12a4da-f574-40d3-ad03-4eb4c9fe3ce6/services/f6b25925-da05-431c-b2d9-3f3de8cbccae/image"
      digest: "sha256:0c9d580bde94b957cd033fe5ea8dfad43311a5f7fcfd7069568408874fa48024"
  runtime:
    ports:
      - containerPort: 8080
        name: "http"
        protocol: "TCP"
        servicePort: 80
    probes:
      liveness:
        failureThreshold: 3
        httpGet:
          path: "/"
          port: "http"
          scheme: "HTTP"
        periodSeconds: 10
        timeoutSeconds: 2
      readiness:
        failureThreshold: 3
        httpGet:
          path: "/"
          port: "http"
          scheme: "HTTP"
        periodSeconds: 3
        timeoutSeconds: 2
      startup:
        failureThreshold: 30
        periodSeconds: 2
        tcpSocket:
          port: "http"
        timeoutSeconds: 1
    replicas: 1
    resources:
      limits:
        cpu: "100m"
        memory: "64Mi"
      requests:
        cpu: "10m"
        memory: "16Mi"
    strategy:
      type: "RollingUpdate"
    workloadType: "Deployment"
    env:
      - name: RC402_RUNTIME_SECRET
        valueFrom:
          secretBindingRef:
            bindingId: 08563ce2-e295-4352-bbe4-5654202e6dcd
            name: rc402-runtime-cb5b3fbf
            key: apiKey
            version: 2
  overrides:
    deployment:
      metadata:
        annotations:
          qualification.kuberploy.io/deployment: rc413
      spec:
        revisionHistoryLimit: 7
    service:
      metadata:
        annotations:
          qualification.kuberploy.io/service: rc413
      spec:
        sessionAffinity: None
    ingress:
      metadata:
        annotations:
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          external-dns.alpha.kubernetes.io/target: 103.117.151.86
          qualification.kuberploy.io/ingress: rc413
    serviceAccount:
      metadata:
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/kuberploy-rc413
  routes:
    - id: qualification
      host: kuberploy-qualification.adminchatmate.com
      path: /
      port: http
      dns:
        mode: manual
      tls:
        mode: customCertificate
        secretRef:
          bindingId: e68deb4d-adce-4db9-9f28-e1d1b3e968ed
          name: rc402-custom-cert-cb5b3fbf
          version: 2
        redirectHttp: true
      middlewareRefs: []
