apiVersion: config.kuberploy.io/v1alpha1
kind: AppConfig
metadata:
  id: "5fdc0ef4-8931-4f4a-8d31-fa006b1c3948"
  name: "oci"
spec:
  projectId: "92c030ae-83a7-4308-87cc-0f3742347ce2"
  applicationId: "5fdc0ef4-8931-4f4a-8d31-fa006b1c3948"
  environmentId: "17edcd5e-f159-4236-8e12-70d484d3c961"
  delivery:
    mode: image
    release:
      repository: "registry.k8s.io/e2e-test-images/agnhost"
      digest: "sha256:99c6b4bb4a1e1df3f0b3752168c89358794d02258ebebc26bf21c29399011a85"
  runtime:
    args:
      - "netexec"
      - "--http-port=8080"
      - "--udp-port=-1"
      - "--http-override=/echo?msg=development"
    command:
      - "/agnhost"
    env:
      -
        name: "RC405_ENVIRONMENT"
        value: "development"
    ports:
      -
        containerPort: 8080
        name: "http"
        protocol: "TCP"
        servicePort: 80
    probes:
      liveness:
        failureThreshold: 3
        httpGet:
          path: "/echo?msg=live"
          port: "http"
          scheme: "HTTP"
        periodSeconds: 10
        timeoutSeconds: 2
      readiness:
        failureThreshold: 3
        httpGet:
          path: "/echo?msg=ready"
          port: "http"
          scheme: "HTTP"
        periodSeconds: 3
        timeoutSeconds: 2
      startup:
        failureThreshold: 30
        periodSeconds: 2
        tcpSocket:
          port: "http"
        timeoutSeconds: 1
    replicas: 1
    resources:
      limits:
        cpu: "100m"
        memory: "64Mi"
      requests:
        cpu: "10m"
        memory: "16Mi"
    strategy:
      type: "RollingUpdate"
    terminationGracePeriodSeconds: 20
    workingDirectory: "/"
    workloadType: "Deployment"
