apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: kp-h-815d24ab3c2f49ada4c5f663c0f372b3
    namespace: argocd
    finalizers:
        - resources-finalizer.argocd.argoproj.io
    labels:
        app.kubernetes.io/component: approved-helm-application
        app.kubernetes.io/managed-by: kuberploy
        kuberploy.io/application-id: 815d24ab-3c2f-49ad-a4c5-f663c0f372b3
        kuberploy.io/environment-id: 7e5dd98e-b429-4cb7-a8b9-3ad92e696c0c
        kuberploy.io/project-id: 7ba1ed2f-8b3f-48ee-87bc-44da0f5a9012
    annotations:
        argocd.argoproj.io/manifest-generate-paths: clusters/22222222-2222-4222-8222-222222222222/helm-manifests/environments/7e5dd98e-b429-4cb7-a8b9-3ad92e696c0c/applications/815d24ab-3c2f-49ad-a4c5-f663c0f372b3/revisions/2237c43a-2ac8-4a9d-b4ff-3ecb024af68f/release.yaml
        kuberploy.io/helm-payload-digest: sha256:28a1b59501c36ef0aaf52d8270cbaf18fe26f79170292dfbc3b93a041bec080c
        kuberploy.io/helm-payload-revision: 00b72658343064289778b3471eaf16e76ccacf1f
        kuberploy.io/helm-release-revision: 2237c43a-2ac8-4a9d-b4ff-3ecb024af68f
spec:
    project: kp-rc159-helm-qualification-oci
    source:
        repoURL: https://github.com/kuberploy/kuberploy-gitops-test.git
        targetRevision: 00b72658343064289778b3471eaf16e76ccacf1f
        path: clusters/22222222-2222-4222-8222-222222222222/helm-manifests/environments/7e5dd98e-b429-4cb7-a8b9-3ad92e696c0c/applications/815d24ab-3c2f-49ad-a4c5-f663c0f372b3/revisions/2237c43a-2ac8-4a9d-b4ff-3ecb024af68f
        directory:
            recurse: false
            include: release.yaml
    destination:
        server: https://kubernetes.default.svc
        namespace: kp-rc159-helm-qualification-oci
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
            allowEmpty: false
        syncOptions:
            - CreateNamespace=false
            - ServerSideApply=true
