apiVersion: config.kuberploy.io/v1alpha1
kind: AppConfig
metadata:
  id: "0a7a9254-d216-464e-870d-059be15b97c2"
  name: "rc372-private-oci-credential"
spec:
  projectId: "6b1da853-0bf9-436a-b9e7-4744f7a3586e"
  applicationId: "0a7a9254-d216-464e-870d-059be15b97c2"
  environmentId: "51fc57b4-c825-4e7c-9f49-7fef2efc83d0"
  delivery:
    mode: image
    registryPull:
      targetId: "f0b03740-c7a9-4ca0-a852-e807c97d2fc8"
      profileName: "managed-main"
      profileRevision: 1
    release:
      repository: "registry.adminchatmate.com/kuberploy-qualification/projects/6b1da853-0bf9-436a-b9e7-4744f7a3586e/services/0a7a9254-d216-464e-870d-059be15b97c2/image"
      digest: "sha256:9d1239da767bb6a63e030015696cd40ca69fd40335b16d735d60d29912b38283"
  runtime:
    ports:
      -
        containerPort: 8080
        name: "http"
        protocol: "TCP"
    replicas: 1
    resources:
      limits:
        cpu: "250m"
        memory: "128Mi"
      requests:
        cpu: "25m"
        memory: "32Mi"
    strategy:
      type: "RollingUpdate"
    workloadType: "Deployment"
