{
  "apiVersion": "config.kuberploy.io/v1alpha1",
  "kind": "AppConfig",
  "metadata": {
    "id": "0455af5d-8b3d-4463-b5f3-7251aa0399e7",
    "name": "web"
  },
  "spec": {
    "applicationId": "0455af5d-8b3d-4463-b5f3-7251aa0399e7",
    "delivery": {
      "mode": "image",
      "registryPull": {
        "profileName": "managed-main",
        "profileRevision": 1,
        "targetId": "f0b03740-c7a9-4ca0-a852-e807c97d2fc8"
      },
      "release": {
        "digest": "sha256:c43c92c47ee0b5dfb40391ba1436238c8a16a72dcea5d034cfa628d9dc37e5f0",
        "repository": "registry.adminchatmate.com/kuberploy-qualification/projects/f9952bf0-7bd7-4528-9d33-1511005db8a2/services/0455af5d-8b3d-4463-b5f3-7251aa0399e7/image"
      }
    },
    "environmentId": "83b9ed83-e516-426c-94e3-7231f3d5ec12",
    "projectId": "f9952bf0-7bd7-4528-9d33-1511005db8a2",
    "runtime": {
      "ports": [
        {
          "containerPort": 8080,
          "name": "http",
          "protocol": "TCP",
          "servicePort": 80
        }
      ],
      "probes": {
        "liveness": {
          "failureThreshold": 3,
          "httpGet": {
            "path": "/",
            "port": "http",
            "scheme": "HTTP"
          },
          "periodSeconds": 10,
          "timeoutSeconds": 2
        },
        "readiness": {
          "failureThreshold": 3,
          "httpGet": {
            "path": "/",
            "port": "http",
            "scheme": "HTTP"
          },
          "periodSeconds": 3,
          "timeoutSeconds": 2
        },
        "startup": {
          "failureThreshold": 30,
          "periodSeconds": 2,
          "tcpSocket": {
            "port": "http"
          },
          "timeoutSeconds": 1
        }
      },
      "replicas": 2,
      "resources": {
        "limits": {
          "cpu": "100m",
          "memory": "64Mi"
        },
        "requests": {
          "cpu": "10m",
          "memory": "16Mi"
        }
      },
      "strategy": {
        "type": "RollingUpdate"
      },
      "workloadType": "Deployment"
    }
  }
}
