apiVersion: config.kuberploy.io/v1alpha1
kind: AppConfig
metadata:
  id: "11135d2e-773b-4c50-beda-235fea4400ac"
  name: "retained-oci"
spec:
  projectId: "18290bc7-6ebd-4f92-b306-afe45361532c"
  applicationId: "11135d2e-773b-4c50-beda-235fea4400ac"
  environmentId: "451440df-e985-4478-a3fd-18592bcd49b8"
  delivery:
    mode: image
    release:
      repository: "registry.k8s.io/e2e-test-images/agnhost"
      digest: "sha256:99c6b4bb4a1e1df3f0b3752168c89358794d02258ebebc26bf21c29399011a85"
  runtime:
    args:
      - "netexec"
      - "--http-port=8080"
      - "--udp-port=-1"
    command:
      - "/agnhost"
    ports:
      - containerPort: 8080
        name: "http"
        protocol: "TCP"
        servicePort: 80
    probes:
      readiness:
        failureThreshold: 3
        httpGet:
          path: "/echo?msg=ready"
          port: "http"
          scheme: "HTTP"
        periodSeconds: 3
        timeoutSeconds: 2
    replicas: 1
    resources:
      limits:
        cpu: "100m"
        memory: "64Mi"
      requests:
        cpu: "10m"
        memory: "16Mi"
    strategy:
      type: "RollingUpdate"
    workloadType: "Deployment"
    env:
      - name: RC402_RUNTIME_SECRET
        valueFrom:
          secretBindingRef:
            bindingId: 8e36c34e-4df7-48fa-aac6-df356747f18f
            name: rc402-runtime-fd06f9f0
            key: apiKey
            version: 2
  routes:
    - id: qualification
      host: kuberploy-qualification.adminchatmate.com
      path: /
      port: http
      dns:
        mode: manual
      tls:
        mode: customCertificate
        secretRef:
          bindingId: f2d4bf80-5ab1-46c6-93e5-874c1a96075d
          name: rc402-custom-cert-fd06f9f0
          version: 2
        redirectHttp: true
      middlewareRefs: []
