apiVersion: config.kuberploy.io/v1alpha1
kind: AppConfig
metadata:
  id: "11135d2e-773b-4c50-beda-235fea4400ac"
  name: "retained-oci"
spec:
  projectId: "18290bc7-6ebd-4f92-b306-afe45361532c"
  applicationId: "11135d2e-773b-4c50-beda-235fea4400ac"
  environmentId: "451440df-e985-4478-a3fd-18592bcd49b8"
  delivery:
    mode: image
    release:
      repository: "registry.k8s.io/e2e-test-images/agnhost"
      digest: "sha256:99c6b4bb4a1e1df3f0b3752168c89358794d02258ebebc26bf21c29399011a85"
  runtime:
    args:
      - "netexec"
      - "--http-port=8080"
      - "--udp-port=-1"
    command:
      - "/agnhost"
    ports:
      - containerPort: 8080
        name: "http"
        protocol: "TCP"
        servicePort: 80
    probes:
      readiness:
        failureThreshold: 3
        httpGet:
          path: "/echo?msg=ready"
          port: "http"
          scheme: "HTTP"
        periodSeconds: 3
        timeoutSeconds: 2
    replicas: 1
    resources:
      limits:
        cpu: "100m"
        memory: "64Mi"
      requests:
        cpu: "10m"
        memory: "16Mi"
    strategy:
      type: "RollingUpdate"
    workloadType: "Deployment"
  overrides:
    deployment:
      metadata:
        annotations:
          qualification.kuberploy.io/deployment: rc404
      spec:
        revisionHistoryLimit: 7
    service:
      metadata:
        annotations:
          qualification.kuberploy.io/service: rc404
      spec:
        sessionAffinity: None
    ingress:
      metadata:
        annotations:
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          external-dns.alpha.kubernetes.io/target: 103.117.151.86
          qualification.kuberploy.io/ingress: rc404
    serviceAccount:
      metadata:
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/kuberploy-rc404
  routes:
    - id: public
      host: kuberploy-qualification.adminchatmate.com
      path: /
      port: http
      ingressClassName: traefik
      dns:
        mode: externalDns
        integrationRef: kuberploy-cloudflare
        ttl: 60
      tls:
        mode: letsencrypt
        issuerRef: kuberploy-http01-production
        redirectHttp: true
