apiVersion: config.kuberploy.io/v1alpha1
kind: AppConfig
metadata:
  id: "3d9d17eb-3b9b-40f7-9925-27c43911cc66"
  name: "http-probe"
spec:
  projectId: "123b5c0d-f472-4f7f-ae7a-19438db4391f"
  applicationId: "3d9d17eb-3b9b-40f7-9925-27c43911cc66"
  environmentId: "77b798aa-9013-4ae7-b1e0-b2fa6566709e"
  delivery:
    mode: image
    release:
      repository: "docker.io/library/busybox"
      digest: "sha256:9db7b59979c38555a39def84a31fb98b5296952f9e3afd4f6f11f05b07adfab0"
  runtime:
    args:
      - "mkdir -p /tmp/www && printf rc149-qualified > /tmp/www/index.html && exec httpd -f -p 8080 -h /tmp/www"
    command:
      - "/bin/sh"
      - "-c"
    ports:
      -
        containerPort: 8080
        name: "http"
        protocol: "TCP"
        servicePort: 8080
    replicas: 1
    resources:
      limits:
        cpu: "100m"
        memory: "64Mi"
      requests:
        cpu: "25m"
        memory: "32Mi"
    strategy:
      type: "RollingUpdate"
  routes:
    - id: route-f2ee65250e
      host: "kp-31b1dba8d6961ac55bbf.103-117-151-86.sslip.io"
      path: "/"
      ingressClassName: "traefik"
      port: "http"
      dns:
        mode: sslip
      tls:
        mode: httpOnly
