apiVersion: config.kuberploy.io/v1alpha1
kind: AppConfig
metadata:
  id: "8dfb20ef-747f-43c1-84a0-84f4a2587692"
  name: "rc394-oci-lifecycle"
spec:
  projectId: "6b1da853-0bf9-436a-b9e7-4744f7a3586e"
  applicationId: "8dfb20ef-747f-43c1-84a0-84f4a2587692"
  environmentId: "51fc57b4-c825-4e7c-9f49-7fef2efc83d0"
  delivery:
    mode: image
    release:
      repository: "registry.k8s.io/e2e-test-images/agnhost"
      digest: "sha256:99c6b4bb4a1e1df3f0b3752168c89358794d02258ebebc26bf21c29399011a85"
  runtime:
    args:
      - "netexec"
      - "--http-port=8080"
      - "--udp-port=-1"
      - "--http-override=/echo?msg=development"
    command:
      - "/agnhost"
    env:
      -
        name: "RC394_ENVIRONMENT"
        value: "development"
    ports:
      -
        containerPort: 8080
        name: "http"
        protocol: "TCP"
        servicePort: 80
    probes:
      liveness:
        failureThreshold: 3
        httpGet:
          path: "/echo?msg=live"
          port: "http"
          scheme: "HTTP"
        periodSeconds: 10
        timeoutSeconds: 2
      readiness:
        failureThreshold: 3
        httpGet:
          path: "/echo?msg=ready"
          port: "http"
          scheme: "HTTP"
        periodSeconds: 3
        timeoutSeconds: 2
      startup:
        failureThreshold: 30
        periodSeconds: 2
        tcpSocket:
          port: "http"
        timeoutSeconds: 1
    replicas: 1
    resources:
      limits:
        cpu: "100m"
        memory: "64Mi"
      requests:
        cpu: "10m"
        memory: "16Mi"
    strategy:
      type: "RollingUpdate"
    terminationGracePeriodSeconds: 20
    workingDirectory: "/"
    workloadType: "Deployment"
