apiVersion: config.kuberploy.io/v1alpha1
kind: AppConfig
metadata:
  id: "aed83666-d7d5-4ad8-97cf-dbe197d77872"
  name: "ssh"
spec:
  projectId: "b4cb68a3-0ce7-40e4-96a4-61cf471a6989"
  applicationId: "aed83666-d7d5-4ad8-97cf-dbe197d77872"
  environmentId: "4e4e15b2-719d-4e92-a18f-598f86162373"
  delivery:
    mode: image
    registryPull:
      targetId: "f0b03740-c7a9-4ca0-a852-e807c97d2fc8"
      profileName: "managed-main"
      profileRevision: 1
    release:
      repository: "registry.adminchatmate.com/kuberploy-qualification/projects/b4cb68a3-0ce7-40e4-96a4-61cf471a6989/services/aed83666-d7d5-4ad8-97cf-dbe197d77872/image"
      digest: "sha256:dec2b619d32386d1e9f3d37ec501cce1bf418590820bdaf44266659b48fae863"
  runtime:
    ports:
      -
        containerPort: 8080
        name: "http"
        protocol: "TCP"
        servicePort: 80
    probes:
      liveness:
        failureThreshold: 3
        httpGet:
          path: "/"
          port: "http"
          scheme: "HTTP"
        periodSeconds: 10
        timeoutSeconds: 2
      readiness:
        failureThreshold: 3
        httpGet:
          path: "/"
          port: "http"
          scheme: "HTTP"
        periodSeconds: 3
        timeoutSeconds: 2
    replicas: 1
    resources:
      limits:
        cpu: "250m"
        memory: "128Mi"
      requests:
        cpu: "10m"
        memory: "16Mi"
    strategy:
      type: "RollingUpdate"
    workloadType: "Deployment"
