---
# Source: kuberploy-safe/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: helm
  namespace: kp-rc316-qualification-dev
  labels:
    app.kubernetes.io/instance: "helm"
    app.kubernetes.io/name: "helm"
    kuberploy.io/application: "3aee300a-7393-4df3-ba94-382dfa4014a6"
    kuberploy.io/environment: "bdf8c6f7-9566-4381-849d-c12136e16e97"
    kuberploy.io/project: "4400424f-820d-43bb-ae26-f397af3e4d62"
data:
  replicas: "2"
