apiVersion: config.kuberploy.io/v1alpha1
kind: AppConfig
metadata:
  id: "f6d71f8e-099e-4554-97ab-9af9a1b48b9e"
  name: "rc414-gitssh-app-b33c010f"
spec:
  projectId: "3da1a56f-b0fd-4b0f-b046-e710e3536fc0"
  applicationId: "f6d71f8e-099e-4554-97ab-9af9a1b48b9e"
  environmentId: "31f2780d-4609-4cb4-97ad-c758595f18b1"
  delivery:
    mode: image
    registryPull:
      targetId: "f0b03740-c7a9-4ca0-a852-e807c97d2fc8"
      profileName: "managed-main"
      profileRevision: 1
    release:
      repository: "registry.adminchatmate.com/kuberploy-qualification/projects/3da1a56f-b0fd-4b0f-b046-e710e3536fc0/services/f6d71f8e-099e-4554-97ab-9af9a1b48b9e/image"
      digest: "sha256:11b671248fc58f3834d767e1840f66d97b1f5508a8bcd2a574f1469e7e5c448f"
  runtime:
    ports:
      -
        containerPort: 8080
        name: "http"
        protocol: "TCP"
        servicePort: 80
    probes:
      liveness:
        failureThreshold: 3
        httpGet:
          path: "/"
          port: "http"
          scheme: "HTTP"
        periodSeconds: 10
        timeoutSeconds: 2
      readiness:
        failureThreshold: 3
        httpGet:
          path: "/"
          port: "http"
          scheme: "HTTP"
        periodSeconds: 3
        timeoutSeconds: 2
    replicas: 1
    resources:
      limits:
        cpu: "250m"
        memory: "128Mi"
      requests:
        cpu: "10m"
        memory: "16Mi"
    strategy:
      type: "RollingUpdate"
    workloadType: "Deployment"
