apiVersion: config.kuberploy.io/v1alpha1
kind: AppConfig
metadata:
  id: "df689141-1b1d-4e81-97b4-b4b1a639f2c2"
  name: "web-probe"
spec:
  projectId: "123b5c0d-f472-4f7f-ae7a-19438db4391f"
  applicationId: "df689141-1b1d-4e81-97b4-b4b1a639f2c2"
  environmentId: "77b798aa-9013-4ae7-b1e0-b2fa6566709e"
  delivery:
    mode: image
    release:
      repository: "docker.io/library/nginx"
      digest: "sha256:97d490c12ba55b4946b01546d1c3ed324e8d41ab1c9fcb2a616aa470620e5b46"
  runtime:
    ports:
      -
        containerPort: 80
        name: "http"
        protocol: "TCP"
        servicePort: 80
    replicas: 1
    resources:
      limits:
        cpu: "200m"
        memory: "128Mi"
      requests:
        cpu: "50m"
        memory: "64Mi"
    strategy:
      type: "RollingUpdate"
  routes:
    - id: route-bce1180b1d
      host: "kp-fb7b18bb4049d33c73b5.103-117-151-86.sslip.io"
      path: "/"
      ingressClassName: "traefik"
      port: "http"
      dns:
        mode: sslip
      tls:
        mode: httpOnly
