apiVersion: config.kuberploy.io/v1alpha1
kind: AppConfig
metadata:
  id: "c9f4bad1-4d6c-4ee0-9660-823edce70b39"
  name: "oci"
spec:
  projectId: "b87693b1-4925-4049-9814-cf768bac0dd3"
  applicationId: "c9f4bad1-4d6c-4ee0-9660-823edce70b39"
  environmentId: "d7ba656e-bad2-4f16-8251-b729dee55894"
  delivery:
    mode: image
    release:
      repository: "ghcr.io/stefanprodan/podinfo"
      digest: "sha256:10af81c9659824cecaa7fe09134c6c318136341b4ae84c4a37f18d9bd8a33eac"
  runtime:
    ports:
      - containerPort: 9898
        name: "http"
        protocol: "TCP"
        servicePort: 80
    probes:
      liveness:
        failureThreshold: 3
        httpGet:
          path: "/healthz"
          port: "http"
          scheme: "HTTP"
        periodSeconds: 10
      readiness:
        failureThreshold: 6
        httpGet:
          path: "/readyz"
          port: "http"
          scheme: "HTTP"
        periodSeconds: 5
    replicas: 1
    resources:
      limits:
        cpu: "250m"
        memory: "128Mi"
      requests:
        cpu: "25m"
        memory: "32Mi"
    strategy:
      type: "RollingUpdate"
    workloadType: "Deployment"
  overrides:
    deployment:
      metadata:
        annotations:
          qualification.kuberploy.io/deployment: rc372
      spec:
        replicas: 2
        revisionHistoryLimit: 7
    service:
      metadata:
        annotations:
          qualification.kuberploy.io/service: rc372
      spec:
        sessionAffinity: ClientIP
    ingress:
      metadata:
        annotations:
          qualification.kuberploy.io/ingress: rc372
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
    serviceAccount:
      metadata:
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/kuberploy-rc372
  routes:
    - id: public
      host: kuberploy-qualification.adminchatmate.com
      path: /
      port: http
      ingressClassName: traefik
      dns:
        mode: manual
      tls:
        mode: httpOnly
