apiVersion: config.kuberploy.io/v1alpha1
kind: AppConfig
metadata:
  id: "b6f5b6f6-ef2d-4702-b75b-e81dfd2e60ed"
  name: "rc411-oci-e23096a2"
spec:
  projectId: "60c6013f-d38f-4f56-8c5f-a2373cf30f5a"
  applicationId: "b6f5b6f6-ef2d-4702-b75b-e81dfd2e60ed"
  environmentId: "881d0234-2dac-4464-800a-b0539b3e8807"
  delivery:
    mode: image
    release:
      repository: "registry.k8s.io/e2e-test-images/agnhost"
      digest: "sha256:99c6b4bb4a1e1df3f0b3752168c89358794d02258ebebc26bf21c29399011a85"
  runtime:
    args:
      - "netexec"
      - "--http-port=8080"
      - "--udp-port=-1"
      - "--http-override=/echo?msg=development"
    command:
      - "/agnhost"
    env:
      -
        name: "RC411_ENVIRONMENT"
        value: "development"
    ports:
      -
        containerPort: 8080
        name: "http"
        protocol: "TCP"
        servicePort: 80
    probes:
      liveness:
        failureThreshold: 3
        httpGet:
          path: "/echo?msg=live"
          port: "http"
          scheme: "HTTP"
        periodSeconds: 10
        timeoutSeconds: 2
      readiness:
        failureThreshold: 3
        httpGet:
          path: "/echo?msg=ready"
          port: "http"
          scheme: "HTTP"
        periodSeconds: 3
        timeoutSeconds: 2
      startup:
        failureThreshold: 30
        periodSeconds: 2
        tcpSocket:
          port: "http"
        timeoutSeconds: 1
    replicas: 1
    resources:
      limits:
        cpu: "100m"
        memory: "64Mi"
      requests:
        cpu: "10m"
        memory: "16Mi"
    strategy:
      type: "RollingUpdate"
    terminationGracePeriodSeconds: 20
    workingDirectory: "/"
    workloadType: "Deployment"
