---
# Source: kuberploy-helm-fixture/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-config
  namespace: kp-rc329-qualification-dev
  labels:
    app.kubernetes.io/instance: helm
    app.kubernetes.io/name: helm
    kuberploy.io/application: "3b7df5be-bdf1-4b6e-86d5-adcfe87c3a2d"
    kuberploy.io/environment: "aa67ff10-d73f-423c-8e6d-71eda2e1af69"
    kuberploy.io/project: "42f87499-2630-4641-af0b-95ca21125d45"
  annotations:
    qualification.kuberploy.io/sensitive-token: "rc329-sensitive-git"
data:
  MESSAGE: "rc329-git"

---
# Source: kuberploy-helm-fixture/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm
  namespace: kp-rc329-qualification-dev
  labels:
    app.kubernetes.io/instance: helm
    app.kubernetes.io/name: helm
    kuberploy.io/application: "3b7df5be-bdf1-4b6e-86d5-adcfe87c3a2d"
    kuberploy.io/environment: "aa67ff10-d73f-423c-8e6d-71eda2e1af69"
    kuberploy.io/project: "42f87499-2630-4641-af0b-95ca21125d45"
spec:
  replicas: 1
  selector:
    matchLabels:
      kuberploy.io/application: "3b7df5be-bdf1-4b6e-86d5-adcfe87c3a2d"
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: helm
        app.kubernetes.io/name: helm
        kuberploy.io/application: "3b7df5be-bdf1-4b6e-86d5-adcfe87c3a2d"
        kuberploy.io/environment: "aa67ff10-d73f-423c-8e6d-71eda2e1af69"
        kuberploy.io/project: "42f87499-2630-4641-af0b-95ca21125d45"
    spec:
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: fixture
          image: registry.k8s.io/e2e-test-images/agnhost@sha256:99c6b4bb4a1e1df3f0b3752168c89358794d02258ebebc26bf21c29399011a85
          imagePullPolicy: IfNotPresent
          command: ["/agnhost"]
          args: ["netexec", "--http-port=8080", "--udp-port=-1", "--http-override=/echo?msg=rc329"]
          env:
            - name: QUALIFICATION_VALUE
              value: "rc329-environment"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65532
            runAsGroup: 65532
