apiVersion: config.kuberploy.io/v1alpha1
kind: AppConfig
metadata:
  id: "d30f9be6-6fe7-413c-a5e1-6ee755925593"
  name: "web"
spec:
  projectId: "3ef0fb27-fcda-4d54-8a5f-707bdfcb5847"
  applicationId: "d30f9be6-6fe7-413c-a5e1-6ee755925593"
  environmentId: "f9abd9f7-7698-4b94-9465-970b257b3043"
  delivery:
    mode: image
    registryPull:
      targetId: "f0b03740-c7a9-4ca0-a852-e807c97d2fc8"
      profileName: "managed-main"
      profileRevision: 1
    release:
      repository: "registry.adminchatmate.com/kuberploy-qualification/projects/3ef0fb27-fcda-4d54-8a5f-707bdfcb5847/services/d30f9be6-6fe7-413c-a5e1-6ee755925593/image"
      digest: "sha256:b3f31620d00ce925969866cc2ea52c99b5de3971f93e49f9625bf86f5e18e048"
  runtime:
    ports:
      -
        containerPort: 8080
        name: "http"
        protocol: "TCP"
        servicePort: 80
    probes:
      liveness:
        failureThreshold: 3
        httpGet:
          path: "/"
          port: "http"
          scheme: "HTTP"
        periodSeconds: 10
        timeoutSeconds: 2
      readiness:
        failureThreshold: 3
        httpGet:
          path: "/"
          port: "http"
          scheme: "HTTP"
        periodSeconds: 3
        timeoutSeconds: 2
      startup:
        failureThreshold: 30
        periodSeconds: 2
        tcpSocket:
          port: "http"
        timeoutSeconds: 1
    replicas: 1
    resources:
      limits:
        cpu: "100m"
        memory: "64Mi"
      requests:
        cpu: "10m"
        memory: "16Mi"
    strategy:
      type: "RollingUpdate"
    workloadType: "Deployment"

