apiVersion: config.kuberploy.io/v1alpha1
kind: AppConfig
metadata:
  id: "0b3fdcd1-99d9-4da0-9044-eddf4f5cee29"
  name: "rc414-gitssh-project-9cbdbfdd"
spec:
  projectId: "a2f5afcc-239b-47e6-8cbd-d0de07670fbe"
  applicationId: "0b3fdcd1-99d9-4da0-9044-eddf4f5cee29"
  environmentId: "1d1cff85-636d-43cf-a6cf-289b0f430080"
  delivery:
    mode: image
    registryPull:
      targetId: "f0b03740-c7a9-4ca0-a852-e807c97d2fc8"
      profileName: "managed-main"
      profileRevision: 1
    release:
      repository: "registry.adminchatmate.com/kuberploy-qualification/projects/a2f5afcc-239b-47e6-8cbd-d0de07670fbe/services/0b3fdcd1-99d9-4da0-9044-eddf4f5cee29/image"
      digest: "sha256:aadcaaebdabe4e96af097a6bca2dc9f7825c665161a6a1f40def90124a7d7d36"
  runtime:
    ports:
      -
        containerPort: 8080
        name: "http"
        protocol: "TCP"
        servicePort: 80
    probes:
      liveness:
        failureThreshold: 3
        httpGet:
          path: "/"
          port: "http"
          scheme: "HTTP"
        periodSeconds: 10
        timeoutSeconds: 2
      readiness:
        failureThreshold: 3
        httpGet:
          path: "/"
          port: "http"
          scheme: "HTTP"
        periodSeconds: 3
        timeoutSeconds: 2
    replicas: 1
    resources:
      limits:
        cpu: "250m"
        memory: "128Mi"
      requests:
        cpu: "10m"
        memory: "16Mi"
    strategy:
      type: "RollingUpdate"
    workloadType: "Deployment"
