apiVersion: config.kuberploy.io/v1alpha1
kind: AppConfig
metadata:
  id: "aa4570cb-7adb-4b00-bfd1-d3255c6f2d04"
  name: "rc414-gitssh-project-7814bbc4"
spec:
  projectId: "3ef0fb27-fcda-4d54-8a5f-707bdfcb5847"
  applicationId: "aa4570cb-7adb-4b00-bfd1-d3255c6f2d04"
  environmentId: "f9abd9f7-7698-4b94-9465-970b257b3043"
  delivery:
    mode: image
    registryPull:
      targetId: "f0b03740-c7a9-4ca0-a852-e807c97d2fc8"
      profileName: "managed-main"
      profileRevision: 1
    release:
      repository: "registry.adminchatmate.com/kuberploy-qualification/projects/3ef0fb27-fcda-4d54-8a5f-707bdfcb5847/services/aa4570cb-7adb-4b00-bfd1-d3255c6f2d04/image"
      digest: "sha256:4886057059cde37b05b3536cec97286d6b00a148e01b4df5797cc0c4bf446461"
  runtime:
    ports:
      -
        containerPort: 3000
        name: "http"
        protocol: "TCP"
    replicas: 1
    resources:
      requests:
        cpu: "50m"
        memory: "100Mi"
    strategy:
      type: "RollingUpdate"
    workloadType: "Deployment"
