{
  "apiVersion": "config.kuberploy.io/v1alpha1",
  "kind": "AppConfig",
  "metadata": {
    "id": "f3634ff8-ffa5-41cf-b5a6-991567240ba4",
    "name": "demo-service"
  },
  "spec": {
    "applicationId": "f3634ff8-ffa5-41cf-b5a6-991567240ba4",
    "delivery": {
      "mode": "image",
      "release": {
        "digest": "sha256:99c6b4bb4a1e1df3f0b3752168c89358794d02258ebebc26bf21c29399011a85",
        "repository": "registry.k8s.io/e2e-test-images/agnhost"
      }
    },
    "environmentId": "31a3087d-78fa-4ebc-aacd-5f94f304d051",
    "projectId": "a612a75d-a15d-413f-89fe-7d45aa321f48",
    "routes": [],
    "runtime": {
      "args": [
        "netexec",
        "--http-port=8080"
      ],
      "ports": [
        {
          "containerPort": 8080,
          "name": "http",
          "protocol": "TCP",
          "servicePort": 80
        }
      ],
      "replicas": 1,
      "resources": {
        "requests": {
          "cpu": "50m",
          "memory": "100Mi"
        }
      },
      "strategy": {
        "type": "RollingUpdate"
      },
      "workloadType": "Deployment"
    }
  }
}
