apiVersion: config.kuberploy.io/v1alpha1
kind: AppConfig
metadata:
  id: "4a676f9c-35d1-4d80-8dd7-81c50c357335"
  name: "rc411-private-oci-832c170a"
spec:
  projectId: "60c6013f-d38f-4f56-8c5f-a2373cf30f5a"
  applicationId: "4a676f9c-35d1-4d80-8dd7-81c50c357335"
  environmentId: "881d0234-2dac-4464-800a-b0539b3e8807"
  delivery:
    mode: image
    registryPull:
      targetId: "f0b03740-c7a9-4ca0-a852-e807c97d2fc8"
      profileName: "managed-main"
      profileRevision: 1
    release:
      repository: "registry.adminchatmate.com/kuberploy-qualification/projects/60c6013f-d38f-4f56-8c5f-a2373cf30f5a/services/4a676f9c-35d1-4d80-8dd7-81c50c357335/image"
      digest: "sha256:5f1956a16918827fda956c1db094cb74354d85e78287b6b38269205e4f73c7ba"
  runtime:
    ports:
      -
        containerPort: 8080
        name: "http"
        protocol: "TCP"
    replicas: 1
    resources:
      limits:
        cpu: "250m"
        memory: "128Mi"
      requests:
        cpu: "25m"
        memory: "32Mi"
    strategy:
      type: "RollingUpdate"
    workloadType: "Deployment"
