apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
    kuberploy.io/application: {{ .Values.applicationId | quote }}
    kuberploy.io/environment: {{ .Values.environmentId | quote }}
    kuberploy.io/project: {{ .Values.projectId | quote }}
  annotations:
    qualification.kuberploy.io/sensitive-token: {{ .Values.sensitiveAnnotation | quote }}
data:
  MESSAGE: {{ .Values.message | quote }}
