apiVersion: config.kuberploy.io/v1alpha1
kind: AppConfig
metadata:
  id: "b4b0c1a0-668e-4f91-8db1-20c75775891c"
  name: "rc376-web"
spec:
  projectId: "f2674f0a-afbc-40b4-9286-874de90efdd9"
  applicationId: "b4b0c1a0-668e-4f91-8db1-20c75775891c"
  environmentId: "d2ce9611-44b3-41ff-a729-21d8df849084"
  delivery:
    mode: image
    release:
      repository: "docker.io/library/nginx"
      digest: "sha256:42a516af16b852e33b7682d5ef8acbd5d13fe08fecadc7ed98605ba5e3b26ab8"
  runtime:
    env:
      -
        name: "QUALIFICATION"
        value: "rc376"
    ports:
      -
        containerPort: 80
        name: "http"
        protocol: "TCP"
    probes:
      readiness:
        httpGet:
          path: "/"
          port: 80
    replicas: 1
    resources:
      limits:
        cpu: "250m"
        memory: "256Mi"
      requests:
        cpu: "50m"
        memory: "100Mi"
    strategy:
      type: "RollingUpdate"
    workloadType: "Deployment"
