apiVersion: config.kuberploy.io/v1alpha1
kind: AppConfig
metadata:
  id: "4fc8140d-fd07-4d44-9a97-69789c41e03f"
  name: "rc153-valid-image"
spec:
  projectId: "6eddb36b-3b5a-4f88-a8ff-e7ab80110f61"
  applicationId: "4fc8140d-fd07-4d44-9a97-69789c41e03f"
  environmentId: "fb4ce7e7-5d87-4a72-8cab-08c402e48623"
  delivery:
    mode: image
    release:
      repository: "docker.io/library/nginx"
      digest: "sha256:8541484afbc9c8a5a8a99b379568ebbc957f658583ec9448fc43104229c03cf8"
  runtime:
    ports:
      -
        containerPort: 80
        name: "http"
        protocol: "TCP"
    replicas: 1
    resources:
      requests:
        cpu: "25m"
        memory: "32Mi"
    strategy:
      type: "RollingUpdate"
    workloadType: "Deployment"
