apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: "kuberploy-http01-production"
  labels:
    app.kubernetes.io/managed-by: "kuberploy"
    kuberploy.io/certificate-issuer-profile: "kuberploy-http01-production"
  annotations:
    kuberploy.io/certificate-issuer-spec-digest: "sha256:15bf9a6df9c3d8b52a8e055f4abf7f78ce4b61b922b68e682dca5bf35fc3ba89"
    kuberploy.io/certificate-issuer-revision: "1"
spec:
  acme:
    email: "admin@adminchatmate.com"
    server: "https://acme-v02.api.letsencrypt.org/directory"
    privateKeySecretRef:
      name: "kuberploy-http01-production-account"
    solvers:
      - http01:
          ingress:
            ingressClassName: "traefik"
            ingressTemplate:
              metadata:
                annotations:
                  external-dns.alpha.kubernetes.io/exclude: "true"
                  external-dns.alpha.kubernetes.io/ingress-hostname-source: "annotation-only"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "kuberploy-ci-observer-e41d5240f824328fdef2"
  labels:
    app.kubernetes.io/managed-by: "kuberploy"
    kuberploy.io/certificate-issuer-profile: "kuberploy-http01-production"
rules:
  - apiGroups:
      - "cert-manager.io"
    resources:
      - "clusterissuers"
    resourceNames:
      - "kuberploy-http01-production"
    verbs:
      - "get"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "kuberploy-ci-observer-e41d5240f824328fdef2"
  labels:
    app.kubernetes.io/managed-by: "kuberploy"
    kuberploy.io/certificate-issuer-profile: "kuberploy-http01-production"
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: ClusterRole
  name: "kuberploy-ci-observer-e41d5240f824328fdef2"
subjects:
  - kind: ServiceAccount
    name: "kuberploy-worker"
    namespace: "kuberploy-system"
