apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: "rc351f-dns01-staging"
  labels:
    app.kubernetes.io/managed-by: "kuberploy"
    kuberploy.io/certificate-issuer-profile: "rc351f-dns01-staging"
  annotations:
    kuberploy.io/certificate-issuer-spec-digest: "sha256:84d2ee411b197e0104d3511426c22ab15c285bd0479305e15889ae79a4dd87c5"
    kuberploy.io/certificate-issuer-revision: "1"
spec:
  acme:
    email: "admin@adminchatmate.com"
    server: "https://acme-staging-v02.api.letsencrypt.org/directory"
    privateKeySecretRef:
      name: "rc351f-dns01-staging-account"
    solvers:
      - selector:
          dnsZones:
            - "adminchatmate.com"
        dns01:
          cloudflare:
            apiTokenSecretRef:
              name: "rc351f-cloudflare-dns01"
              key: "apiToken"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "kuberploy-ci-observer-34ed4b403471b8874388"
  labels:
    app.kubernetes.io/managed-by: "kuberploy"
    kuberploy.io/certificate-issuer-profile: "rc351f-dns01-staging"
rules:
  - apiGroups:
      - "cert-manager.io"
    resources:
      - "clusterissuers"
    resourceNames:
      - "rc351f-dns01-staging"
    verbs:
      - "get"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "kuberploy-ci-observer-34ed4b403471b8874388"
  labels:
    app.kubernetes.io/managed-by: "kuberploy"
    kuberploy.io/certificate-issuer-profile: "rc351f-dns01-staging"
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: ClusterRole
  name: "kuberploy-ci-observer-34ed4b403471b8874388"
subjects:
  - kind: ServiceAccount
    name: "kuberploy-worker"
    namespace: "kuberploy-system"
