apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: "rc391-http01-production"
  labels:
    app.kubernetes.io/managed-by: "kuberploy"
    kuberploy.io/certificate-issuer-profile: "rc391-http01-production"
  annotations:
    kuberploy.io/certificate-issuer-spec-digest: "sha256:716655c81a10330c1e9bc649aa9f098388abae0f4db5619eb64d980ac63cca11"
    kuberploy.io/certificate-issuer-revision: "1"
spec:
  acme:
    email: "admin@adminchatmate.com"
    server: "https://acme-v02.api.letsencrypt.org/directory"
    privateKeySecretRef:
      name: "rc391-http01-production-account"
    solvers:
      - http01:
          ingress:
            ingressClassName: "traefik"
            ingressTemplate:
              metadata:
                annotations:
                  external-dns.alpha.kubernetes.io/exclude: "true"
                  external-dns.alpha.kubernetes.io/ingress-hostname-source: "annotation-only"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "kuberploy-ci-observer-9c5ec99bc6ead27a93f8"
  labels:
    app.kubernetes.io/managed-by: "kuberploy"
    kuberploy.io/certificate-issuer-profile: "rc391-http01-production"
rules:
  - apiGroups:
      - "cert-manager.io"
    resources:
      - "clusterissuers"
    resourceNames:
      - "rc391-http01-production"
    verbs:
      - "get"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "kuberploy-ci-observer-9c5ec99bc6ead27a93f8"
  labels:
    app.kubernetes.io/managed-by: "kuberploy"
    kuberploy.io/certificate-issuer-profile: "rc391-http01-production"
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: ClusterRole
  name: "kuberploy-ci-observer-9c5ec99bc6ead27a93f8"
subjects:
  - kind: ServiceAccount
    name: "kuberploy-worker"
    namespace: "kuberploy-system"
