apiVersion: config.kuberploy.io/v1alpha1
kind: AppConfig
metadata:
  id: "5c45b120-001c-47f1-a1b5-e4a6cfe7a956"
  name: "rc414-gitssh-app-e567ee9d"
spec:
  projectId: "21a12574-8177-418f-b54e-4b1adc4cc301"
  applicationId: "5c45b120-001c-47f1-a1b5-e4a6cfe7a956"
  environmentId: "c06912f0-5612-4593-b697-0a1cb12beab2"
  delivery:
    mode: image
    registryPull:
      targetId: "f0b03740-c7a9-4ca0-a852-e807c97d2fc8"
      profileName: "managed-main"
      profileRevision: 1
    release:
      repository: "registry.adminchatmate.com/kuberploy-qualification/projects/21a12574-8177-418f-b54e-4b1adc4cc301/services/5c45b120-001c-47f1-a1b5-e4a6cfe7a956/image"
      digest: "sha256:c08f1c2c2f42e47a7f0476ff1e00b4542db56d10461c33f44da57378e2ab1665"
  runtime:
    ports:
      -
        containerPort: 8080
        name: "http"
        protocol: "TCP"
        servicePort: 80
    probes:
      liveness:
        failureThreshold: 3
        httpGet:
          path: "/"
          port: "http"
          scheme: "HTTP"
        periodSeconds: 10
        timeoutSeconds: 2
      readiness:
        failureThreshold: 3
        httpGet:
          path: "/"
          port: "http"
          scheme: "HTTP"
        periodSeconds: 3
        timeoutSeconds: 2
    replicas: 1
    resources:
      limits:
        cpu: "250m"
        memory: "128Mi"
      requests:
        cpu: "10m"
        memory: "16Mi"
    strategy:
      type: "RollingUpdate"
    workloadType: "Deployment"
