{
  "apiVersion": "config.kuberploy.io/v1alpha1",
  "kind": "AppConfig",
  "metadata": {
    "id": "bfe523da-7f0e-4ab8-a0ca-ba8d2b765754",
    "name": "github"
  },
  "spec": {
    "applicationId": "bfe523da-7f0e-4ab8-a0ca-ba8d2b765754",
    "delivery": {
      "mode": "image",
      "registryPull": {
        "profileName": "managed-main",
        "profileRevision": 1,
        "targetId": "f0b03740-c7a9-4ca0-a852-e807c97d2fc8"
      },
      "release": {
        "digest": "sha256:2cb3532e3d79f2a63570eda30a7e841b22ae4c1e16bd55e9d407a0ef9afb43de",
        "repository": "registry.adminchatmate.com/kuberploy-qualification/projects/d329f441-87c5-4a54-a00a-be01316f64af/services/bfe523da-7f0e-4ab8-a0ca-ba8d2b765754/image"
      }
    },
    "environmentId": "00f171dd-1bf2-4dba-b173-9304ba56f3b3",
    "projectId": "d329f441-87c5-4a54-a00a-be01316f64af",
    "runtime": {
      "ports": [
        {
          "containerPort": 8080,
          "name": "http",
          "protocol": "TCP",
          "servicePort": 80
        }
      ],
      "replicas": 1,
      "resources": {
        "limits": {
          "cpu": "250m",
          "memory": "128Mi"
        },
        "requests": {
          "cpu": "25m",
          "memory": "32Mi"
        }
      },
      "strategy": {
        "type": "RollingUpdate"
      },
      "workloadType": "Deployment"
    }
  }
}
