{
  "apiVersion": "config.kuberploy.io/v1alpha1",
  "kind": "AppConfig",
  "metadata": {
    "id": "e8466062-962a-44a9-ac79-c799b84369df",
    "name": "rc314-web"
  },
  "spec": {
    "applicationId": "e8466062-962a-44a9-ac79-c799b84369df",
    "delivery": {
      "mode": "image",
      "registryPull": {
        "profileName": "managed-registry",
        "profileRevision": 3,
        "targetId": "f0b03740-c7a9-4ca0-a852-e807c97d2fc8"
      },
      "release": {
        "digest": "sha256:525297dc98599d25ab2e752b8e3491d6e4b10f2e5a8709c81252f36f8e90c56c",
        "repository": "registry.adminchatmate.com/kuberploy-qualification/projects/c996a286-e587-4359-aaba-c5e16f14e518/services/e8466062-962a-44a9-ac79-c799b84369df/image"
      }
    },
    "environmentId": "3ccdfa19-83ee-4f96-b094-40e49ac2c408",
    "projectId": "c996a286-e587-4359-aaba-c5e16f14e518",
    "routes": [
      {
        "dns": {
          "integrationRef": "cloudflare-foundation",
          "mode": "externalDns",
          "ttl": 300
        },
        "host": "kuberploy-qualification.adminchatmate.com",
        "id": "route-2c66e299b0",
        "ingressClassName": "traefik",
        "middlewareRefs": [],
        "path": "/",
        "port": "http",
        "tls": {
          "issuerRef": "kuberploy-dns01-production",
          "mode": "letsencrypt",
          "redirectHttp": true
        }
      }
    ],
    "runtime": {
      "args": [
        "netexec",
        "--http-port=8080"
      ],
      "command": [
        "/agnhost"
      ],
      "env": [],
      "ports": [
        {
          "containerPort": 8080,
          "name": "http",
          "protocol": "TCP"
        }
      ],
      "replicas": 1,
      "resources": {
        "requests": {
          "cpu": "50m",
          "memory": "100Mi"
        }
      },
      "strategy": {
        "type": "RollingUpdate"
      },
      "workloadType": "Deployment"
    }
  }
}
