apiVersion: config.kuberploy.io/v1alpha1
kind: AppConfig
metadata:
  id: "1e755791-b82b-42c2-b8e8-38dd8ffa9661"
  name: "rc414-gitssh-project-f73efb35"
spec:
  projectId: "2bf6981d-7dd0-4349-8669-9da02ca32ea7"
  applicationId: "1e755791-b82b-42c2-b8e8-38dd8ffa9661"
  environmentId: "a8ffa1a7-7cfa-498f-b0cb-22d1970f16e2"
  delivery:
    mode: image
    registryPull:
      targetId: "f0b03740-c7a9-4ca0-a852-e807c97d2fc8"
      profileName: "managed-main"
      profileRevision: 1
    release:
      repository: "registry.adminchatmate.com/kuberploy-qualification/projects/2bf6981d-7dd0-4349-8669-9da02ca32ea7/services/1e755791-b82b-42c2-b8e8-38dd8ffa9661/image"
      digest: "sha256:555f5c2f8252ab74bd0af4faedb9d07b94461538a513526cb8e603e785b97469"
  runtime:
    ports:
      -
        containerPort: 8080
        name: "http"
        protocol: "TCP"
        servicePort: 80
    probes:
      liveness:
        failureThreshold: 3
        httpGet:
          path: "/"
          port: "http"
          scheme: "HTTP"
        periodSeconds: 10
        timeoutSeconds: 2
      readiness:
        failureThreshold: 3
        httpGet:
          path: "/"
          port: "http"
          scheme: "HTTP"
        periodSeconds: 3
        timeoutSeconds: 2
    replicas: 1
    resources:
      limits:
        cpu: "250m"
        memory: "128Mi"
      requests:
        cpu: "10m"
        memory: "16Mi"
    strategy:
      type: "RollingUpdate"
    workloadType: "Deployment"
