apiVersion: config.kuberploy.io/v1alpha1
kind: AppConfig
metadata:
  id: "ec1fa5a3-0423-4cd1-9af0-dffab9ea5ee8"
  name: "rc414-gitssh-app-7814bbc4"
spec:
  projectId: "3ef0fb27-fcda-4d54-8a5f-707bdfcb5847"
  applicationId: "ec1fa5a3-0423-4cd1-9af0-dffab9ea5ee8"
  environmentId: "f9abd9f7-7698-4b94-9465-970b257b3043"
  delivery:
    mode: image
    registryPull:
      targetId: "f0b03740-c7a9-4ca0-a852-e807c97d2fc8"
      profileName: "managed-main"
      profileRevision: 1
    release:
      repository: "registry.adminchatmate.com/kuberploy-qualification/projects/3ef0fb27-fcda-4d54-8a5f-707bdfcb5847/services/ec1fa5a3-0423-4cd1-9af0-dffab9ea5ee8/image"
      digest: "sha256:a23576ac1fc602146478a682adeee55dfc9aea9ec88bede932ac17d0e076517a"
  runtime:
    ports:
      -
        containerPort: 3000
        name: "http"
        protocol: "TCP"
    replicas: 1
    resources:
      requests:
        cpu: "50m"
        memory: "100Mi"
    strategy:
      type: "RollingUpdate"
    workloadType: "Deployment"
