apiVersion: config.kuberploy.io/v1alpha1
kind: AppConfig
metadata:
  id: "b008e31d-cca3-4c2c-9cde-b76ee0d188a2"
  name: "rc356-oci-app"
spec:
  projectId: "f75773d7-0673-4b74-b9e3-8cefe7aa1bbe"
  applicationId: "b008e31d-cca3-4c2c-9cde-b76ee0d188a2"
  environmentId: "aec1ab12-4cff-4b18-af6b-2d75a59e09a4"
  delivery:
    mode: image
    release:
      repository: "docker.io/library/nginx"
      digest: "sha256:db35bfc6b2951e7f8a72db5db120288c127ffaeeb4a6d4b95a26fead017d5913"
  runtime:
    ports:
      -
        containerPort: 80
        name: "http"
        protocol: "TCP"
        servicePort: 80
    probes:
      liveness:
        failureThreshold: 6
        httpGet:
          path: "/"
          port: "http"
        periodSeconds: 10
        timeoutSeconds: 2
      readiness:
        failureThreshold: 12
        httpGet:
          path: "/"
          port: "http"
        periodSeconds: 5
        timeoutSeconds: 2
    replicas: 1
    resources:
      limits:
        cpu: "250m"
        memory: "128Mi"
      requests:
        cpu: "25m"
        memory: "32Mi"
    strategy:
      type: "RollingUpdate"
    workloadType: "Deployment"
