{
  "apiVersion": "config.kuberploy.io/v1alpha1",
  "kind": "AppConfig",
  "metadata": {
    "id": "585fdf32-d15e-466a-9a6c-20befe82afbd",
    "name": "rc361-github-builder"
  },
  "spec": {
    "applicationId": "585fdf32-d15e-466a-9a6c-20befe82afbd",
    "delivery": {
      "mode": "image",
      "registryPull": {
        "profileName": "managed-main",
        "profileRevision": 1,
        "targetId": "f0b03740-c7a9-4ca0-a852-e807c97d2fc8"
      },
      "release": {
        "digest": "sha256:829bb8f920c745976613e03d0f691ea21cf7d0846d2c71a220d9a0adaf76219a",
        "repository": "registry.adminchatmate.com/kuberploy-qualification/projects/70d3f00a-4d77-4745-b974-0b5cff1a3e33/services/585fdf32-d15e-466a-9a6c-20befe82afbd/image"
      }
    },
    "environmentId": "f19416a5-0760-4062-be0b-ece5af9f51c7",
    "projectId": "70d3f00a-4d77-4745-b974-0b5cff1a3e33",
    "runtime": {
      "ports": [
        {
          "containerPort": 8080,
          "name": "http",
          "protocol": "TCP"
        }
      ],
      "probes": {
        "liveness": {
          "failureThreshold": 3,
          "httpGet": {
            "path": "/",
            "port": "http"
          },
          "periodSeconds": 10,
          "timeoutSeconds": 2
        },
        "readiness": {
          "failureThreshold": 6,
          "httpGet": {
            "path": "/",
            "port": "http"
          },
          "periodSeconds": 5,
          "timeoutSeconds": 2
        }
      },
      "replicas": 1,
      "resources": {
        "limits": {
          "cpu": "500m",
          "memory": "256Mi"
        },
        "requests": {
          "cpu": "50m",
          "memory": "64Mi"
        }
      },
      "strategy": {
        "type": "RollingUpdate"
      },
      "workloadType": "Deployment"
    }
  }
}
