apiVersion: config.kuberploy.io/v1alpha1
kind: AppConfig
metadata:
  id: "96d5938a-82a6-4b54-ba18-52636500ef65"
  name: "rc414-gitssh-project-7805b73a"
spec:
  projectId: "2b5d5baf-bf06-4809-a18b-179082054c7b"
  applicationId: "96d5938a-82a6-4b54-ba18-52636500ef65"
  environmentId: "f837907c-aba6-4495-b05c-05624a3bd3ec"
  delivery:
    mode: image
    registryPull:
      targetId: "f0b03740-c7a9-4ca0-a852-e807c97d2fc8"
      profileName: "managed-main"
      profileRevision: 1
    release:
      repository: "registry.adminchatmate.com/kuberploy-qualification/projects/2b5d5baf-bf06-4809-a18b-179082054c7b/services/96d5938a-82a6-4b54-ba18-52636500ef65/image"
      digest: "sha256:2d372cad07fdd791636b71c12c49c982c04aea3728696b454e2ea874b98d162b"
  runtime:
    ports:
      -
        containerPort: 3000
        name: "http"
        protocol: "TCP"
    replicas: 1
    resources:
      requests:
        cpu: "50m"
        memory: "100Mi"
    strategy:
      type: "RollingUpdate"
    workloadType: "Deployment"
