apiVersion: config.kuberploy.io/v1alpha1
kind: AppConfig
metadata:
  id: "33ad7afe-5eb8-44f1-9844-de8d91001308"
  name: "rc402-private-oci-a7b96559"
spec:
  projectId: "ea186ebb-acbf-49b4-b8b5-54a02c5080a6"
  applicationId: "33ad7afe-5eb8-44f1-9844-de8d91001308"
  environmentId: "5d7af687-f604-4bd2-a39f-420a9dbb5622"
  delivery:
    mode: image
    registryPull:
      targetId: "f0b03740-c7a9-4ca0-a852-e807c97d2fc8"
      profileName: "managed-main"
      profileRevision: 1
    release:
      repository: "registry.adminchatmate.com/kuberploy-qualification/projects/ea186ebb-acbf-49b4-b8b5-54a02c5080a6/services/33ad7afe-5eb8-44f1-9844-de8d91001308/image"
      digest: "sha256:5f1956a16918827fda956c1db094cb74354d85e78287b6b38269205e4f73c7ba"
  runtime:
    ports:
      -
        containerPort: 8080
        name: "http"
        protocol: "TCP"
    replicas: 1
    resources:
      limits:
        cpu: "250m"
        memory: "128Mi"
      requests:
        cpu: "25m"
        memory: "32Mi"
    strategy:
      type: "RollingUpdate"
    workloadType: "Deployment"
