{
  "apiVersion": "config.kuberploy.io/v1alpha1",
  "kind": "AppConfig",
  "metadata": {
    "id": "245b3ca8-8b4d-4306-adb9-35fc8270bde3",
    "name": "builder-fixture"
  },
  "spec": {
    "applicationId": "245b3ca8-8b4d-4306-adb9-35fc8270bde3",
    "delivery": {
      "mode": "image",
      "registryPull": {
        "profileName": "managed-registry",
        "profileRevision": 5,
        "targetId": "f0b03740-c7a9-4ca0-a852-e807c97d2fc8"
      },
      "release": {
        "digest": "sha256:0acec282587fa362abb96fa2c6e4f9946716272d578b978c00b6a5ef08bbc98f",
        "repository": "registry.adminchatmate.com/kuberploy-qualification/projects/3821bcf5-83a9-4a72-9d10-9ee9ee6a4b73/services/245b3ca8-8b4d-4306-adb9-35fc8270bde3/image"
      }
    },
    "environmentId": "9ca3deb4-7de4-4404-ace6-0fd99ce95759",
    "middlewares": [
      {
        "name": "login",
        "profileRef": {
          "assignmentsDigest": "sha256:06e451a67962b47d37179a94108ffb5a30a5a9a6587fd6b0a9518e464ccde8d4",
          "profileId": "6006edf7-4b6c-4c16-9377-35c6876287b7",
          "revision": 1,
          "specDigest": "sha256:b8530680f4369b333f44c39bf1072eecdb0070bd8b4e9c2c6439a2d57a20eed3"
        },
        "spec": {
          "basicAuth": {
            "removeHeader": true,
            "secretBindingRef": {
              "bindingId": "369ecbf7-0564-4424-8274-1bab49a44efd",
              "key": "users",
              "name": "rc111-basic-auth",
              "version": 1
            }
          }
        }
      }
    ],
    "projectId": "3821bcf5-83a9-4a72-9d10-9ee9ee6a4b73",
    "routes": [
      {
        "dns": {
          "mode": "sslip"
        },
        "host": "kp-c219827b75931d3acb02.103-117-151-86.sslip.io",
        "id": "basic-auth",
        "ingressClassName": "traefik",
        "middlewareRefs": [
          "login"
        ],
        "path": "/",
        "port": "http",
        "tls": {
          "mode": "httpOnly"
        }
      }
    ],
    "runtime": {
      "env": [
        {
          "name": "RC_RUNTIME_ONLY",
          "value": "live-runtime-only"
        }
      ],
      "ports": [
        {
          "containerPort": 8080,
          "name": "http",
          "protocol": "TCP"
        }
      ],
      "replicas": 2,
      "resources": {
        "requests": {
          "cpu": "100m",
          "memory": "128Mi"
        }
      },
      "strategy": {
        "type": "Recreate"
      }
    }
  }
}
