apiVersion: config.kuberploy.io/v1alpha1
kind: AppConfig
metadata:
  id: "68cbbdac-6b04-46d5-9265-f4521590f0e6"
  name: "rc414-public-oci-20260911224313"
spec:
  projectId: "4e13df4a-53c2-4f43-b745-2c4584ca8e05"
  applicationId: "68cbbdac-6b04-46d5-9265-f4521590f0e6"
  environmentId: "34da39d7-8f1f-4db6-9dba-8c22685911ea"
  delivery:
    mode: image
    release:
      repository: "registry.k8s.io/e2e-test-images/agnhost"
      digest: "sha256:99c6b4bb4a1e1df3f0b3752168c89358794d02258ebebc26bf21c29399011a85"
  runtime:
    args:
      - "netexec"
      - "--http-port=8080"
      - "--udp-port=-1"
    command:
      - "/agnhost"
    env:
      -
        name: "RC414_RUNTIME"
        value: "initial"
    ports:
      -
        containerPort: 8080
        name: "http"
        protocol: "TCP"
        servicePort: 80
    probes:
      liveness:
        failureThreshold: 3
        httpGet:
          path: "/echo?msg=live"
          port: "http"
          scheme: "HTTP"
        periodSeconds: 10
        timeoutSeconds: 2
      readiness:
        failureThreshold: 3
        httpGet:
          path: "/echo?msg=ready"
          port: "http"
          scheme: "HTTP"
        periodSeconds: 3
        timeoutSeconds: 2
      startup:
        failureThreshold: 30
        periodSeconds: 2
        tcpSocket:
          port: "http"
        timeoutSeconds: 1
    replicas: 1
    resources:
      limits:
        cpu: "100m"
        memory: "64Mi"
      requests:
        cpu: "10m"
        memory: "16Mi"
    strategy:
      type: "RollingUpdate"
    terminationGracePeriodSeconds: 20
    workingDirectory: "/"
    workloadType: "Deployment"
