apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: "rc281-http01"
  labels:
    app.kubernetes.io/managed-by: "kuberploy"
    kuberploy.io/certificate-issuer-profile: "rc281-http01"
  annotations:
    kuberploy.io/certificate-issuer-spec-digest: "sha256:09be804bffaa834b1023b6b82cfe4c2fa2964e82352dedf86a8e71af09f07f1d"
    kuberploy.io/certificate-issuer-revision: "1"
spec:
  acme:
    email: "acme-qualification@adminchatmate.com"
    server: "https://acme-v02.api.letsencrypt.org/directory"
    privateKeySecretRef:
      name: "rc281-http01-account-v1"
    solvers:
      - http01:
          ingress:
            ingressClassName: "traefik"
            ingressTemplate:
              metadata:
                annotations:
                  external-dns.alpha.kubernetes.io/ingress-hostname-source: "annotation-only"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "kuberploy-ci-observer-434ac9249dd6843dc798"
  labels:
    app.kubernetes.io/managed-by: "kuberploy"
    kuberploy.io/certificate-issuer-profile: "rc281-http01"
rules:
  - apiGroups:
      - "cert-manager.io"
    resources:
      - "clusterissuers"
    resourceNames:
      - "rc281-http01"
    verbs:
      - "get"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "kuberploy-ci-observer-434ac9249dd6843dc798"
  labels:
    app.kubernetes.io/managed-by: "kuberploy"
    kuberploy.io/certificate-issuer-profile: "rc281-http01"
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: ClusterRole
  name: "kuberploy-ci-observer-434ac9249dd6843dc798"
subjects:
  - kind: ServiceAccount
    name: "kuberploy-worker"
    namespace: "kuberploy-system"
